### ISSUE TITLE
SchemaOperationProcessEngineClose called even if no DbSqlSession available

### ISSUE THREAD

**Issue by kovadam69** [Activiti/Activiti#1037]
I try to switch the persistence layer, and I disabled the usage of the DbSqlSession by setting the usingRelationalDatabase property to false in the ProcessEngineConfiguration. I use the processEngine with spring integration. Everything seems to be fine, except that at the end when the processEngine is being closed in the ProcessEngine close method following line is executed:

commandExecutor.execute(processEngineConfiguration.getSchemaCommandConfig(), new SchemaOperationProcessEngineClose());

which results in an exception, since this will require a DbSqlSession to be present, which is not in my case.

The exceptions is:

ERROR [org.activiti.engine.impl.interceptor.CommandContext] - <Error while closing command context>
org.activiti.engine.ActivitiException: no session factory configured for org.activiti.engine.impl.db.DbSqlSession
    at org.activiti.engine.impl.interceptor.CommandContext.getSession(CommandContext.java:281)
    at org.activiti.engine.impl.interceptor.CommandContext.getDbSqlSession(CommandContext.java:295)
    at org.activiti.engine.impl.SchemaOperationProcessEngineClose.execute(SchemaOperationProcessEngineClose.java:25)
    at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:38)
    at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:79)
    at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:58)
    at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:43)
    at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
    at org.activiti.engine.impl.ProcessEngineImpl.close(ProcessEngineImpl.java:109)
    at org.activiti.spring.ProcessEngineFactoryBean.destroy(ProcessEngineFactoryBean.java:41)
    at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:272)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:975)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:982)
    at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1028)
    at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1004)
    at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:956)

**Comment by kovadam69** [comment]
Forget to mention:
Activiti version 6.0.0.4 (beta4)

**Comment by Salaboy** [comment]
@kovadam69 have you tried Activiti 6 Final? is this still an issue? 
I'm closing this issue, but feel free to reopen if this is still an issue with version 6 Final.
