### ISSUE TITLE
Integrating Spring application with Activiti causing EL conflict

### ISSUE THREAD

**Issue by Manojpkulakarni** [Activiti/Activiti#1038]
**I am getting the below error when I am integrating our application with activiti.**

Caused by: java.lang.ExceptionInInitializerError
    at org.apache.jasper.compiler.Validator$ValidateVisitor.getJspAttribute(Validator.java:1390)
    at org.apache.jasper.compiler.Validator$ValidateVisitor.checkXmlAttributes(Validator.java:1204)
    at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:855)
    at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1535)
    at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2375)
    at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2427)
    at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2433)
    at org.apache.jasper.compiler.Node$Root.accept(Node.java:464)
    at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2375)
    at org.apache.jasper.compiler.Validator.validateExDirectives(Validator.java:1819)
    at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:218)
    at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
    at org.apache.jasper.compiler.Compiler.compile(Compiler.java:334)
    at org.apache.jasper.compiler.Compiler.compile(Compiler.java:321)
    at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:652)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:358)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:402)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:346)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:81)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.jsp.JspFileHandler.handleRequest(JspFileHandler.java:32)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:265)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToServlet(ServletInitialHandler.java:210)
    at io.undertow.servlet.spec.RequestDispatcherImpl.includeImpl(RequestDispatcherImpl.java:343)
    at io.undertow.servlet.spec.RequestDispatcherImpl.include(RequestDispatcherImpl.java:256)
    at org.apache.tiles.request.servlet.ServletRequest.doInclude(ServletRequest.java:243)
    ... 38 more
Caused by: java.lang.NullPointerException
    at javax.el.CompositeELResolver.add(CompositeELResolver.java:117)
    at org.apache.jasper.el.ELContextImpl.<clinit>(ELContextImpl.java:87)
    ... 70 more

 **We resolved it temporarily by deleting juel-spi-2.2.7.jar and added javax.el-3.0.1-b05.jar in the lib folder with an entry in Manifest.mf file of javax.el-3.0.1-b05.jar as below**

Fragment-Host: de.odysseus.juel-api

We followed this link to fix the issue: http://stackoverflow.com/questions/15905471/juel-set-up-doesnt-work.

**Could you please tell us can we expect this fix with activiti or if any other solution is there?**

**Comment by yuanqiangxie** [comment]
I have the same problem, anyone can help me?

**Comment by qinsky** [comment]
you could edit "activiti-engine-6.0.0.pom" to remove juel-api.jar and juel-spi.jar ,like this:

**Comment by qinsky** [comment]
Your could edit "activiti-engine-6.0.0.pom" to remove juel-api and juel-spi dependency . @yuanqiangxie @Manojpkulakarni

**Comment by Salaboy** [comment]
@qinsky I'm closing this issue due to inactivity. Replacing such libraries is usually not recommend without building the whole project again to make sure that no test fail. Please re-open if this is still an issue and you want to help us to test your solution.
