### ISSUE TITLE
Migration - Error when migration process instance from Activiti 5.21.0 to Activiti 6

### ISSUE THREAD

**Issue by minhquankq** [Activiti/Activiti#1311]
Hi all,
I have handled migration activiti from 5.21.0 to 6.0.0 by guide from https://www.activiti.org/migration.html
(I have updated  file `activiti-rest/WEB-INF/classes/activiti-custom-context.xml` to set activiti5CompatibilityEnabled and activiti5CompatibilityHandlerFactory
```
<bean id="activiti5CompabilityFactory" class="org.activiti.compatibility.spring.SpringActiviti5CompatibilityHandlerFactory" />
<bean id="processEngineConfiguration" class="org.activiti.spring.SpringProcessEngineConfiguration">
   .........
    <property name="activiti5CompatibilityEnabled" value="true" />
    <property name="activiti5CompatibilityHandlerFactory" ref="activiti5CompabilityFactory" />
</bean>
``` 
 and copy activiti5-compatibility-6.0.0.jar, activiti5-engine-6.0.0.jar, activiti5-spring-6.0.0.jar, activiti5-spring-compatibility-6.0.0.jar to activiti-rest's libs)

and I had a active process instance in old version as below
![selection_107](https://user-images.githubusercontent.com/18256815/28764688-07f5ac60-75f1-11e7-9e12-4d5f9602d58f.png)
after migration, I still got a this process instance, but when I submit user task, and service task execute and throw BpmnError, the BoundaryEvent can not catch this exception, I got an error in log
```
03:29:59,686 [activiti-async-job-executor-thread-2] ERROR org.activiti.engine.impl.interceptor.CommandContext  - Error while closing command context
org.activiti.engine.ActivitiException: Programmatic error: no parent scope execution found for boundary event
  at org.activiti.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior.executeInterruptingBehavior(BoundaryEventActivityBehavior.java:85)
  at org.activiti.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior.trigger(BoundaryEventActivityBehavior.java:56)
  at org.activiti.engine.impl.agenda.TriggerExecutionOperation.run(TriggerExecutionOperation.java:38)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
  at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
  at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
  at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
  at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
  at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
  at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:97)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:75)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
03:29:59,888 [activiti-async-job-executor-thread-2] ERROR org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable  - Job 235003 failed
org.activiti.engine.ActivitiException: Programmatic error: no parent scope execution found for boundary event
  at org.activiti.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior.executeInterruptingBehavior(BoundaryEventActivityBehavior.java:85)
  at org.activiti.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior.trigger(BoundaryEventActivityBehavior.java:56)
  at org.activiti.engine.impl.agenda.TriggerExecutionOperation.run(TriggerExecutionOperation.java:38)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
  at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
  at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
  at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
  at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
  at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
  at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:97)
  at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:75)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```
Please help!

**Comment by balsarori** [comment]
You can ask in the community forums here https://community.alfresco.com/community/bpm

It will be very useful if you can write a small unit test (and maybe some steps) that helps reproducing the issue.
