### ISSUE TITLE
Check assertion plugin configuration because it is being triggered when mvn spring-boot:run

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1343]
When running spring-boot:run on the activiti-services-audit-jpa we get: 
====================================
AssertJ assertions generation report
====================================

--- Generator input parameters ---

Generating AssertJ assertions for classes in following packages and subpackages:
- org.activiti.services.core.model
- org.activiti.services.audit.events

Generating AssertJ assertions for classes:
- org.springframework.http.ResponseEntity

--- Generator results ---

Assertions failed with error : null
- Given classes were : [org.springframework.http.ResponseEntity]
- Given packages were : [org.activiti.services.core.model, org.activiti.services.audit.events]

Full error stack : java.lang.NullPointerException
	at org.assertj.assertions.generator.util.ClassUtil.getClassesInDirectory(ClassUtil.java:183)
	at org.assertj.assertions.generator.util.ClassUtil.getClassesInDirectory(ClassUtil.java:205)
	at org.assertj.assertions.generator.util.ClassUtil.getPackageClassesFromClasspathFiles(ClassUtil.java:155)
	at org.assertj.assertions.generator.util.ClassUtil.getClassesInPackage(ClassUtil.java:119)
	at org.assertj.assertions.generator.util.ClassUtil.collectClasses(ClassUtil.java:100)
	at org.assertj.maven.generator.AssertionsGenerator.generateAssertionsFor(AssertionsGenerator.java:106)
	at org.assertj.maven.AssertJAssertionsGeneratorMojo.executeWithAssertionGenerator(AssertJAssertionsGeneratorMojo.java:169)
	at org.assertj.maven.AssertJAssertionsGeneratorMojo.execute(AssertJAssertionsGeneratorMojo.java:160)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by Salaboy** [comment]
@erdemedeiros is this still a problem?

**Comment by erdemedeiros** [comment]
No work has been done to fix it. However, it might get fixed by boot upgrades.

**Comment by mteodori** [comment]
obsolete
