### ISSUE TITLE
activiti#MySQLIntegrityConstraintViolationException happens, how can i fix it?

### ISSUE THREAD

**Issue by 4codingHu** [Activiti/Activiti#1475]
When I complete the task, an exception happened!

16:40:50.348 [http-nio-8161-exec-1] ERROR org.activiti.engine.impl.interceptor.CommandContext - Error while closing command context
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`tops_finance`.`act
_ru_variable`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`))
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`tops_finance`.`act_ru_variable`, CONSTRAINT 
`ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`))
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.3.1.jar:3.3.1]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:172) ~[mybatis-3.3.1.jar:3.3.1]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:185) ~[mybatis-3.3.1.jar:3.3.1]
        at org.activiti.engine.impl.db.DbSqlSession$CheckedDeleteOperation.execute(DbSqlSession.java:293) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.db.DbSqlSession.flushRegularDeletes(DbSqlSession.java:897) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.db.DbSqlSession.flushDeletes(DbSqlSession.java:890) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:617) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:212) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:138) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:66) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-5.22.0.jar:5.22.0]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.3.6.RELEASE.jar:4.3.6.RELEASE]
        at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) ~[activiti-engine-5.22.0.jar:5.22.0]
        at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:182) ~[activiti-engine-5.22.0.jar:5.22.0]

**Comment by nbqyqx** [comment]
any update？

**Comment by daisuke-yoshimoto** [comment]
@4codingHu @nbqyqx I'm sorry for the delay in answering.
However, it can not be reproduced, so it can not be investigated.

Please provide the code and process definition  to reproduce.

**Comment by daisuke-yoshimoto** [comment]
@4codingHu @nbqyqx Any update?
Can I close this issue?

**Comment by nbqyqx** [comment]
no, the issue was reported occasionally. How can I have the entry in  act_ru_variable  but not exist in ACT_RU_EXECUTION?

**Comment by nbqyqx** [comment]
We have had the issue twice in October and once in November by now.

**Comment by daisuke-yoshimoto** [comment]
https://activiti.atlassian.net/browse/ACT-4320

**Comment by daisuke-yoshimoto** [comment]
@4codingHu @nbqyqx 
Well, I'm sorry, but I do not know the condition to reproduce, so it is difficult to investigate. 
Can you get a process definition or code at which an event occurs?

By the way, if it happens only occasionally, it may be an exclusive error.

**Comment by 4codingHu** [comment]
ok. 
It's difficult to reproduce the question. You can close this issue. 
when the question occurs again, we try to get more clues and the whole environment data, then reopen this issue.

**Comment by daisuke-yoshimoto** [comment]
@4codingHu 
No, I will not close this issue.

But, please give me some more information to reproduce.
Can you get a process definition or code at which an event occurs?

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
You are assigned to a ticket, so do you know something about this error?
https://activiti.atlassian.net/browse/ACT-4320

**Comment by EduFrazao** [comment]
Hi folks. Its happenning here too, with Oracle 11g and Activiti 5.22. I've note that some dupplicate variables are present after complete some multi instance user tasks. This causes problems when trying to finish this tasks.
Any news?
This atlassian links are not working.

**Comment by albans** [comment]
Hello, 

Almost same settings than @EduFrazao, same remark. We have duplicated process variables (same process instance, same execution identifier). We are also in a situation where the process instance raises several user tasks,  but the user-tasks themselves are not multi-instance. Instead they are part of a multi-instance embedded sub-process.

If I retry the failed job, it fails again for the same reason. But if I delete the duplicate process variables and retry, then the process continues. 

The problem seems to be, as suggested by @EduFrazao, coming from the duplicated process variables. Indeed if you observe the way variables are collected and deleted in class `ExecutionEntity`, it seems the implementation will fail to delete all variables from an execution if there are several variables with the same name attached to the same execution. Somehow the method deleting the process variables iterates over a map indexing the process variables by name. 

An obvious solution would be to keep the list of all process variables as a property of variable scope, and iterate over this list instead of the map when deleting an execution. But it seems the variables within a scope are really meant to have different names, and therefore we wouldn't be fixing the cause of the issue, but its consequence.

**Comment by 4codingHu** [comment]
Got it. 

Thx

> 在 2019年9月27日，下午5:02，Alban Scholer <notifications@github.com> 写道：
> 
> variables
