### ISSUE TITLE
timeDuration not support PnW

### ISSUE THREAD

**Issue by zhanzhanqi** [Activiti/Activiti#1865]
I test timerEventDefinition. timeDuration with “P2W”, but it does not work and show up with exceptions as below:
```
Caused by: java.lang.IllegalArgumentException: P2W
	at com.sun.org.apache.xerces.internal.jaxp.datatype.DurationImpl.organizeParts(DurationImpl.java:612)
	at com.sun.org.apache.xerces.internal.jaxp.datatype.DurationImpl.<init>(DurationImpl.java:524)
	at com.sun.org.apache.xerces.internal.jaxp.datatype.DatatypeFactoryImpl.newDuration(DatatypeFactoryImpl.java:104)
```

Then I google the timer standard ISO 8601, it says the duration support "YMWDHMS" with "W" designators that follows the value for the number of weeks. (https://en.wikipedia.org/wiki/ISO_8601)

Then I dig into the exception code `DurationImpl` init method using in `org.activiti.engine.impl.calendar.DurationHelper`, it says it only support for "YMDHMS" not for "W". So I confirm it must be a bug and should be fixed. As a solution we can use `java.time.Period` to parse the ISO 8601 timer patterns.

**Comment by Salaboy** [comment]
@zhanzhanqi we will appreciate if you can provide a reproducer so we can quickly fix the issue. A simple maven project with a JUnit reproducing the issue will be great. A pull request with a failing test to the activiti repository will be even better.

**Comment by Salaboy** [comment]
If you also mention which version are you using that will be great

**Comment by daisuke-yoshimoto** [comment]
@zhanzhanqi @Salaboy
 
PnW is not supported now.
DurationHelper use DatatypeFactory#newDuration(java.lang.String) for parsing timeDuration.
https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/calendar/DurationHelper.java#L213
DatatypeFactory#newDuration(java.lang.String) support only "PnYnMnDTnHnMnS". So, timeDuration doesn't support PnW.
https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/DatatypeFactory.html#newDuration-java.lang.String-

https://community.alfresco.com/thread/228372-are-there-any-known-issues-using-p1w-as-a-time-duration
