### ISSUE TITLE
Service is not unregistered

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1867]
After i undeploy services, the actuator/routes endpoint still returns those services
as 'running'(t is not a short delay issue), but they should be disappeared. 
```
{
    "/audit/**": "audit",
    "/rb-my-app/**": "rb-my-app",
    "/query/**": "query",
    "/application-new-1-rb/**": "application-new-1-rb",
    "/application-new-1-query/**": "application-new-1-query",
    "/application-new-2-rb/**": "application-new-2-rb",
    "/application-new-2-query/**": "application-new-2-query"
}
```

The service is undeployed(i found this problem running on kubernetes)
so when i try to call the service via gateway i get a 500 rather than 404
because it is still registered somehow.

On the gateway logs:
```
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: application-new-2-rb.application-new-2: Name does not resolve
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340) ~[rxjava-1.3.4.jar!/:1.3.4]
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112) ~[ribbon-loadbalancer-2.2.4.jar!/:2.2.4]
	... 127 common frames omitted
Caused by: java.net.UnknownHostException: application-new-2-rb.application-new-2: Name does not resolve
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_151]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_151]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_151]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_151]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_151]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_151]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.3.jar!/:4.5.3]
	at org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient.execute(RibbonLoadBalancingHttpClient.java:86) ~[spring-cloud-netflix-core-2.0.0.M5.jar!/:2.0.0.M5]
	at org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient.execute(RibbonLoadBalancingHttpClient.java:42) ~[spring-cloud-netflix-core-2.0.0.M5.jar!/:2.0.0.M5]
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104) ~[ribbon-loadbalancer-2.2.4.jar!/:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303) ~[ribbon-loadbalancer-2.2.4.jar!/:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287) ~[ribbon-loadbalancer-2.2.4.jar!/:2.2.4]
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10256) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:286) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onNext(OnSubscribeConcatMap.java:144) ~[rxjava-1.3.4.jar!/:1.3.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185) ~[ribbon-loadbalancer-2.2.4.jar!/:2.2.4]
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180) ~[ribbon-loadbalancer-2.2.4.jar!/:2.2.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10256) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.Observable.unsafeSubscribe(Observable.java:10256) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.Observable.subscribe(Observable.java:10352) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.Observable.subscribe(Observable.java:10319) ~[rxjava-1.3.4.jar!/:1.3.4]
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) ~[rxjava-1.3.4.jar!/:1.3.4]
	... 129 common frames omitted

```

**Comment by Salaboy** [comment]
@ffazzini is this still a problem?

**Comment by ryandawsonuk** [comment]
It seems the problem is that our services aren't currently reporting themselves as down to eureka.

I'm currently seeing:

![image](https://user-images.githubusercontent.com/22754674/39538020-403ec05a-4e33-11e8-869a-566f9833e6e7.png)

But those services are all down. Their routes are still in the gateway but if I call query I get "java.net.UnknownHostException: activiti-cloud-query"
