### ISSUE TITLE
Deadlock during update of Activiti tables

### ISSUE THREAD

**Issue by krkumar6969** [Activiti/Activiti#1890]
We encountered a deadlock during update of one of the Activiti tables in our application. Here is the snippet of the error:

Exception stack is:
1. ORA-00060: deadlock detected while waiting for resource
(java.sgl.SQLException)
oracle.jdbc.driver.DatabaseError:113 (null)
2.
### SQL: update ACT_GE_BYTEARRAY set REV_ = ?, BYTES_ = ? where ID_ = ? and REV_= ?
Cause: java.sgl.SQLException: ORA-00060: deadlock detected while waiting for resource
(org.apache.ibatis.exceptions.PersistenceException)
org.apache.ibatis.exceptions.ExceptionFactory:23 (null)

**Here is the more detailed trace:**

SEVERE: Error while closing command context org.apache.ibatis.exceptions.PersistenceException: ### Error updating database. Cause: java.sql.SQLException: ORA-00060: deadlock detected while waiting for resource ### The error may involve org.activiti.engine.impl.persistence.entity.VariableInstanceEntity.updateByteArray-Inline ### The error occurred while setting parameters ### SQL: update ACT_GE_BYTEARRAY set REV_ = ?, BYTES_ = ? where ID_ = ? and REV_ = ? ### Cause: java.sql.SQLException: ORA-00060: deadlock detected while waiting for resource at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23) at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:147) at org.activiti.engine.impl.db.DbSqlSession.flushUpdates(DbSqlSession.java:650) at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:460) at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:167) at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:114) at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:69) at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:42) at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130) at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:40) at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:32) at org.activiti.engine.impl.RuntimeServiceImpl.signal(RuntimeServiceImpl.java:170) at 

What could be the potential problem? Please let us know how we can avoid this error in the future? We are currently using Activiti v5.11, Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production and Red Hat 4.1.2-48

**Comment by Salaboy** [comment]
@krkumar6969 thanks for reporting this issue, can you please try 5.22? if that issue is not solved in that version we need to find a way to reproduce it.
