### ISSUE TITLE
ReflectUtil.loadClass(String) throws `java.lang.ClassNotFoundException: int` on primitive types

### ISSUE THREAD

**Issue by raja-anbazhagan** [Activiti/Activiti#1905]
We are using activiti version 5.18.0 and it was working fine as a spring mvc application. But since the application is converted to Spring boot 2, the executions fails with a weird ClassNotFoundException for primitive types.

Here is a sample exception.

Caused by: org.activiti.engine.ActivitiException: Couldn't deserialize object in variable 'executionObject'
        at org.activiti.engine.impl.variable.SerializableType.deserialize(SerializableType.java:112)
        at org.activiti.engine.impl.variable.DeserializedObject.flush(DeserializedObject.java:43)
        at org.activiti.engine.impl.db.DbSqlSession.flushDeserializedObjects(DbSqlSession.java:700)
        at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:576)
        at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:211)
        at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:137)
        at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:66)
        at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
        at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:37)
        at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
        at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
        at org.activiti.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:77)
        at com.tcl.gvg.itsm.activiti.ActivitiServiceImpl.executeActivity(ActivitiServiceImpl.java:518)
        ... 199 more
Caused by: org.activiti.engine.ActivitiClassLoadingException: Class not found: int
        at org.activiti.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:87)
        at org.activiti.engine.impl.variable.SerializableType$1.resolveClass(SerializableType.java:126)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1859)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1745)
        at java.io.ObjectInputStream.readClass(ObjectInputStream.java:1710)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1550)
        at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1966)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1561)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2278)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2278)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2278)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2278)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2278)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2202)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
        at org.activiti.engine.impl.variable.SerializableType.deserialize(SerializableType.java:108)
        ... 213 more
Caused by: java.lang.ClassNotFoundException: int
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:70)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1136)
        at org.activiti.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:291)
        at org.activiti.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:68)
        ... 242 more

Here is a possible workaround.

```
    protected static final String[] PRIMITIVE_NAMES = new String[] { "boolean",
            "byte", "char", "double", "float", "int", "long", "short", "void" };

    protected static final Class<?>[] PRIMITIVES = new Class[] { boolean.class,
            byte.class, char.class, double.class, float.class, int.class,
            long.class, short.class, Void.TYPE };

    protected static Class<?> forNamePrimitive(String name) {
        if (name.length() <= 8) {
            int p = Arrays.binarySearch(PRIMITIVE_NAMES, name);
            if (p >= 0) {
                return PRIMITIVES[p];
            }
        }
        return null;
    }
```

and then the loadClass can have a check if the class name is falling under primitive type to resolve a class or else follow the existing implementation.

**Comment by raja-anbazhagan** [comment]
Raised pull request #1909 for the same.

**Comment by balsarori** [comment]
Any reason not to use the latest 5.22? Did you try to re-produce on 5.22?

**Comment by balsarori** [comment]
@raja-anbazhagan thanks for confirming the versions. 

I'm interested knowing how to reproduce this issue. Can you provide a simple example/unit test to show how can this can be reproduced?

**Comment by raja-anbazhagan** [comment]
@balsarori Unfortunately I don't have a reproducible example because it happens in our production. I remote debugged the whole executionObject and i didn't see a thing that matches an `int` type... 
My guess is that the spring and hibernate have something do with it(proxy objects may be?).

As per the business logic, the variable goes through a lot of other frameworks like spring and hibernate which has their influences 

But fundamentally, the ReflectUtil doesn't do its purpose on its full responsibility. So I had to  create this PR.

I will try my best.

**Comment by raja-anbazhagan** [comment]
@balsarori  Would it be okay if I just add the unit cases for ReflectUtil? I couldn't reproduce this issue via a test case because I have no control on what is happening with the object before it was serialized.

**Comment by balsarori** [comment]
@raja-anbazhagan the engine shouldn't serialize primitive type.  
An exception like ```java.lang.ClassNotFoundException: int``` should never happen. If you can provide an example where the engine will attempt to seriialize a primitive type that will help.

@Salaboy @erdemedeiros @ryandawsonuk since you guys are using spring boot 2, are you guys aware of this or know if this can happen (engine serializing primitive types)?

**Comment by Salaboy** [comment]
I think that it should work in Spring Boot 2, mostly because we upgraded the engine to use Spring 5. I guess that if you try to use spring boot 2 with the old version of spring provided in Activiti 5.x and 6.x that will cause issues. 

@raja-anbazhagan if you can create a reproducer we can make sure that in Activiti 7 this doesn't happen.

**Comment by raja-anbazhagan** [comment]
@balsarori I agree. **`java.lang.ClassNotFoundException: int` should never happen.**  In java, You shouldn't even worry about primitive types being serialized. Because these primitive values will be boxed to their respective Wrapper classes. 

This issue was never observed when the application was running with 5.22.0 as a spring MVC application that runs as a war file on tomcat 8.5.29.


@Salaboy As I said earlier, I could not reproduce this issue for two reasons. 
  1. The environment where this is observed is too big and complicated to replicate. it involves various frameworks.
2. **`java.lang.ClassNotFoundException: int` should never happen.**  

For what I know, There are frameworks, pretty popular ones use the workaround that I suggested.

**Comment by raja-anbazhagan** [comment]
Team, Are we going to do anything about this?

**Comment by Salaboy** [comment]
@raja-anbazhagan I know that @balsarori is investigating the problem. Without a reproducer is hard. Because something that looks like a fix might be hiding the real problem. We are a small team and things might take a lot of time if we need to come up with a reproducer for a complex scenario like yours. We will appreciate help on that front. Regarding "The environment where this is observed is too big and complicated to replicate. it involves various frameworks and business logics", I haven't seen any case where a simple reproducer cannot be created to simulate what is happening. If you do a debug session of your application, you should be able to see the trace of which classes are invoked and hence create a simple project that execute a process in similar circumstances.

**Comment by raja-anbazhagan** [comment]
This might interest you. 

Apparently an object of type `org.hibernate.proxy.pojo.javassist.SerializableProxy` is the one that doesn't get serialized. I will have to sweep the entire 300+ classes for any primitive type arguments in setters for a wrapper field. At Least that's what I think i should do.

![debug](https://user-images.githubusercontent.com/8947215/41175516-f89007c2-6b7a-11e8-959e-6c695e6b7e8d.png)

Any thoughts? Sorry it took some time

**Comment by raja-anbazhagan** [comment]
This is embarrassing. One of the JPA entity was having a field that has setters for both `int` and `Integer`. Removing the inappropriate one solved the problem. I also have to mention that the javassist versions of the mvc application is different from the one that comes with spring boot 2.0.2.

**Comment by Salaboy** [comment]
@raja-anbazhagan no problem, these things happens all the time, and that's the main reason why we cannot apply a random patch without making sure that we can reproduce the issue in a consistent way first. 
Thanks a lot for closing the issue :)

**Comment by raja-anbazhagan** [comment]
Now I'm sure that Activiti is not causing the problem. However, I still have the urge to know why your custom implementation of ObjectInputStream doesn't handle primitive classes when the original implementation of ObjectInputStream has such behaviour.
See this comment https://github.com/Activiti/Activiti/pull/1909#issuecomment-395865104
