### ISSUE TITLE
The error occurred while setting parameters 

### ISSUE THREAD

**Issue by rocky-chen** [Activiti/Activiti#1914]
Hi there,

I keep getting the following error and it caused the timer job failed.  May I ask if anyone knows what the problem is?  Thanks

```
org.activiti.engine.ActivitiException:  
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block 
### The error may exist in org/activiti/db/mapping/entity/HistoricVariableInstance.xml 
### The error may involve defaultParameterMap 
### The error occurred while setting parameters 
### SQL: select * from ACT_HI_VARINST where ID_ = ? 
### Cause: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block  
at org.activiti.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:119)  
at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:180)  
at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:131)  
at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:89)  
at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:55)  
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)  
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)  
at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)  
at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)  
at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)  
at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)  
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)  
at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)  
at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)  
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)  
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)  
at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:97)  
at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:75)  
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  
at java.lang.Thread.run(Thread.java:748) Caused by: org.apache.ibatis.exceptions.PersistenceException:  
```

**Comment by balsarori** [comment]
@rocky-chen can you share your process definition or maybe a simple unit test to help reproduce the issue?

**Comment by rocky-chen** [comment]
Hi @balsarori ,  thank you for getting back to me.  May I ask what process definition is?  Is it the bpmn file?

**Comment by balsarori** [comment]
@rocky-chen yes it's the bpmn file (XML file)
