### ISSUE TITLE
kill a connector pod and the rb to connector stream breaks

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1940]
Start a runtime bundle and connector example. I did this with:

https://github.com/ryandawsonuk/environment-ferretmaze-staging/blob/41087fe1c28d956b1307fb6de7c5965785009fc8/env/values.yaml

Now you can start a process instance for the connector process with this payload at /rb-my-app/v1/process-instances:

{
  "processDefinitionKey": "ConnectorProcess",
  "commandType":"START_PROCESS"
}

That works. So now kill the connector pod with `kubectl delete pod`. And when it comes up then try again. You get:

org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'Example Connector' is expected to be of type 'org.activiti.runtime.api.connector.Connector' but was actually of type 'org.springframework.integration.channel.DirectChannel'
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:389)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1095)
at org.activiti.runtime.api.connector.DefaultServiceTaskBehavior.execute(DefaultServiceTaskBehavior.java:38)
at org.activiti.services.connectors.behavior.MQServiceTaskBehavior.execute(MQServiceTaskBehavior.java:60)
at org.activiti.engine.impl.delegate.ActivityBehaviorInvocation.invoke(ActivityBehaviorInvocation.java:35)
at org.activiti.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:35)
at org.activiti.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
at org.activiti.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:88)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:210)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:146)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:101)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:66)
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
at org.activiti.engine.impl.RuntimeServiceImpl.startProcessInstance(RuntimeServiceImpl.java:524)
at org.activiti.engine.impl.runtime.ProcessInstanceBuilderImpl.start(ProcessInstanceBuilderImpl.java:114)
at org.activiti.runtime.api.model.builder.impl.ProcessStarterImpl.doIt(ProcessStarterImpl.java:71)
at org.activiti.runtime.api.model.builder.impl.ProcessStarterImpl.doIt(ProcessStarterImpl.java:26)
at org.activiti.cloud.services.core.pageable.SecurityAwareProcessInstanceService.startProcess(SecurityAwareProcessInstanceService.java:101)

Note this happens without making any changes to either image - just killing the connector and letting an instance come back up with the same image is enough to recreate the issue.

If you then kill the runtime bundle and let that come back up then it works again. I'm not 100% sure but I don't think this was happening before the most recent refactoring.

**Comment by ryandawsonuk** [comment]
This is now working for me
