### ISSUE TITLE
why  was  "commandExecutor" Properties always threw an exception ("NullpointException") ？

### ISSUE THREAD

**Issue by zhaogituser** [Activiti/Activiti#1948]
`public long count() {  
    this.resultType = ResultType.COUNT;
    if (commandExecutor!=null) {
      return (Long) commandExecutor.execute(this);
    }
    return executeCount(Context.getCommandContext());
  }`

**Comment by Salaboy** [comment]
@zhaogituser what? where? where is that code running? Are you using spring? if so.. Spring is doing that injection magic. This is not an issue. Please report with all the required data for us to be able to help you

**Comment by zhaogituser** [comment]
@Salaboy yes use spring

**Comment by Salaboy** [comment]
@zhaogituser ok, but we need more information and a reproducer of the problem,. Please create a simple maven project where you demonstrate how is this failing. We need to be able to run and see the issue in order to fix it. The amount of information provided here is not enough to understand what is going wrong.

**Comment by zhaogituser** [comment]
@Salaboy  


DeploymentQuery deploymentQuery=repositoryService.createDeploymentQuery().deploymentNameLike("%"+ search+"%");
            if( deploymentQuery !=null){
                total=deploymentQuery.count();
                rows=repositoryService.createDeploymentQuery()//创建流程查询实例
                        .orderByDeploymenTime().desc()  //降序
                        .deploymentNameLike("%"+search+"%")   //根据Name模糊查询
                        .listPage(offset/lmit, limit);
            }

This my code ."deploymentQuery.count();" be caused NullPointException.

**Comment by Salaboy** [comment]
@zhaogituser I cannot run that code, and I don't even know which version of activiti you are using.. please provide a maven project that we can run to help you.

**Comment by zhaogituser** [comment]
where i send my code ? email?

**Comment by zhaogituser** [comment]
@Salaboy   I used dubbo to provide activiti services  .    Is this  an  issue?

**Comment by zhaogituser** [comment]
@Salaboy I'm sorry. English is not my native language. Can you speak Chinese .

**Comment by zhaogituser** [comment]
I use activiti version 5.19.0.2 .Here's my activi.xml .


 
  <bean id="processEngineConfiguration" class="org.activiti.spring.SpringProcessEngineConfiguration">
    <property name="dataSource" ref="dataSource" />
    <property name="transactionManager" ref="transactionManager" />
    <property name="databaseSchemaUpdate" value="true" />
    <property name="jobExecutorActivate" value="false" />
  </bean>
  
  
  <bean id="processEngine" class="org.activiti.spring.ProcessEngineFactoryBean">
    <property name="processEngineConfiguration" ref="processEngineConfiguration" />
  </bean>
  
  
  <bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />
  <bean id="runtimeService" factory-bean="processEngine" factory-method="getRuntimeService" />
  <bean id="taskService" factory-bean="processEngine" factory-method="getTaskService" />
  <bean id="historyService" factory-bean="processEngine" factory-method="getHistoryService" />
  <bean id="managementService" factory-bean="processEngine" factory-method="getManagementService" />
  <bean id="identityService" factory-bean="processEngine" factory-method="getIdentityService"/>
  <bean id="formService" factory-bean="processEngine" factory-method="getFormService"></bean>

**Comment by zhaogituser** [comment]
<bean id="processEngineConfiguration" class="org.activiti.spring.SpringProcessEngineConfiguration">
    <property name="dataSource" ref="dataSource" />
    <property name="transactionManager" ref="transactionManager" />
    <property name="databaseSchemaUpdate" value="true" />
    <property name="jobExecutorActivate" value="false" />
  </bean>
  
  
  <bean id="processEngine" class="org.activiti.spring.ProcessEngineFactoryBean">
    <property name="processEngineConfiguration" ref="processEngineConfiguration" />
  </bean>
  
  
  <bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />
  <bean id="runtimeService" factory-bean="processEngine" factory-method="getRuntimeService" />
  <bean id="taskService" factory-bean="processEngine" factory-method="getTaskService" />
  <bean id="historyService" factory-bean="processEngine" factory-method="getHistoryService" />
  <bean id="managementService" factory-bean="processEngine" factory-method="getManagementService" />
  <bean id="identityService" factory-bean="processEngine" factory-method="getIdentityService"/>
  <bean id="formService" factory-bean="processEngine" factory-method="getFormService"></bean>

**Comment by Salaboy** [comment]
@zhaogituser no, just create a project in your github account so we can clone it and run it with maven.

**Comment by Salaboy** [comment]
@zhaogituser please upload your project to a github repo. We will not download a zip file

**Comment by balsarori** [comment]
@zhaogituser you have a custom ```org.mybatis.spring.SqlSessionFactoryBean``` with custom mappers. I guess this is whats causing the issue. This overrides the Activiti specific mybatis mappers. If you want your own mappers use the example here 
https://www.activiti.org/userguide/#_xml_based_mapped_statements
set your customMybatisMappers
```
<property name="customMybatisMappers">
        <set>
            <value>org.activiti.standalone.cfg.MyTestMapper</value>
        </set>
</property>
```

Or inside mybatis-config.xml you should point to all Activiti's mappers see
https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-engine/src/main/resources/org/activiti/db/mapping/mappings.xml

**Comment by zhaogituser** [comment]
OK

**Comment by zhaogituser** [comment]
thanks .I will try it first

**Comment by zhaogituser** [comment]
@balsarori  
I see  the 
 <property name="customMybatisMappers">
        <set>
            <value>org.activiti.standalone.cfg.MyTestMapper</value>
        </set>
</property>
config ,but I did't know  which file to put it under.

And please give me your advice.

**Comment by zhaogituser** [comment]
@balsarori thanks

**Comment by zhaogituser** [comment]
@Salaboy I think my problem should not be here . I don't have any mapping files, but called the count () method of the "repositoryservice" class of the activiti engine directly.    When I ran debug mode into the following method,the program prompts commandexecute to be empty and throws a NullPointerException.   
This is the method `.public long count() {
    this.resultType = ResultType.COUNT;
    if (commandExecutor!=null) {
      return (Long) commandExecutor.execute(this);
    }
    return executeCount(Context.getCommandContext());
  }`

 Because I used dubbo distribution, I put the corresponding activiti service in the dubbo-provider.xml file as well.

**Comment by zhaogituser** [comment]
@Salaboy I hope  I'm not bothering you?

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Please upload the full stacktrace of your NullpointException.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto wait on

**Comment by zhaogituser** [comment]
`com.alibaba.dubbo.common.bytecode.proxy1@759f72d32018-07-30 11:48:39,711 [qtp1194385648-18] ERROR [com.gw.oydCloud.common.base.BaseController] - 统一异常处理：
java.lang.NullPointerException
	at org.activiti.engine.impl.DeploymentQueryImpl.executeCount(DeploymentQueryImpl.java:157)
	at org.activiti.engine.impl.AbstractQuery.count(AbstractQuery.java:159)
	at com.gw.oydCloud.upms.server.controller.manage.UpmsDeployController.list(UpmsDeployController.java:54)
	at com.gw.oydCloud.upms.server.controller.manage.UpmsDeployController$$FastClassBySpringCGLIB$$6472e0db.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.gw.oydCloud.upms.client.interceptor.LogAspect.doAround(LogAspect.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor$1.proceed(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:82)
	at org.apache.shiro.authz.aop.AuthorizingMethodInterceptor.invoke(AuthorizingMethodInterceptor.java:39)
	at org.apache.shiro.spring.security.interceptor.AopAllianceAnnotationsAuthorizingMethodInterceptor.invoke(AopAllianceAnnotationsAuthorizingMethodInterceptor.java:115)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.gw.oydCloud.upms.server.controller.manage.UpmsDeployController$$EnhancerBySpringCGLIB$$8501a9b6.list(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
`

@daisuke-yoshimoto

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Thanks. I will check it and investigate that cause.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto Thank you. I'm waiting for the good news.    Let me explain that I used dubbo distributed.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto Are you still there?

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser 

I cannot find com.gw.oydCloud.upms.server.controller.manage.UpmsDeployController.list in https://github.com/Activiti/Activiti/files/2235203/Activiti-LFP.zip. So, I do not know the exact cause.

But, Perhaps it seems to be caused by commandContext being null, that is, executing DeploymentQuery directly from outside the command. So, please fix to use DeploymentQuery from RepositoryService.createDeploymentQuery().

```
java.lang.NullPointerException
	at org.activiti.engine.impl.DeploymentQueryImpl.executeCount(DeploymentQueryImpl.java:157)
	at org.activiti.engine.impl.AbstractQuery.count(AbstractQuery.java:159)
	at com.gw.oydCloud.upms.server.controller.manage.UpmsDeployController.list(UpmsDeployController.java:54)
	at com.gw.oydCloud.upms.server.controller.manage.UpmsDeployController$$FastClassBySpringCGLIB$$6472e0db.invoke(<generated>)
```

```
  @Override
  public long executeCount(CommandContext commandContext) {
    checkQueryOk();
    return commandContext
      .getDeploymentEntityManager()
      .findDeploymentCountByQueryCriteria(this);
  }
```

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto the project is demo ,not my real project .Now I'm uploading my project.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto First, introduce you to the two necessary startup modules "oydCloud-upms-rpc-service" and "oydCloud-upms-server"

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Where is your project?

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto The UpmsDeployController class of the com.gw.oydCloud.upms.server.controller.manage package .

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto  sorry my project is over 10 MB.Maybe I send you email if you like .

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Can you use google drive? If google drive, you can upload your project.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I'm sorry. I don't know what google driver is

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto The exception was occurred  in  the list method .

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Do you reproduce that exception using this file too?
[UpmsDeployController.java.txt](https://github.com/Activiti/Activiti/files/2240517/UpmsDeployController.java.txt)

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I can't understand this sentence

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Can you reproduce your exception yet using https://github.com/Activiti/Activiti/files/2240517/UpmsDeployController.java.txt ?

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto this class caused exception

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto IIs my understanding right?

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser OK. My fix cannot resolve your exception.
I will continue to investigate.

Can I reproduce your exception using your old project https://github.com/Activiti/Activiti/files/2235203/Activiti-LFP.zip?

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I ‘m trying to understand your original intention.please give me some times

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto NO this exception in my real project . not my demo

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I will try to upload the source code to GIThub ,and i will tell you

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Ohh,if so, it is hard to investigate about your project without your real project.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto Maybe you can give some advice to run my code

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Can you use https://www.dropbox.com/h or https://drive.google.com/drive/my-drive for uploading your real project? If not so, please divide it into multiple files and upload them.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I just had a google driver account. I will upload my source code to google driver, tomorrow morning. Would you like to share the link with me or if you give me the gmail email address? 


Thank you again for your help.

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Good. If you can use google drive, you can upload your project and share its url to me in this thread.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto How to share it safely with you?

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto    you can upload  what does  the "in this thread " word  mean  .

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Ohh, do you mean that you want to share your real project to only me?

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto Yeah, that's it. Just look.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I don't have a twitter account. Do you have a google driver login?   When I click share again, let me enter the email or name of the person to whom I shared

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Ok. Please chat with me in https://gitter.im/ https://gitter.im/Activiti/Activiti7. Since you have github account, so you can use gitter.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I just sent you a private chat

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser Thanks. I will start check your project and reproduce your exception.

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto I uploaded  the project that  was  packaged  in zip

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser 

Sorry I made you wait. After all, I could not confirm the reproducibility in your project, but I understood what seemed to be the cause. When checking applicationContext-dubbo-provider.xml, RepositoryService's bean was not retrieved from processEngine. RepositoryService's bean was directly created from new RuntimeServiceImpl(). So, if you use RepositoryService's bean, its bean cannot access processEngine and cannot get commandExecutor.

Please check examples for spring bean setting. https://github.com/Activiti/Activiti/blob/5.19.0.2/modules/activiti-spring/src/test/resources/activiti-context.xml#L45

### applicationContext-dubbo-provider.xml

```
<!--activity-->
<bean id="runtimeService" class="org.activiti.engine.impl.RuntimeServiceImpl"/>
<dubbo:service interface="org.activiti.engine.RuntimeService" ref="runtimeService" timeout="10000"/>

<bean id="repositoryService" class="org.activiti.engine.impl.RepositoryServiceImpl"/>
<dubbo:service interface="org.activiti.engine.RepositoryService" ref="repositoryService" timeout="10000"/>

<bean id="taskService" class="org.activiti.engine.impl.TaskServiceImpl"/>
<dubbo:service interface="org.activiti.engine.TaskService" ref="taskService" timeout="10000"/>

<bean id="historyService" class="org.activiti.engine.impl.HistoryServiceImpl"/>
<dubbo:service interface="org.activiti.engine.HistoryService" ref="historyService" timeout="10000"/>

<bean id="managementService" class="org.activiti.engine.impl.ManagementServiceImpl"/>
<dubbo:service interface="org.activiti.engine.ManagementService"  ref="managementService" timeout="10000"/>

<bean id="identityService" class="org.activiti.engine.impl.IdentityServiceImpl"/>
<dubbo:service interface="org.activiti.engine.IdentityService" ref="identityService" timeout="10000"/>

<bean id="formService"  class="org.activiti.engine.impl.FormServiceImpl"/>
<dubbo:service interface="org.activiti.engine.FormService" ref="formService" timeout="100000"/>

```

**Comment by zhaogituser** [comment]
I see. As you said "RepositoryService's bean was not retrieved from processEngine." .Based on this tip, I created an intermediate class to inject activiti's services into the dubbo registry .`import org.activiti.engine.RepositoryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;


@Service
@Transactional
public class OydRepositoryService {
	
	@Autowired
	public RepositoryService repositoryService;

}`

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto But,I can't understand .why not use the repositoryService  (`
  <bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />") "` of in activiti-context.xml to inject activiti’s service directly

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto    activiti-context.xml .`
  <bean id="processEngine" class="org.activiti.spring.ProcessEngineFactoryBean">
    <property name="processEngineConfiguration" ref="processEngineConfiguration" />
  </bean>
    <bean id="repositoryService" factory-bean="processEngine" factory-method="getRepositoryService" />`  

dubbo-provider.xml

`
	<dubbo:service interface="org.activiti.engine.RepositoryService"	ref="repositoryService" />` 
Please pay attention to the thickening part . **org.activiti.engine.RepositoryService** is not my declare but is activiti's.

Can you understand what  I explain ?

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto Your explanation is good. Although my problem has been solved, I would prefer to know the answer to the question I asked you last time .You are a great software engineer.

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser 

Sorry I made you wait. I have been busy with my full time job for a while.

`<dubbo:service interface="org.activiti.engine.RuntimeService" ref="runtimeService" timeout="10000"/>
`

This mean that Spring framework uses runtimeService as the implementation of the interface org.activiti.engine.RuntimeService.

`<bean id="runtimeService" class="org.activiti.engine.impl.RuntimeServiceImpl"/>
`

And, runtimeService mean `new org.activiti.engine.impl.RuntimeServiceImpl()`;

So, dubbo use `new org.activiti.engine.impl.RuntimeServiceImpl()` as the implementation of the interface org.activiti.engine.RuntimeService.

**Comment by daisuke-yoshimoto** [comment]
@zhaogituser 
Also, if you want to use activiti-context.xml, you should set so that dubbo-provider.xml refer activiti-context.xml. For example, the following.

`<import resource="classpath:activiti-context.xml"/>`

**Comment by zhaogituser** [comment]
@daisuke-yoshimoto Sorry,I took up your precious time.I did it before ,but the  Spring framewrok didn't get the implemention of the interface org.activiti.engine.RuntimeService.  Now ,I do it again.

**Comment by salaboy** [comment]
@zhaogituser @daisuke-yoshimoto @balsarori amazing community contributions/interactions. Is this issue solved? did you guys found the cause of the problem? For what I can see in the comments it was more about how the engine was being used in a distributed setup with Spring than a real issue. 
Are you ok with closing this issue?

**Comment by gebilaoman** [comment]
Is the problem finally solved?
