### ISSUE TITLE
Deadlock on table ACT_RU_EXECUTION, activiti 7-201802-EA

### ISSUE THREAD

**Issue by jtama-op** [Activiti/Activiti#1977]
Hi,
We are currently using Activiti 7-201802-EA, activiti-spring and database Oracle 11. 
We regularly encounter deadlocks with the following message : 
```
Error while closing command context
 org.apache.ibatis.exceptions.PersistenceException:
 ### Error updating database.  Cause: java.sql.SQLException: ORA-00060: deadlock detected while waiting for resource
 ### The error may involve org.activiti.engine.impl.persistence.entity.ExecutionEntityImpl.deleteExecution-Inline
 ### The error occurred while setting parameters
 ### SQL: delete from ACT_RU_EXECUTION where ID_ = ? and REV_ = ?
 ### Cause: java.sql.SQLException: ORA-00060: deadlock detected while waiting for resource
 at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:213)
 at org.activiti.engine.impl.db.DbSqlSession.flushDeleteEntities(DbSqlSession.java:911)
 at org.activiti.engine.impl.db.DbSqlSession.flushDeletes(DbSqlSession.java:871)
 at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:525)
 at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:237)
 at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:102)
 at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
 at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
 at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
 at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
 at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
 at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
 at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
 at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:97)
 at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:75)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:844)
 Caused by: java.sql.SQLException: ORA-00060: deadlock detected while waiting for resource
 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
 at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
 at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
 at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
 at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
 at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
 at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
 at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
 at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
 at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
 at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
 at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:4901)
 at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1385)
 at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
 at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
 at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
 at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
 at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
 at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
 at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
 at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
 ... 18 common frames omitted
```
The following issue #741 seems to relate to the same bug.

We use the following configuration : 
```java
conf.setDataSource(transactionManager.getDataSource())
                .setAsyncExecutorActivate(true)
                .setDatabaseSchemaUpdate("true")

conf.setAsyncExecutorCorePoolSize(10);
conf.setAsyncExecutorMaxPoolSize(20);
conf.setAsyncExecutorAsyncJobLockTimeInMillis(30 * 60 * 1000);
```

The process is the following : 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:tns="http://www.activiti.org/processdef" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/processdef" id="Definitions_0agncek" name="" exporterVersion="1.16.0">
  <process id="my_process" isExecutable="true">
    <scriptTask id="Task_1cjc80v" name="Process Script" scriptFormat="groovy" activiti:autoStoreVariables="false">
      <script>
        //...
      </script>
    </scriptTask>
    <endEvent id="EndEvent_09di1k5"></endEvent>
    <sequenceFlow id="SequenceFlow_0m8k0x3" sourceRef="Task_1cjc80v" targetRef="EndEvent_09di1k5"></sequenceFlow>
    <scriptTask id="scripttask1" name="Set parameter script 1" scriptFormat="groovy" activiti:autoStoreVariables="false">
      <script>
        //...
      </script>
    </scriptTask>
    <scriptTask id="scripttask2" name="Set parameter script 2" scriptFormat="groovy" activiti:autoStoreVariables="false">
      <script>
        //...
      </script>
    </scriptTask>
    <scriptTask id="scripttask3" name="Set parameter script 3" scriptFormat="groovy" activiti:autoStoreVariables="false">
      <script>
        //...
      </script>
    </scriptTask>
    <startEvent id="timerstartevent1" name="Timer start 1">
      <timerEventDefinition>
        <timeCycle>0 0/2 * ? * * *</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <sequenceFlow id="flow2" sourceRef="timerstartevent1" targetRef="scripttask1"></sequenceFlow>
    <startEvent id="timerstartevent2" name="Timer start BIOSFADETPDF">
      <timerEventDefinition>
        <timeCycle>0 0/2 * ? * * *</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <startEvent id="timerstartevent3" name="Timer start BIOSFADETXML">
      <timerEventDefinition>
        <timeCycle>0 0/2 * ? * * *</timeCycle>
      </timerEventDefinition>
    </startEvent>
    <sequenceFlow id="flow3" sourceRef="timerstartevent2" targetRef="scripttask2"></sequenceFlow>
    <sequenceFlow id="flow4" sourceRef="timerstartevent3" targetRef="scripttask3"></sequenceFlow>
    <sequenceFlow id="flow5" sourceRef="scripttask1" targetRef="Task_1cjc80v"></sequenceFlow>
    <sequenceFlow id="flow6" sourceRef="scripttask2" targetRef="Task_1cjc80v"></sequenceFlow>
    <sequenceFlow id="flow7" sourceRef="scripttask3" targetRef="Task_1cjc80v"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram">
    <bpmndi:BPMNPlane bpmnElement="my_process" id="BPMNPlane_my_process">
      <bpmndi:BPMNShape bpmnElement="Task_1cjc80v" id="BPMNShape_Task_1cjc80v">
        <omgdc:Bounds height="80.0" width="100.0" x="563.0" y="280.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="EndEvent_09di1k5" id="BPMNShape_EndEvent_09di1k5">
        <omgdc:Bounds height="36.0" width="36.0" x="596.0" y="410.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="scripttask1" id="BPMNShape_scripttask1">
        <omgdc:Bounds height="61.0" width="105.0" x="430.0" y="150.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="scripttask2" id="BPMNShape_scripttask2">
        <omgdc:Bounds height="61.0" width="105.0" x="560.0" y="150.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="scripttask3" id="BPMNShape_scripttask3">
        <omgdc:Bounds height="61.0" width="105.0" x="690.0" y="150.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="timerstartevent1" id="BPMNShape_timerstartevent1">
        <omgdc:Bounds height="35.0" width="35.0" x="465.0" y="40.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="timerstartevent2" id="BPMNShape_timerstartevent2">
        <omgdc:Bounds height="35.0" width="35.0" x="595.0" y="40.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="timerstartevent3" id="BPMNShape_timerstartevent3">
        <omgdc:Bounds height="35.0" width="35.0" x="725.0" y="40.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="SequenceFlow_0m8k0x3" id="BPMNEdge_SequenceFlow_0m8k0x3">
        <omgdi:waypoint x="613.0" y="360.0"></omgdi:waypoint>
        <omgdi:waypoint x="614.0" y="410.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow2" id="BPMNEdge_flow2">
        <omgdi:waypoint x="482.0" y="75.0"></omgdi:waypoint>
        <omgdi:waypoint x="482.0" y="150.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow3" id="BPMNEdge_flow3">
        <omgdi:waypoint x="612.0" y="75.0"></omgdi:waypoint>
        <omgdi:waypoint x="612.0" y="150.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow4" id="BPMNEdge_flow4">
        <omgdi:waypoint x="742.0" y="75.0"></omgdi:waypoint>
        <omgdi:waypoint x="742.0" y="150.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow5" id="BPMNEdge_flow5">
        <omgdi:waypoint x="482.0" y="211.0"></omgdi:waypoint>
        <omgdi:waypoint x="613.0" y="280.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow6" id="BPMNEdge_flow6">
        <omgdi:waypoint x="612.0" y="211.0"></omgdi:waypoint>
        <omgdi:waypoint x="613.0" y="280.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="flow7" id="BPMNEdge_flow7">
        <omgdi:waypoint x="742.0" y="211.0"></omgdi:waypoint>
        <omgdi:waypoint x="613.0" y="280.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
```
This error has been triggered more than 500 times in a 15 hours window.

How can we prevent this? Does this prevent our process to run normally, or are those errors automatically taken into account on a later cleaning process, and should thus be ignored?

**Comment by jtama-op** [comment]
Hi any update on this issue

**Comment by jtama-op** [comment]
We found the root cause.

In activiti oracle DDL there are at least 3 foreign keys that are not covered by indexes. 
When deleting rows, oracle check data consistency. If no indexes exists oracle will lock the table even if the table lock mode is row lock.

We created missing indexes : 

```sql
create index ACT_ID_EXEC_ID on ACT_RU_INTEGRATION(EXECUTION_ID_);
create index ACT_ID_PROC_ID on ACT_RU_INTEGRATION(PROCESS_INSTANCE_ID_);
create index ACT_ID_PROC_DEF on ACT_RU_INTEGRATION(PROC_DEF_ID_);
```

Deadlock doesn't occure anymore.

**Comment by Salaboy** [comment]
@jtama-op ok.. now I have more context to it.. and thanks a lot for you PR. Can you try beta1? We will do our best to include your fix for Beta2. It will be great if you join our gitter channel to have more conversations about your experiments: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by Salaboy** [comment]
@damienb-opt that make sense to me, but it is oracle specific that is why we need to make sure that we keep some alignment with other DBs.
