### ISSUE TITLE
Query fails to handle events when task is assigned via `activiti:assignee`

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2129]
When task is assigned via `activiti:assignee` an exception occurs because due the the internal mechanism the event `TASK_UPDATED` is triggered before the event `TASK_CREATED`.

_Steps to reproduce_
- create a process with `activiti:assignee` set with some value: `<bpmn2:userTask id="Task_03l0zc2" name="my-task" activiti:assignee="testuser">`
- Start an instance of this process and check logs for the query service.

_Strak trace_
```
2018-11-07 12:14:37.406  WARN [query,,,] 1 --- [eEvents.query-1] o.s.a.r.r.RejectAndDontRequeueRecoverer  : Retries exhausted for message (Body:'[{"eventType":"PROCESS_CREATED","id":"9036ad70-9321-46d6-ade5-479a8a29e0ef","timestamp":1541592874205,"entity":{"id":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processDefinitionKey":"SingleTaskProcess","initiator":"testuser","startDate":"2018-11-07T12:14:34.205+0000","businessKey":"MyBusinessKeyd","status":"RUNNING"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00eb915-e286-11e8-8395-0a580a1800e6","eventType":"PROCESS_CREATED"},{"eventType":"VARIABLE_CREATED","id":"0dd1f2ed-850e-4adc-befa-397d09482b15","timestamp":1541592874205,"entity":{"name":"firstName","type":"string","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","value":"TestName","taskVariable":false},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"firstName","eventType":"VARIABLE_CREATED"},{"eventType":"VARIABLE_CREATED","id":"7ec177cb-1463-4fcd-8bde-3372fe405972","timestamp":1541592874205,"entity":{"name":"lastName","type":"string","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","value":"TestLast","taskVariable":false},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"lastName","eventType":"VARIABLE_CREATED"},{"eventType":"VARIABLE_CREATED","id":"5ab3561c-3845-44b1-a9d0-7630b45204f0","timestamp":1541592874206,"entity":{"name":"aget","type":"integer","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","value":25,"taskVariable":false},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"aget","eventType":"VARIABLE_CREATED"},{"eventType":"PROCESS_STARTED","id":"965672e7-7cc8-4a8e-9767-ca226c13880c","timestamp":1541592874206,"entity":{"id":"b00eb915-e286-11e8-8395-0a580a1800e6","name":"My Awesome Name d","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processDefinitionKey":"SingleTaskProcess","initiator":"testuser","startDate":"2018-11-07T12:14:34.205+0000","businessKey":"MyBusinessKeyd","status":"RUNNING"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00eb915-e286-11e8-8395-0a580a1800e6","eventType":"PROCESS_STARTED"},{"eventType":"ACTIVITY_STARTED","id":"3195bc2f-cf0b-4bca-84e8-d706dd3f2728","timestamp":1541592874206,"entity":{"processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","activityType":"startEvent","elementId":"StartEvent_1"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","eventType":"ACTIVITY_STARTED"},{"eventType":"ACTIVITY_COMPLETED","id":"89fb7c5b-250c-4314-89df-5a93e0eb98ef","timestamp":1541592874206,"entity":{"processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","activityType":"startEvent","elementId":"StartEvent_1"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","eventType":"ACTIVITY_COMPLETED"},{"eventType":"SEQUENCE_FLOW_TAKEN","id":"b1010ed9-1e70-465b-abb7-9cb21b6818e6","timestamp":1541592874206,"entity":{"processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","sourceActivityElementId":"StartEvent_1","sourceActivityType":"org.activiti.bpmn.model.StartEvent","targetActivityElementId":"Task_03l0zc2","targetActivityName":"my-task","targetActivityType":"org.activiti.bpmn.model.UserTask"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00eb915-e286-11e8-8395-0a580a1800e6","eventType":"SEQUENCE_FLOW_TAKEN"},{"eventType":"ACTIVITY_STARTED","id":"03d74527-c324-4bc2-b54e-df5d3e38aec2","timestamp":1541592874206,"entity":{"processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","activityName":"my-task","activityType":"userTask","elementId":"Task_03l0zc2"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00eb915-e286-11e8-8395-0a580a1800e6","processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","eventType":"ACTIVITY_STARTED"},{"eventType":"TASK_UPDATED","id":"ec671a69-dc72-41a2-9745-ea1a3724ed24","timestamp":1541592874207,"entity":{"id":"b00f073b-e286-11e8-8395-0a580a1800e6","name":"my-task","status":"ASSIGNED","assignee":"testuser","createdDate":"2018-11-07T12:14:34.207+0000","priority":50,"processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","formKey":"taskForm"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00f073b-e286-11e8-8395-0a580a1800e6","eventType":"TASK_UPDATED"},{"eventType":"TASK_CREATED","id":"6ce18a45-06f9-4160-99e6-cb758b99ba25","timestamp":1541592874208,"entity":{"id":"b00f073b-e286-11e8-8395-0a580a1800e6","name":"my-task","status":"ASSIGNED","assignee":"testuser","createdDate":"2018-11-07T12:14:34.207+0000","priority":50,"processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","formKey":"taskForm"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00f073b-e286-11e8-8395-0a580a1800e6","eventType":"TASK_CREATED"},{"eventType":"TASK_ASSIGNED","id":"553154b3-67ce-41ff-b922-8c71c3555700","timestamp":1541592874208,"entity":{"id":"b00f073b-e286-11e8-8395-0a580a1800e6","name":"my-task","status":"ASSIGNED","assignee":"testuser","createdDate":"2018-11-07T12:14:34.207+0000","priority":50,"processDefinitionId":"SingleTaskProcess:1:e6dcf243-e284-11e8-8395-0a580a1800e6","processInstanceId":"b00eb915-e286-11e8-8395-0a580a1800e6","formKey":"taskForm"},"appName":"default-app","serviceFullName":"rb-my-app","appVersion":"","serviceName":"rb-my-app","serviceVersion":"","serviceType":"runtime-bundle","entityId":"b00f073b-e286-11e8-8395-0a580a1800e6","eventType":"TASK_ASSIGNED"}]' MessageProperties [headers={spanTraceId=517dea382d427e1c, spanId=5078513f0c262429, spanParentSpanId=517dea382d427e1c, nativeHeaders={spanTraceId=[517dea382d427e1c], spanId=[eb2c63d14f24c13a], spanParentSpanId=[d81704e113270524], X-B3-SpanId=[eb2c63d14f24c13a], X-B3-ParentSpanId=[d81704e113270524], X-B3-Sampled=[1], X-B3-TraceId=[517dea382d427e1c], spanSampled=[1]}, X-B3-SpanId=5078513f0c262429, X-B3-ParentSpanId=517dea382d427e1c, X-B3-Sampled=1, X-B3-TraceId=517dea382d427e1c, spanSampled=1, contentType=application/json}, contentType=application/json, contentLength=0, receivedDeliveryMode=PERSISTENT, priority=0, redelivered=false, receivedExchange=engineEvents, receivedRoutingKey=engineEvents, deliveryTag=59, consumerTag=amq.ctag-hvYvMcu_QO9c6njxOMKEhQ, consumerQueue=engineEvents.query])

org.springframework.messaging.MessagingException: Exception thrown while invoking org.activiti.cloud.services.query.app.QueryConsumerChannelHandler#receive[1 args]; nested exception is org.activiti.cloud.services.query.model.QueryException: Unable to find task with id: b00f073b-e286-11e8-8395-0a580a1800e6
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:63)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1100(AmqpInboundChannelAdapter.java:60)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:214)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:211)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1414)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1337)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324)
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:817)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:801)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1042)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.activiti.cloud.services.query.model.QueryException: Unable to find task with id: b00f073b-e286-11e8-8395-0a580a1800e6
	at org.activiti.cloud.services.query.events.handlers.TaskUpdatedEventHandler.lambda$handle$0(TaskUpdatedEventHandler.java:48)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.activiti.cloud.services.query.events.handlers.TaskUpdatedEventHandler.handle(TaskUpdatedEventHandler.java:47)
	at org.activiti.cloud.services.query.events.handlers.QueryEventHandlerContext.handle(QueryEventHandlerContext.java:49)
	at org.activiti.cloud.services.query.app.QueryConsumerChannelHandler.receive(QueryConsumerChannelHandler.java:39)
	at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
```

**Comment by erdemedeiros** [comment]
Possible solution: use TASK_UPDATE event to create a task if it does not exist, then ignore the related create event.

**Comment by erdemedeiros** [comment]
Eventually the solution was: 
Instead of listening to the generic internal ENTITY_UPDATED event we are going to explicitly trigger `TASK_UPDATED` event when `TaskRuntime.update` is called. That means that no event is going to be triggered if the task is updated outside of the api (directly from TaskService for instance)
