### ISSUE TITLE
spring @Transactional is not work when throw the ActivitiException

### ISSUE THREAD

**Issue by Shaun-Yao** [Activiti/Activiti#2158]
```
 @Transactional(rollbackFor = Exception.class)
    public void apply(Repair repair) {
        repairRepository.save(repair);
        Map<String, Object> variables = new HashMap();
        //variables.put("repairer", "123");
        runtimeService.startProcessInstanceByKey("test", "abc", variables);
     
    }
```

If no variable is set，it will throw ActivitiException: Unknown property used in expression: ${repairer}.
throw exception is correct, but the transaction has not rolled back,  repairRepository save successfully.

**Comment by salaboy** [comment]
@Shaun-Yao can you please share which version if Activiti are you using? Also, are you @Autowiring the RuntimeService? Which version of Spring / Spring Boot are you using?

**Comment by Shaun-Yao** [comment]
@salaboy I am using spring boot v2.0.6, activiti v6.0.0, i have autowired runtimeService.
```
@Autowired
 private RuntimeService runtimeService;
```

**Comment by salaboy** [comment]
@Shaun-Yao we are discussing to fix this in 7 by default due the Spring Integration is getting better and better with the new Runtime APIs. In Activiti 6 I think that you need to wire the transactions handled by the engine with the Spring transaction as mentioned in the documentation: https://www.activiti.org/userguide/#_transactions

**Comment by salaboy** [comment]
I will close this issue now, but if you still find problems after following the docs let us know

**Comment by Shaun-Yao** [comment]
@salaboy Thanks, i got it.

**Comment by Shaun-Yao** [comment]
@salaboy I have tried to init the SpringProcessEngineConfiguration bean, But there are some problems here.
Caused by: java.lang.IllegalStateException: No 'targetDataSource' set
	at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.jdbc.datasource.DelegatingDataSource.obtainTargetDataSource(DelegatingDataSource.java:84) ~[spring-jdbc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy.getConnection(TransactionAwareDataSourceProxy.java:121) ~[spring-jdbc-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.initDatabaseType(ProcessEngineConfigurationImpl.java:957) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.initDataSource(ProcessEngineConfigurationImpl.java:907) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.init(ProcessEngineConfigurationImpl.java:689) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:664) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:65) ~[activiti-spring-6.0.0.jar:6.0.0]
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:57) ~[activiti-spring-6.0.0.jar:6.0.0]
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32) ~[activiti-spring-6.0.0.jar:6.0.0]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	... 74 common frames omitted
```

@SpringBootApplication(exclude = SecurityAutoConfiguration.class)
public class OaApplication  {

  
    @Autowired
    private PlatformTransactionManager transactionManager;

    @Autowired
    private HikariDataSource dataSource;

    public static void main(String[] args) {
        SpringApplication.run(OaApplication.class, args);
    }

    @Bean
    public SpringProcessEngineConfiguration processEngineConfiguration() {
        SpringProcessEngineConfiguration config = new SpringProcessEngineConfiguration();
        config.setDataSource(dataSource);
        config.setTransactionManager(transactionManager);
        config.setDatabaseSchemaUpdate("true");
        config.setAsyncExecutorActivate(false);
        return config;
    }

    @Bean
    public ProcessEngineFactoryBean processEngine() {
        ProcessEngineFactoryBean factoryBean = new ProcessEngineFactoryBean();
        factoryBean.setProcessEngineConfiguration(processEngineConfiguration());
        return factoryBean;
    }
}

```

**Comment by salaboy** [comment]
@Shaun-Yao what is the value of: 
```
@Autowired
    private HikariDataSource dataSource;
```
is that different from null?

**Comment by Shaun-Yao** [comment]
@salaboy Any suggestions?
