### ISSUE TITLE
Process status is not updated to COMPLETED in Cloud Query database

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2163]
when the process instance is completed in Runtime Bundle app. 

Activiti Cloud Version: 7.0.0.Beta3

The log is attached

```
  2018-11-15 03:58:35.545 ERROR [query,c5d02f952b5d6c9d,308a8588899bca67,true] 1 --- [Events.query-13] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: Exception thrown while invoking org.activiti.cloud.services.query.app.QueryConsumerChannelHandler#receive[1 args]; nested exception is org.springframework.dao.IncorrectResultSizeDataAccessException: Only one result is allowed for fetchOne calls; nested exception is com.querydsl.core.NonUniqueResultException: Only one result is allowed for fetchOne calls, failedMessage=GenericMessage [payload=byte[8545], headers={amqp_receivedDeliveryMode=PERSISTENT, amqp_receivedExchange=engineEvents, amqp_deliveryTag=606, deliveryAttempt=3, X-B3-ParentSpanId=2e025ec4ab280dc9, amqp_consumerQueue=engineEvents.query, amqp_redelivered=false, spanTraceId=c5d02f952b5d6c9d, spanId=362acc29dc5b0c81, spanParentSpanId=2e025ec4ab280dc9, amqp_receivedRoutingKey=engineEvents, nativeHeaders={spanTraceId=[c5d02f952b5d6c9d], spanId=[308a8588899bca67], spanParentSpanId=[362acc29dc5b0c81], X-B3-SpanId=[308a8588899bca67], X-B3-ParentSpanId=[362acc29dc5b0c81], X-B3-Sampled=[1], X-B3-TraceId=[c5d02f952b5d6c9d], spanSampled=[1]}, X-B3-SpanId=362acc29dc5b0c81, X-B3-Sampled=1, X-B3-TraceId=c5d02f952b5d6c9d, id=7a4b7d14-1cf9-73be-ebcc-85e3c72a5468, spanSampled=1, amqp_consumerTag=amq.ctag-Uu9fzeT8xh1Uifz3WoKa5g, contentType=application/json, timestamp=1542254315538}]
        at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:63)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:109)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:158)
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
        at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445)
        at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:181)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:160)
        at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
        at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
        at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203)
        at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1100(AmqpInboundChannelAdapter.java:60)
        at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:214)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
        at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:211)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1414)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1337)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1324)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1303)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:817)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:801)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$700(SimpleMessageListenerContainer.java:77)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1042)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.dao.IncorrectResultSizeDataAccessException: Only one result is allowed for fetchOne calls; nested exception is com.querydsl.core.NonUniqueResultException: Only one result is allowed for fetchOne calls
        at org.springframework.data.jpa.repository.support.QuerydslJpaRepository.findOne(QuerydslJpaRepository.java:106)
        at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:377)
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:200)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:629)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:593)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy188.findOne(Unknown Source)
        at org.activiti.cloud.services.query.app.repository.EntityFinder.findOne(EntityFinder.java:45)
        at org.activiti.cloud.services.query.events.handlers.VariableUpdater.update(VariableUpdater.java:41)
        at org.activiti.cloud.services.query.events.handlers.ProcessVariableUpdateEventHandler.handle(ProcessVariableUpdateEventHandler.java:42)
        at org.activiti.cloud.services.query.events.handlers.VariableUpdatedEventHandler.handle(VariableUpdatedEventHandler.java:62)
        at org.activiti.cloud.services.query.events.handlers.QueryEventHandlerContext.handle(QueryEventHandlerContext.java:49)
        at org.activiti.cloud.services.query.app.QueryConsumerChannelHandler.receive(QueryConsumerChannelHandler.java:39)
        at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:181)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:114)
        at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
        ... 27 more
Caused by: com.querydsl.core.NonUniqueResultException: Only one result is allowed for fetchOne calls
        at com.querydsl.jpa.impl.AbstractJPAQuery.fetchOne(AbstractJPAQuery.java:258)
        at org.springframework.data.jpa.repository.support.QuerydslJpaRepository.findOne(QuerydslJpaRepository.java:104)
        ... 64 more


```

**Comment by salaboy** [comment]
@igdianov :+1 I am assigning @CTI777 as candidate, I think that this is a very well scoped task to solve.
