### ISSUE TITLE
how to integrate activiti6.0.x with springboot2.0.x,for me boot version is 2.0.6

### ISSUE THREAD

**Issue by leiyazhen** [Activiti/Activiti#2314]
when i start boot i got this below:
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/security/config/annotation/authentication/configurers/GlobalAuthenticationConfigurerAdapter.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:51)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:88)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:75)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:732)
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:948)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:333)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:362)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:265)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:636)
	... 17 common frames omitted

boot start class is like this:
@SpringBootApplication(exclude = { org.activiti.spring.boot.SecurityAutoConfiguration.class })
@EnableNetplanSwagger2
@EnableDiscoveryClient
@EnableCircuitBreaker
@EnableNetplanFeignClients
@Slf4j
public class NetplanActivitiApplication {

	public static void main(String[] args) {
		SpringApplication.run(NetplanActivitiApplication.class, args);
	}
}
so,how to resolve this,anyone could help.

**Comment by salaboy** [comment]
@leiyazhen I suggest you to use the forums or stackoverflow for questions. Regarding Spring Boot 2.x, we are aiming Activiti 7 / Activiti Cloud to work with Spring Boot 2.x and Activiti 6.x was supposed to work with Spring Boot 1.5.x. We are not planning to work on Activiti 6.x compatibility with Spring Boot 2.x, but I know that there are some community users that manage to configure it correctly.
