### ISSUE TITLE
PersistenceException occurred when delete a processInstance

### ISSUE THREAD

**Issue by DestinyWang** [Activiti/Activiti#2349]
activiti version is `6.0.0`

java code is

`runtimeService.deleteProcessInstance(String processInstanceId, String deleteReason)`

Sometimes the following error will occur, and sometimes it will be normal.

I want to know what happened?

Exception in thread "pool-10-thread-4" org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`test`.`ACT_RU_VARIABLE`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`))
    at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:213)
    at org.activiti.engine.impl.db.DbSqlSession.flushDeleteEntities(DbSqlSession.java:770)
    at org.activiti.engine.impl.db.DbSqlSession.flushDeletes(DbSqlSession.java:733)
    at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:419)
    at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:197)
    at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:75)
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
    at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:35)
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
    at org.activiti.engine.impl.RuntimeServiceImpl.deleteProcessInstance(RuntimeServiceImpl.java:130)

**Comment by salaboy** [comment]
@DestinyWang this sounds like you have multiple threads trying to delete the same process instance. It should be harmless if the process instance get deleted by another thread.
