### ISSUE TITLE
intermittent failures in pod exec operations in jenkins-x pipelines

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2582]
Have raised 
jenkins-x/jx#2861

This seems especially likely to happen when multiple builds happen in parallel. Earlier I saw:

![image](https://user-images.githubusercontent.com/22754674/53559647-78147e00-3b42-11e9-9a9e-fd4bfcf1a4d1.png)

They were all failures with the same error message:

java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@5a85ec0b rejected from java.util.concurrent.ThreadPoolExecutor@2e54f447[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 20]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:130)
	at okhttp3.RealCall.enqueue(RealCall.java:100)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:183)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:436)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.exec(PodOperationsImpl.java:267)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.exec(PodOperationsImpl.java:61)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.doLaunch(ContainerExecDecorator.java:318)
	at org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator$1.launch(ContainerExecDecorator.java:236)
	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:188)

http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-query/job/PR-154/1/console
http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-audit/job/PR-154/1/console
http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-notifications-graphql/job/PR-42/1/console

In each case the **travis builds all passed without problems**.

It could be related to resource usage in the cluster. Will have to try to get there quick enough to see resource usage at the time when it happens.

**Comment by ryandawsonuk** [comment]
It seems to always work on a re-trigger, presumably because then only one pipeline is running. It seems to especially affect the cloud cluster, which does run the most parallel pipelines. So I had a look at the build pod resources and noted they are now up to:

![image](https://user-images.githubusercontent.com/22754674/53580166-effa9c80-3b72-11e9-899f-f35ee8d58e1c.png)

Whereas the defaults are:

![image](https://user-images.githubusercontent.com/22754674/53580321-3ea83680-3b73-11e9-8dd7-086286882ba5.png)

**Comment by ryandawsonuk** [comment]
I am reducing the requests back down to the defaults and leave the limits as they are. We can keep an eye on this to see if that resolves it.

**Comment by ryandawsonuk** [comment]
A new instance of this is http://jenkins.jx.35.242.205.159.nip.io/job/Activiti/job/activiti-cloud-notifications-service-graphql/job/develop/23/console

**Comment by ryandawsonuk** [comment]
Am seeing that during the peak there can be about 7 maven build pods running and each uses about 600mCPU and 900Mi. This leaves the cluster able to meet the requests but the pods are actually exceeding the requests and the cluster is not able to meet the limit numbers.

In the process I did notice https://github.com/jenkins-x/jx/issues/3267

**Comment by ryandawsonuk** [comment]
I don't think this is exclusively about resource availability as it is sometimes seen in other clusters. But it looks like an aggravating factor as it is most common in the cloud cluster.

**Comment by ryandawsonuk** [comment]
Just seen another whole set of these failures at about the same time:

http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-query/job/PR-164/1/console
http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-notifications-graphql/view/change-requests/job/PR-50/3/console
http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/example-cloud-connector/job/PR-139/1/console
http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/example-runtime-bundle/view/change-requests/job/PR-178/1/console
http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/activiti-cloud-audit/job/PR-163/1/console

So all coming from one build of activiti-cloud-dependencies:

![image](https://user-images.githubusercontent.com/22754674/53810730-7c300980-3f4f-11e9-972e-7106d8ec68fb.png)


It actually seems like it may have gotten worse, despite adding an extra node to the cluster

**Comment by ryandawsonuk** [comment]
Now changed the examples cluster maven builder pod resources to match the cloud one:

![image](https://user-images.githubusercontent.com/22754674/53813151-e303f180-3f54-11e9-96b2-2aabf12815bd.png)

**Comment by ryandawsonuk** [comment]
I did a `kubectl describe` on one of these pods named `maven-dind`. The reason the request and limits are so high is that the pod contains the maven-java11 container as well as the dind container and the resources are the totals for both added together. Note that the dind resources are therefore allocated even if no docker image is built (as is the case with a PR).

**Comment by ryandawsonuk** [comment]
Made the change to reduce requests on example runtime bundle and it built ok - http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/example-runtime-bundle/job/master/160/console so merging for the others too

**Comment by ryandawsonuk** [comment]
Examples cluster is looking better so far.

Saw an interesting example of this in the cloud cluster. Error is

```
java.util.concurrent.RejectedExecutionException: Task okhttp3.RealCall$AsyncCall@5ba63f67 rejected from java.util.concurrent.ThreadPoolExecutor@3c0b8202[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 69]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at okhttp3.Dispatcher.enqueue(Dispatcher.java:130)
	at okhttp3.RealCall.enqueue(RealCall.java:100)
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.java:183)
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.java:436)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.exec(PodOperationsImpl.java:267)
	at io.fabric8.kubernetes.client.dsl.internal.PodOperationsImpl.exec(PodOperationsImpl.java:61)
```
in http://jenkins.jx.35.242.205.159.nip.io/job/Activiti/job/activiti-cloud-service-common/job/develop/102/console

This happens during updatebot commands and actually gets retried https://github.com/Activiti/activiti-cloud-service-common/blob/develop/Jenkinsfile#L60

So presumably what is happening here is that any steps wrapped in `container('maven')` in the pipeline involve a watch being created in the Jenkins Kubernetes Plugin implementation and we see the error when the watch is lost.

**Comment by ryandawsonuk** [comment]
With the resource changes above this seems to be much less common now - [just had a couple of clean runs](https://github.com/Activiti/Activiti/issues/2587#issuecomment-470066936)
