### ISSUE TITLE
OSGI ProcessEngineFactoryWithELResolver prevents resolvers from running

### ISSUE THREAD

**Issue by arandall** [Activiti/Activiti#259]
When trying to resolve a HashMap property the following exception is returned

```
2014-04-24 10:35:17,772 | WARN  | process/routing] | AggregateProcessor               | rg.apache.camel.util.CamelLogger  224 | 73 - org.apache.camel.camel-core - 2.12.3 | Error processing aggregated exchange. Exchange[JmsMessage[JmsMessageID: ID:localhost-45668-1398139515923-90:18:1:1:4]]. Caused by: [org.activiti.engine.ActivitiException - Unknown property used in expression: ${!empty(params.value)}]
org.activiti.engine.ActivitiException: Unknown property used in expression: ${!empty(params.value)}
...
Caused by: org.activiti.engine.impl.javax.el.PropertyNotFoundException: Could not find property value in class java.util.HashMap
        at org.activiti.engine.impl.javax.el.BeanELResolver.toBeanProperty(BeanELResolver.java:627)[163:org.activiti.engine:5.15.0]
        at org.activiti.engine.impl.javax.el.BeanELResolver.getValue(BeanELResolver.java:298)[163:org.activiti.engine:5.15.0]
...
```

The order of the ELResolvers differs from other parts of the code changing to the following resolves the issue:

```
      compositeElResolver.add(new VariableScopeElResolver(variableScope));
      if (blueprintContextELResolver != null) {
        compositeElResolver.add(blueprintContextELResolver);
      }
      compositeElResolver.add(blueprintELResolver);
      compositeElResolver.add(new ArrayELResolver());
      compositeElResolver.add(new ListELResolver());
      compositeElResolver.add(new MapELResolver());
      compositeElResolver.add(new BeanELResolver());
```

see http://forums.activiti.org/content/compositeelresolver-order-processenginefactorywithelresolverjava for more details

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
