### ISSUE TITLE
Found Activiti 5 process definition, but no compatibility handler on the classpath

### ISSUE THREAD

**Issue by xxf0925** [Activiti/Activiti#2592]
hi, all:
    I use activiti 6, but when I execute `runtimeService.createExecutionQuery().executionId(id).singleResult()` , it throw the error 
```
org.activiti.engine.ActivitiException: Found Activiti 5 process definition, but no compatibility handler on the classpath
	at org.activiti.engine.impl.util.Activiti5Util.getActiviti5CompatibilityHandler(Activiti5Util.java:105) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.util.ProcessDefinitionUtil.getProcess(ProcessDefinitionUtil.java:55) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.persistence.entity.ExecutionEntityImpl.getCurrentFlowElement(ExecutionEntityImpl.java:263) ~[activiti-engine-6.0.0.jar:6.0.0]
```

this is my code : 
```
    @Autowired
    private RuntimeService runtimeService;
    @Override
    public String list(String id) {
        Execution list = runtimeService.createExecutionQuery().executionId(id).singleResult();
        return JSONObject.toJSONString(list);
    }
```

my pom:
```	
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.1.3.RELEASE</version>
	<relativePath/> <!-- lookup parent from repository -->
</parent>
...
<dependency>
	<groupId>org.activiti</groupId>
	<artifactId>activiti-spring-boot-starter-basic</artifactId>
	<version>6.0.0</version>
</dependency>
```

**Comment by jackie1236666** [comment]
怎么解决的，请问
