### ISSUE TITLE
 one wonderful idea, want to design universal workflow template

### ISSUE THREAD

**Issue by yangpancode** [Activiti/Activiti#2654]
I have a wonderful idea, to design universal workflow template，as follows.
![image](https://user-images.githubusercontent.com/16751135/54891712-5f04b000-4ee9-11e9-8cfd-7b53f7eeeaed.png)
```
<process id="universal" name="universal workflow template" isExecutable="true">
    <documentation>universal workflow template</documentation>
    <startEvent id="start"></startEvent>
    <userTask id="user-task" name="user-task"></userTask>
    <exclusiveGateway id="eclusive"></exclusiveGateway>
    <callActivity id="itself" name="process-itself" calledElement="universal" activiti:inheritVariables="false"></callActivity>
    <endEvent id="end"></endEvent>
    <sequenceFlow id="to-user-task" sourceRef="start" targetRef="user-task"></sequenceFlow>
    <sequenceFlow id="to-end-or-itself" sourceRef="user-task" targetRef="eclusive"></sequenceFlow>
    <sequenceFlow id="to-end" sourceRef="eclusive" targetRef="end"></sequenceFlow>
    <sequenceFlow id="itself-to-end" sourceRef="itself" targetRef="end"></sequenceFlow>
    <sequenceFlow id="to-itself" sourceRef="eclusive" targetRef="itself"></sequenceFlow>
  </process>
```

Process nesting itself. You can call yourself at any time, no matter how many tasks and what tasks you have. but it cannot resolve parallel tasks and multi-instance tasks. so I change this template as follows. change the process-itself to  parallel multiInstance. 
```
   <process id="universal" name="universal" isExecutable="true">
    <documentation>universal workflow template</documentation>
    <startEvent id="start"></startEvent>
    <userTask id="user-task" name="${taskMap.taskName}" activiti:assignee="${taskMap.taskUser}">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://activiti.com/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <exclusiveGateway id="exclusive"></exclusiveGateway>
    <callActivity id="itself" name="process-itself" calledElement="universal" activiti:inheritVariables="false">
      <extensionElements>
        <activiti:in source="taskMap_" target="taskMap"></activiti:in>
        <activiti:in source="flag" target="flag"></activiti:in>
        <activiti:out source="taskOutMap" target="taskOutMap"></activiti:out>
      </extensionElements>
      <multiInstanceLoopCharacteristics isSequential="false" activiti:collection="${taskMapList}" activiti:elementVariable="taskMap_"></multiInstanceLoopCharacteristics>
    </callActivity>
    <endEvent id="end"></endEvent>
    <sequenceFlow id="to-end-or-itself" sourceRef="user-task" targetRef="exclusive"></sequenceFlow>
    <sequenceFlow id="itself-to-end" sourceRef="itself" targetRef="end"></sequenceFlow>
    <sequenceFlow id="to-user-task" sourceRef="start" targetRef="user-task"></sequenceFlow>
    <sequenceFlow id="to-itself" sourceRef="exclusive" targetRef="itself">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${flag==1}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="to-end" sourceRef="exclusive" targetRef="end">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${flag==0}]]></conditionExpression>
    </sequenceFlow>
  </process>
```
![image](https://user-images.githubusercontent.com/16751135/55693094-b9206d80-59df-11e9-92c6-ea8c0d986921.png)

Is this universal ? some one have any other good ideals. Openly welcome everyone to come up with ideas

**Comment by proth1** [comment]
@yangpancode What do you mean by universal?  Can you describe the business problem you are addressing?

**Comment by yangpancode** [comment]
I am sorry to answer your question so late. The scene is to design a dynamic common workflow template, can support any task.

**Comment by proth1** [comment]
Perhaps you can provide a more detailed explanation?

**Comment by headays** [comment]
I think it is a very good idea. When I did this, I had a little trouble.
Use this process diagram
![image](https://user-images.githubusercontent.com/16751135/55693722-2b468180-59e3-11e9-91f1-3b4d4a51ccf1.png)
```
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/processdef">
  <process id="universal" name="universal" isExecutable="true">
    <documentation>universal workflow template</documentation>
    <startEvent id="start"></startEvent>
    <userTask id="user-task" name="${taskMap.taskName}" activiti:assignee="${taskMap.taskUser}">
      <extensionElements>
        <modeler:initiator-can-complete xmlns:modeler="http://activiti.com/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <exclusiveGateway id="exclusive"></exclusiveGateway>
    <callActivity id="itself" name="process-itself" calledElement="universal" activiti:inheritVariables="false">
      <extensionElements>
        <activiti:in source="taskMap_" target="taskMap"></activiti:in>
        <activiti:in source="flag" target="flag"></activiti:in>
        <activiti:out source="taskOutMap" target="taskOutMap"></activiti:out>
      </extensionElements>
      <multiInstanceLoopCharacteristics isSequential="false" activiti:collection="${taskMapList}" activiti:elementVariable="taskMap_"></multiInstanceLoopCharacteristics>
    </callActivity>
    <endEvent id="end"></endEvent>
    <sequenceFlow id="to-end-or-itself" sourceRef="user-task" targetRef="exclusive"></sequenceFlow>
    <sequenceFlow id="itself-to-end" sourceRef="itself" targetRef="end"></sequenceFlow>
    <sequenceFlow id="to-user-task" sourceRef="start" targetRef="user-task"></sequenceFlow>
    <sequenceFlow id="to-itself" sourceRef="exclusive" targetRef="itself">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${flag==1}]]></conditionExpression>
    </sequenceFlow>
    <sequenceFlow id="to-end" sourceRef="exclusive" targetRef="end">
      <conditionExpression xsi:type="tFormalExpression"><![CDATA[${flag==0}]]></conditionExpression>
    </sequenceFlow>
  </process>
```
Start with these parameters：  {"taskMap":{"taskName":"baoan","taskUser":"user1"}}
complete task of baoan with these parameters : {"taskMapList":[{"taskName":"task1","taskUser":"user1"},{"taskName":"task2","taskUser":"user1"}],"flag":1}
but in callActivity calledElement="universal"，can not complete task1 with these parameters : {"flag":0},
Error is as follows：
```
org.activiti.engine.ActivitiException: Unknown property used in expression: ${taskMapList}
	at org.activiti.engine.impl.el.JuelExpression.getValue(JuelExpression.java:52)
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveCollection(MultiInstanceActivityBehavior.java:237)
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveAndValidateCollection(MultiInstanceActivityBehavior.java:213)
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveNrOfInstances(MultiInstanceActivityBehavior.java:184)
	at org.activiti.engine.impl.bpmn.behavior.ParallelMultiInstanceBehavior.createInstances(ParallelMultiInstanceBehavior.java:53)
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.execute(MultiInstanceActivityBehavior.java:92)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:180)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeMultiInstanceSynchronous(ContinueProcessOperation.java:163)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:86)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:55)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:35)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:186)
```
I don't understand why it will take the value of this taskMapList variable while I use parameters of {"flag":0}？

**Comment by salaboy** [comment]
@yangpancode @headays this is a wonderful thread.. I love when these things are suggested in Open Source communities. 
In general I will be against of having universal solutions, due they add an abstraction layer that will add a lot of confusion and visibility problems. 

When you implement something like this solution you will then need to check at runtime if the call activity elements has a valid process definition that can be executed, if not the process will fail to execute. 

I don't see any action to be taken here.. but I will appreciate feedback about what are you planning to do with the solution that you are building.
