### ISSUE TITLE
ProcessExtensionService.processExtensionModelMap -> NPE in hasExtensionsFor(String processDefinitionKey) 

### ISSUE THREAD

**Issue by campa** [Activiti/Activiti#2861]
using with spring boot embedded , activiti release 7.1.58 
with this proc def 
```
<?xml version="1.0" encoding="UTF-8"?>
<definitions ... PMN20.xsd">
  <process id="process-d564ea01-1b9c-4fda-b4e3-42adcae37ebc" name="Attak1" isExecutable="true">
    <startEvent id="StartEvent_1"></startEvent>
    <sequenceFlow id="SequenceFlow_04s8u2a" sourceRef="StartEvent_1" targetRef="usertask1"></sequenceFlow>
    <userTask id="usertask1" name="Analysis">
      <documentation>using the X tool get info from the sea... </documentation>
    </userTask>
    <endEvent id="endevent1" name="End"></endEvent>
    <sequenceFlow id="flow1" sourceRef="usertask1" targetRef="endevent1"></sequenceFlow>
  </process>
</definitions>
```
running:

```
ProcessInstance processInstance = processRuntime.start(ProcessPayloadBuilder
                .start()
                .withProcessDefinitionKey("process-d564ea01-1b9c-4fda-b4e3-42adcae37ebc")
                .withName("Attak1")
                .withVariables(variables)
                .build());
```
NPE here

```
Caused by: java.lang.NullPointerException: null
	at org.activiti.spring.process.ProcessExtensionService.hasExtensionsFor(ProcessExtensionService.java:112)
	at org.activiti.spring.process.ProcessExtensionService.hasExtensionsFor(ProcessExtensionService.java:108)
	at org.activiti.spring.process.ProcessVariablesInitiator.createAndStartProcessInstanceWithInitialFlowElement(ProcessVariablesInitiator.java:81)
	at org.activiti.engine.impl.util.ProcessInstanceHelper.createAndStartProcessInstance(ProcessInstanceHelper.java:75)
	at org.activiti.engine.impl.util.ProcessInstanceHelper.createAndStartProcessInstance(ProcessInstanceHelper.java:50)
	at org.activiti.engine.impl.cmd.StartProcessInstanceCmd.createAndStartProcessInstance(StartProcessInstanceCmd.java:109)
```
In the method of ProcessExtensionService below the processExtensionModelMap is null, here:

```
   public boolean hasExtensionsFor(String processDefinitionKey) {
        return processExtensionModelMap.containsKey(processDefinitionKey);
    }
```

Any suggestion so solve ?

**Comment by campa** [comment]
Solved calling processExtensionService.readProcessExtensions() before using it :

```
 @Autowired
    private ProcessExtensionService processExtensionService;
    @PostConstruct
    void init() throws IOException {
    	processExtensionService.readProcessExtensions();
```
