### ISSUE TITLE
 UserTask sets assignee to variable ${employeeGroup} when calling startProcessInstanceByKey method error

### ISSUE THREAD

**Issue by LiWeiWei233** [Activiti/Activiti#2872]
My problem is that I can't set assignee as a variable when creating a dynamic process,
I am using activit6.0 now. 
fix:
I didn't describe the problem clearly. I constructed the process myself, and then verified the deployment success by calling the runtimeService.startProcessInstanceByKey("") method. Then I got the error. I think the startProcessInstanceByKey("") method is set to variable in assignee. When the call is a problem

My code：
` private static UserTask createUserTask(String id, String name, String assignee, String desc) {
        UserTask userTask = new UserTask();
        userTask.setName(name);
        userTask.setId(FlowItemConstant.FLOW_DYNAMIC.getCode() + id);
        userTask.setAssignee(assignee); // when run assignee value is ${employeeGroup}
        userTask.setDocumentation(desc);
        return userTask;
    }`

The error:
`org.activiti.engine.ActivitiException: Unknown property used in expression: ${employeeGroup}
	at org.activiti.engine.impl.el.JuelExpression.getValue(JuelExpression.java:52)
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.handleAssignments(UserTaskActivityBehavior.java:244)
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.execute(UserTaskActivityBehavior.java:207)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:180)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:131)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:89)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:55)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:82)`

Thank you for your help!

**Comment by ggrnd0** [comment]
> Unknown property used in expression
Process do not have variable with name 'employeeGroup'

try `${execution.getVariable('employeeGroup')}` for avoid exception and get null instead.

**Comment by LiWeiWei233** [comment]
> ${execution.getVariable('employeeGroup')}


I didn't describe the problem clearly. I constructed the process myself, and then verified the deployment success by calling the runtimeService.startProcessInstanceByKey("") method. Then I got the error. I think the startProcessInstanceByKey("") method is set to variable in assignee. When the call is a problem

**Comment by LiWeiWei233** [comment]
I have solved this problem, I forgot to pass in the variable when starting the process instance.
`// 4. Start a process instance
        Map<String, Object> variableMap = new HashMap<String, Object>();
        variableMap.put("employeeGroup", "groupA");
        ProcessInstance processInstance = processEngine.getRuntimeService().startProcessInstanceByKey(processDefinitionKey,variableMap);`
