### ISSUE TITLE
I found a problem

### ISSUE THREAD

**Issue by jonny-jiang** [Activiti/Activiti#2962]
When I complete a task with variables, then got an exception as follow:
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.sql.SQLException: 违反引用约束[ACT_FK_VAR_EXE]
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:213) ~[mybatis-3.4.6.jar:3.4.6]
	at org.activiti.engine.impl.db.DbSqlSession.flushDeleteEntities(DbSqlSession.java:911) ~[activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.db.DbSqlSession.flushDeletes(DbSqlSession.java:871) ~[activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:525) ~[activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:237) ~[activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:102) ~[activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:68) [activiti-engine-7.1.41.jar:na]
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) [activiti-spring-7.1.41.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) [spring-tx-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) [activiti-spring-7.1.41.jar:na]
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29) [activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44) [activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) [activiti-engine-7.1.41.jar:na]
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:201) [activiti-engine-7.1.41.jar:na]

**Comment by jonny-jiang** [comment]
the next flow element is end event

**Comment by jonny-jiang** [comment]
completing with transient variables
