### ISSUE TITLE
`INTEGRATION_REQUESTED` and `INTEGRATION_RESULT_RECEIVED` events produce exceptions at consumer side

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#3153]
The following exceptions appear in both audit and query services:
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.activiti.cloud.api.model.shared.events.CloudRuntimeEvent[]` out of START_OBJECT token
 at [Source: (byte[])"{"eventType":"INTEGRATION_REQUESTED","id":"658c6168-cd3b-48f8-8f58-657eda3d27fa","timestamp":1582024441405,"entity":{"id":"c40f8550-523f-11ea-84da-26a2b86cd1bc","outBoundVariables":{},"processInstanceId":"c40f5e3d-523f-11ea-84da-26a2b86cd1bc","processDefinitionId":"ConnectorProcess:1:8b9abbc7-5231-11ea-84da-26a2b86cd1bc","processDefinitionKey":"ConnectorProcess","processDefinitionVersion":1,"clientId":"sid-CDFE7219-4627-43E9-8CA8-866CC38EBA94","clientName":"Connector Task","clientType":"ServiceT"[truncated 283 bytes]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:175)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3122)
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:221)
	... 37 more
```
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `org.activiti.cloud.api.model.shared.events.CloudRuntimeEvent[]` out of START_OBJECT token
 at [Source: (byte[])"{"eventType":"INTEGRATION_RESULT_RECEIVED","id":"d384bc53-e47d-4bb3-934e-81a3c9623641","timestamp":1582023995367,"entity":{"id":"ba2b963e-523e-11ea-84da-26a2b86cd1bc","outBoundVariables":{"serviceType":"runtime-bundle","amqp_receivedDeliveryMode":"PERSISTENT","appVersion":"1","amqp_receivedExchange":"headers.GET","amqp_deliveryTag":14,"amqp_redelivered":false,"processDefinitionKey":"HeadersConnectorProcess","serviceVersion":"","spanId":"1546b6e92f2cdf6e","messagePayloadType":"org.activiti.cloud."[truncated 2032 bytes]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:330)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:175)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4014)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3122)
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:221)
	... 37 common frames omitted
```

Fix: the message has to be sent as an array to be consumed by audit and query in the messaging system.

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/520
