### ISSUE TITLE
When using Spring to build engine, process deployment is not possible using RepositoryService

### ISSUE THREAD

**Issue by shivamgupta1** [Activiti/Activiti#3194]
The error:
```
org.activiti.api.runtime.shared.UnprocessableEntityException: Process definition with the given id:'testProcess:1:d7aa1244-6ce1-11ea-b46c-fe54002f66cf' belongs to a different application version.
        at org.activiti.runtime.api.impl.ProcessRuntimeImpl.checkProcessDefinitionBelongsToLatestDeployment(ProcessRuntimeImpl.java:140)
        at org.activiti.runtime.api.impl.ProcessRuntimeImpl.processDefinition(ProcessRuntimeImpl.java:120)
        at org.activiti.runtime.api.impl.ProcessRuntimeImpl.getProcessDefinitionAndCheckUserHasRights(ProcessRuntimeImpl.java:418)
        at org.activiti.runtime.api.impl.ProcessRuntimeImpl.start(ProcessRuntimeImpl.java:252)
        at org.activiti.runtime.api.impl.ProcessRuntimeImpl$$FastClassBySpringCGLIB$$60a3d48.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.activiti.runtime.api.impl.ProcessRuntimeImpl$$EnhancerBySpringCGLIB$$7304ea3d.start(<generated>)
```

**Comment by shivamgupta1** [comment]
Steps to reproduce:
1. Create an engine using Spring method of building engine.
2. Deploy a process using RepositoryService.
3. Using ProcessRuntime APIs to start the process **using its key**.
