### ISSUE TITLE
For JDK8 compatibility(52) issues ,class file versions up to 55,

### ISSUE THREAD

**Issue by jf11480** [Activiti/Activiti#3231]
## Running error

``` java
Caused by: java.lang.UnsupportedClassVersionError: org/activiti/engine/api/internal/Internal has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_192]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_192]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_192]
```

##  Version
``` java
<groupId>org.activiti</groupId>
<artifactId>activiti-engine</artifactId>
<version>7.0.0.GA</version>
```

## Error location
 path:  org.activiti.engine.api.internal.Internal

**Comment by jf11480** [comment]
Solved: just upgrade the version .
<groupId>org.activiti</groupId>
<artifactId>activiti-engine</artifactId>
<version>7.0.0.SR1</version>

**Comment by jf11480** [comment]
Solved: just upgrade the version .
<groupId>org.activiti</groupId>
<artifactId>activiti-engine</artifactId>
<version>7.0.0.SR1</version>
