### ISSUE TITLE
Starting a process calling 500 subprocesses ends up in endless loop

### ISSUE THREAD

**Issue by mathieubodin** [Activiti/Activiti#3271]
Lets say there are 2 process definitions:
- `sub` which define only 1 task
- `main` which creates 500 subs

I got the following stack:
```
java.lang.NullPointerException: null
	at org.activiti.spring.process.ProcessExtensionService.getExtensionsFor(ProcessExtensionService.java:74)
	at org.activiti.spring.process.ProcessExtensionService.getExtensionsForId(ProcessExtensionService.java:83)
	at org.activiti.runtime.api.impl.VariablesMappingProvider.calculateInputVariables(VariablesMappingProvider.java:68)
	at org.activiti.runtime.api.impl.MappingAwareCallActivityBehavior.calculateInboundVariables(MappingAwareCallActivityBehavior.java:60)
	at org.activiti.engine.impl.bpmn.behavior.CallActivityBehavior.execute(CallActivityBehavior.java:124)
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.execute(MultiInstanceActivityBehavior.java:108)
	at org.activiti.engine.impl.agenda.ContinueMultiInstanceOperation.executeSynchronous(ContinueMultiInstanceOperation.java:75)
	at org.activiti.engine.impl.agenda.ContinueMultiInstanceOperation.continueThroughMultiInstanceFlowNode(ContinueMultiInstanceOperation.java:48)
	at org.activiti.engine.impl.agenda.ContinueMultiInstanceOperation.run(ContinueMultiInstanceOperation.java:40)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	
// The stack below gets repeated 340 times

at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.RepositoryServiceImpl.getProcessDefinition(RepositoryServiceImpl.java:138)
	at org.activiti.spring.process.ProcessExtensionService.getExtensionsForId(ProcessExtensionService.java:81)
	at org.activiti.runtime.api.impl.VariablesMappingProvider.calculateInputVariables(VariablesMappingProvider.java:68)
	at org.activiti.runtime.api.impl.MappingAwareCallActivityBehavior.calculateInboundVariables(MappingAwareCallActivityBehavior.java:60)
	at org.activiti.engine.impl.bpmn.behavior.CallActivityBehavior.execute(CallActivityBehavior.java:124)
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.execute(MultiInstanceActivityBehavior.java:108)
	at org.activiti.engine.impl.agenda.ContinueMultiInstanceOperation.executeSynchronous(ContinueMultiInstanceOperation.java:75)
	at org.activiti.engine.impl.agenda.ContinueMultiInstanceOperation.continueThroughMultiInstanceFlowNode(ContinueMultiInstanceOperation.java:48)
	at org.activiti.engine.impl.agenda.ContinueMultiInstanceOperation.run(ContinueMultiInstanceOperation.java:40)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
```

My question is: why? Is there a know limit ? I want to test how the runtime bundle behave with 10000 living tasks, but if I can't generate more than 340, it's pointless...

For now I fall back to multiple call to 100 subprocesses creations but something smells badly bad...

**Comment by mathieubodin** [comment]
I reproduce the same behavior with the following process definition
[nardole.zip](https://github.com/Activiti/Activiti/files/4555017/nardole.zip)

**Comment by mathieubodin** [comment]
Nobody ?

**Comment by mathieubodin** [comment]
After hours of investigation, it appears that the present usecase is tricky :) I studied it with the version M11.

Firts thing first: wiring a call activity to another process (from the same model or another) with such cardinality, either through a collection or with an explicit amount lead to a StackOverflow due to the JVM `Xss` option. It was illustrated with an increase on the latter which once set to 2mb allow a cardinality of 500, but still forbid 800. 

My first conclusion is that a runtime bundle **can't** handle such amount of sub process **synchronous** creations. 

Then I tried to split invocations into batches within their own hhread, but failed one step later, especially during the *synchronous* treatment of the CallActivityBehavior.

I closely looked at the code of [ContinueMultiInstanceOperation](https://github.com/Activiti/Activiti/blob/6e9bfd070ad74276cf57d7946cb8e70a2ed969ad/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/ContinueMultiInstanceOperation.java#L61) which was involved in the StackOverflow and noticed that there was another path of execution: **asynchronous** sub process instance creations !

After looking for a way to do it (btw juste add the attribute `activiti:async="true"` to *callActivity* tag in XML), I successfully  tested it with 500 even **2000** as cardinality **without** any increase on the `Xss` option.

My second conclusion is that a runtime bundle *may* handle such amount of sub process **asynchronous** creations.

There is at least one drawback: since the creation process is asynchronous, you may have to wait for the whole bunch of process to be started... But it seems that it's not big deal as we're talking about sub processes that will run on their own. Note that I haven't checked the behaviors once the subprocesses are completed, but I'm fairly confident it should work the same way.

As a conclusion, I would say there is a memory black hole in the current implementation of such synchronous usecase (as the M12 tag doesn't change anything on that matter) that **still smells very bad**. The good news is that it could be solved with an asynchronous approach, which is fairly acceptable when it's about sub process creations. It **SHOULD** be documented somewhere. And it **MAY** become a specific behavior, i.e. when callActivity should create sub processes, then it does it *asynchronously*, unless it's specified otherwise (`activiti:async="false"`).

I let this issue open, as a StackOverflow should be examinated and **solved**. :p
