### ISSUE TITLE
Can't apply mail settings to the v5 engine after it's built

### ISSUE THREAD

**Issue by s-onuma** [Activiti/Activiti#3379]
I'm using Activiti 6.0.0 with old process instances created in v5.19.0.2, but email tasks in the old processes are failing due to an error `javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;` (The full log is attached at the bottom)

As far as I investigated, the mail host that I programmatically set after the engine was built looks not effective to the ProcessEngineConfiguration of the v5 engine.

Is there any way that I can set the mail settings to the v5 engine later? If not, is this a limitation or a bug?

**Sample code**
```java
public class MyWorkflowEngine {

  private final ProcessEngine engine;

  MyWorkflowEngine() {
    engine = ProcessEngineConfiguration.createProcessEngineConfigurationFromResource("activiti-context.xml")
                                       .buildProcessEngine();
  }

  public setMailServerHost(String hostname) { // Users of my application can set mail config later
    this.engine.setMailServerHost(hostname); // It's not propagated to the v5 configuration
  }
}
```

**Log**
```
[2020-07-13 13:32:12,133] ERROR   [activiti-async-job-executor-thread-1263] Job 368458 failed (AsyncJobUtil.java:59)
org.activiti5.engine.ActivitiException: Could not send e-mail in execution 271544
	at org.activiti5.engine.impl.bpmn.behavior.MailActivityBehavior.handleException(MailActivityBehavior.java:411)
	at org.activiti5.engine.impl.bpmn.behavior.MailActivityBehavior.execute(MailActivityBehavior.java:107)
	at org.activiti5.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:62)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerStart.eventNotificationsCompleted(AtomicOperationTransitionNotifyListenerStart.java:52)
	at org.activiti5.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:56)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:49)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AtomicOperationTransitionCreateScope.execute(AtomicOperationTransitionCreateScope.java:49)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerTake.execute(AtomicOperationTransitionNotifyListenerTake.java:80)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AtomicOperationTransitionDestroyScope.execute(AtomicOperationTransitionDestroyScope.java:116)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerEnd.eventNotificationsCompleted(AtomicOperationTransitionNotifyListenerEnd.java:35)
	at org.activiti5.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:56)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:49)
	at org.activiti5.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:100)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:646)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:641)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.take(ExecutionEntity.java:458)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.take(ExecutionEntity.java:436)
	at org.activiti5.engine.impl.bpmn.behavior.BpmnActivityBehavior.performOutgoingBehavior(BpmnActivityBehavior.java:148)
	at org.activiti5.engine.impl.bpmn.behavior.BpmnActivityBehavior.performDefaultOutgoingBehavior(BpmnActivityBehavior.java:67)
	at org.activiti5.engine.impl.bpmn.behavior.FlowNodeActivityBehavior.leave(FlowNodeActivityBehavior.java:45)
	at org.activiti5.engine.impl.bpmn.behavior.AbstractBpmnActivityBehavior.leave(AbstractBpmnActivityBehavior.java:47)
	at org.activiti5.engine.impl.bpmn.behavior.IntermediateCatchEventActivityBehavior.signal(IntermediateCatchEventActivityBehavior.java:28)
	at org.activiti5.engine.impl.persistence.entity.ExecutionEntity.signal(ExecutionEntity.java:415)
	at org.activiti5.engine.impl.jobexecutor.TimerCatchIntermediateEventJobHandler.execute(TimerCatchIntermediateEventJobHandler.java:56)
	at org.activiti5.engine.impl.persistence.entity.JobEntity.execute(JobEntity.java:67)
	at org.activiti5.engine.impl.cmd.ExecuteAsyncJobCmd.execute(ExecuteAsyncJobCmd.java:65)
	at org.activiti5.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
	at org.activiti5.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:58)
	at org.activiti5.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti5.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti5.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
	at org.activiti5.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
	at org.activiti5.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
	at org.activiti5.engine.impl.asyncexecutor.AsyncJobUtil.executeJob(AsyncJobUtil.java:40)
	at org.activiti.compatibility.DefaultActiviti5CompatibilityHandler.executeJobWithLockAndRetry(DefaultActiviti5CompatibilityHandler.java:803)
	at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable$2.execute(ExecuteAsyncRunnable.java:87)
	at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable$2.execute(ExecuteAsyncRunnable.java:84)
	at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.isHandledByActiviti5Engine(ExecuteAsyncRunnable.java:84)
	at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1164)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:634)
	at java.lang.Thread.run(Thread.java:809)
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at org.activiti5.engine.impl.bpmn.behavior.MailActivityBehavior.execute(MailActivityBehavior.java:102)
	... 75 more
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1545)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:453)
	at javax.mail.Service.connect(Service.java:291)
	at javax.mail.Service.connect(Service.java:172)
	at javax.mail.Service.connect(Service.java:121)
	at javax.mail.Transport.send0(Transport.java:190)
	at javax.mail.Transport.send(Transport.java:120)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 77 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.Socket.connect(Socket.java:643)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:265)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:227)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1511)
	... 84 more
```

**Comment by mteodori** [comment]
version 7.x is the current one under active development, we only accept PRs for former versions
