### ISSUE TITLE
ProcessRuntimeBPMNTimerIT fails intermittently

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#3387]
The following test is failing intermittently:

```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.356 s <<< FAILURE! - in org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT
8336[ERROR] shouldGetTimerFiredScheduledEventsForProcessWithTimer  Time elapsed: 10.073 s  <<< ERROR!
8337org.awaitility.core.ConditionTimeoutException: 
8338Assertion condition defined as a lambda expression in org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT 
8339Expecting:
8340 <[]>
8341to contain:
8342 <[(TIMER_FIRED, "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "6d7a0408-908e-11ea-aa3a-0242fd6a0551", "timer")]>
8343but could not find:
8344 <[(TIMER_FIRED, "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "6d7a0408-908e-11ea-aa3a-0242fd6a0551", "timer")]>
8345 within 10 seconds.
8346	at org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT.shouldGetTimerFiredScheduledEventsForProcessWithTimer(ProcessRuntimeBPMNTimerIT.java:167)
8347Caused by: java.lang.AssertionError: 
8348
8349Expecting:
8350 <[]>
8351to contain:
8352 <[(TIMER_FIRED, "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "6d7a0408-908e-11ea-aa3a-0242fd6a0551", "timer")]>
8353but could not find:
8354 <[(TIMER_FIRED, "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "4ebf589e-908e-11ea-aa3a-0242fd6a0551", "6d7a0408-908e-11ea-aa3a-0242fd6a0551", "timer")]>
8355
8356	at org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT.lambda$shouldGetTimerFiredScheduledEventsForProcessWithTimer$12(ProcessRuntimeBPMNTimerIT.java:175)
```

**Comment by erdemedeiros** [comment]
The changes are not enough, It test keep failing intermittently.
```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.64 s <<< FAILURE! - in org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT
[ERROR] shouldGetTimerFiredScheduledEventsForProcessWithTimer  Time elapsed: 10.107 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a lambda expression in org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT 
Expecting:
 <[]>
to contain:
 <[(TIMER_FIRED, "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "ae4b6a5a-d0b4-11ea-a65c-0242a50db4a2", "timer")]>
but could not find:
 <[(TIMER_FIRED, "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "ae4b6a5a-d0b4-11ea-a65c-0242a50db4a2", "timer")]>
 within 10 seconds.
	at org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT.shouldGetTimerFiredScheduledEventsForProcessWithTimer(ProcessRuntimeBPMNTimerIT.java:151)
Caused by: java.lang.AssertionError: 
Expecting:
 <[]>
to contain:
 <[(TIMER_FIRED, "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "ae4b6a5a-d0b4-11ea-a65c-0242a50db4a2", "timer")]>
but could not find:
 <[(TIMER_FIRED, "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "8d8fbf84-d0b4-11ea-a65c-0242a50db4a2", "ae4b6a5a-d0b4-11ea-a65c-0242a50db4a2", "timer")]>
	at org.activiti.spring.boot.process.ProcessRuntimeBPMNTimerIT.lambda$shouldGetTimerFiredScheduledEventsForProcessWithTimer$12(ProcessRuntimeBPMNTimerIT.java:159)
```
