### ISSUE TITLE
Error in createElResolver after migrate 5.7 to 6 

### ISSUE THREAD

**Issue by azizkhani** [Activiti/Activiti#3461]
```
Oct 13, 2020 2:18:43 PM org.apache.catalina.core.ApplicationContext log
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine': FactoryBean threw exception on object creation; nested exception is java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/activiti/spring/SpringExpressionManager.createElResolver(Lorg/activiti/engine/delegate/VariableScope;)Ljavax/el/ELResolver; @17: invokevirtual
  Reason:
    Type 'org/activiti/engine/impl/el/VariableScopeElResolver' (current frame, stack[1]) is not assignable to 'javax/el/ELResolver'
  Current Frame:
    bci: @17
    flags: { }
    locals: { 'org/activiti/spring/SpringExpressionManager', 'org/activiti/engine/delegate/VariableScope', 'javax/el/CompositeELResolver' }
    stack: { 'javax/el/CompositeELResolver', 'org/activiti/engine/impl/el/VariableScopeElResolver' }
  Bytecode:
    0x0000000: bb00 0359 b700 044d 2cbb 0005 592b b700
    0x0000010: 06b6 0007 2ab4 0008 c600 152c bb00 0959
    0x0000020: 2ab4 0008 b700 0ab6 0007 a700 122c bb00
    0x0000030: 0b59 2ab4 0002 b700 0cb6 0007 2cbb 000d
    0x0000040: 59b7 000e b600 072c bb00 0f59 b700 10b6
    0x0000050: 0007 2cbb 0011 59b7 0012 b600 072c bb00
    0x0000060: 1359 b700 14b6 0007 2cbb 0015 59b7 0016
    0x0000070: b600 072c b0                           
  Stackmap Table:
    append_frame(@45,Object[#47])
    same_frame(@60)

	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:149)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1468)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:249)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:353)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1055)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:951)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:389)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:294)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4797)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5291)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1553)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:622)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:569)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/activiti/spring/SpringExpressionManager.createElResolver(Lorg/activiti/engine/delegate/VariableScope;)Ljavax/el/ELResolver; @17: invokevirtual
  Reason:
    Type 'org/activiti/engine/impl/el/VariableScopeElResolver' (current frame, stack[1]) is not assignable to 'javax/el/ELResolver'
  Current Frame:
    bci: @17
    flags: { }
    locals: { 'org/activiti/spring/SpringExpressionManager', 'org/activiti/engine/delegate/VariableScope', 'javax/el/CompositeELResolver' }
    stack: { 'javax/el/CompositeELResolver', 'org/activiti/engine/impl/el/VariableScopeElResolver' }
  Bytecode:
    0x0000000: bb00 0359 b700 044d 2cbb 0005 592b b700
    0x0000010: 06b6 0007 2ab4 0008 c600 152c bb00 0959
    0x0000020: 2ab4 0008 b700 0ab6 0007 a700 122c bb00
    0x0000030: 0b59 2ab4 0002 b700 0cb6 0007 2cbb 000d
    0x0000040: 59b7 000e b600 072c bb00 0f59 b700 10b6
    0x0000050: 0007 2cbb 0011 59b7 0012 b600 072c bb00
    0x0000060: 1359 b700 14b6 0007 2cbb 0015 59b7 0016
    0x0000070: b600 072c b0                           
  Stackmap Table:
    append_frame(@45,Object[#47])
    same_frame(@60)

	at org.activiti.spring.ProcessEngineFactoryBean.configureExpressionManager(ProcessEngineFactoryBean.java:63)
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:50)
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:142)
	... 66 more

Oct 13, 2020 2:18:54 PM org.apache.catalina.core.ApplicationContext log

```

**Comment by mteodori** [comment]
version 7.x is the current one under active development, please switch to that one
