### ISSUE TITLE
Not able to run Activiti-develop\activiti-examples\activiti-api-basic-full-example-nobean

### ISSUE THREAD

**Issue by sourabhparsekar** [Activiti/Activiti#3513]
I downloaded the source code and opened it in Intellij. However, when I tried to run the code, it gave me below error. I tried to google it out, but not able to understand it. Could it be because of a specific JAR version ? POM file is to take the latest one so not sure :( 

```
2021-01-11 13:17:48.108  INFO 2404 --- [   scheduling-1] org.activiti.examples.SecurityUtil       : > Logged in as: system
2021-01-11 13:17:48.114  INFO 2404 --- [   scheduling-1] org.activiti.examples.DemoApplication    : > Starting process to process content: {body=Hi there from activiti!} at 11-01-21 13:17:48
2021-01-11 13:17:48.145 ERROR 2404 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.activiti.api.runtime.shared.UnprocessableEntityException: Process definition with the given id:'categorizeHumanProcess:1:4b22a296-53e1-11eb-b01a-dc7196c5d63a' belongs to a different application version.
	at org.activiti.runtime.api.impl.ProcessRuntimeImpl.checkProcessDefinitionBelongsToLatestDeployment(ProcessRuntimeImpl.java:140) ~[activiti-api-process-runtime-impl-7.1.0.M6.jar:na]
	at org.activiti.runtime.api.impl.ProcessRuntimeImpl.processDefinition(ProcessRuntimeImpl.java:120) ~[activiti-api-process-runtime-impl-7.1.0.M6.jar:na]
	at org.activiti.runtime.api.impl.ProcessRuntimeImpl.getProcessDefinitionAndCheckUserHasRights(ProcessRuntimeImpl.java:418) ~[activiti-api-process-runtime-impl-7.1.0.M6.jar:na]
	at org.activiti.runtime.api.impl.ProcessRuntimeImpl.start(ProcessRuntimeImpl.java:252) ~[activiti-api-process-runtime-impl-7.1.0.M6.jar:na]
	at org.activiti.runtime.api.impl.ProcessRuntimeImpl$$FastClassBySpringCGLIB$$60a3d48.invoke(<generated>) ~[activiti-api-process-runtime-impl-7.1.0.M6.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.activiti.runtime.api.impl.ProcessRuntimeImpl$$EnhancerBySpringCGLIB$$5991d5c0.start(<generated>) ~[activiti-api-process-runtime-impl-7.1.0.M6.jar:na]
	at org.activiti.examples.DemoApplication.processText(DemoApplication.java:103) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-01-11 13:17:48.145  INFO 2404 --- [   scheduling-1] org.activiti.examples.SecurityUtil       : > Logged in as: bob
```

**Comment by gicappa** [comment]
We merged a pull request that fixes the examples, so I'll close this issue.

Please, feel free to reopen it if you still have problems, (if possible adding some details on how to reproduce the issue). 

Thank you!
