### ISSUE TITLE
activiti-cloud-modeling unable to save model entity

### ISSUE THREAD

**Issue by homiodev** [Activiti/Activiti#3605]
I'm trying to use <activiti-cloud-starter-modeling> dependency for bpmn modelling. But during saving it to db I faced with error:

ERROR org.activiti.cloud.services.modeling.rest.controller.ModelingRestExceptionHandler - Data access error
org.springframework.orm.jpa.JpaSystemException: attempted to assign id from null one-to-one property [org.activiti.cloud.services.modeling.entity.ModelVersionEntity.versionedEntity]; nested exception is org.hibernate.id.IdentifierGenerationException: attempted to assign id from null one-to-one property [org.activiti.cloud.services.modeling.entity.ModelVersionEntity.versionedEntity]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:331) ~[spring-orm-5.3.3.jar:5.3.3]
....
at org.activiti.cloud.services.modeling.jpa.ModelRepositoryImpl.updateModelContent(ModelRepositoryImpl.java:132) ~[activiti-cloud-services-modeling-jpa-7.1.662.jar:?]

**Comment by homiodev** [comment]
sorry, it was my mistake
