### ISSUE TITLE
7.1.0.M5 ProcessDefinition method getIdentityLinks throw NullPointerException

### ISSUE THREAD

**Issue by snowpubby** [Activiti/Activiti#3646]
Why does the process put in `resources/processes/` folder and auto deploy throw null pointer exception when I use `ProcessDefinitionEntityImpl.getIdentityLinks()`?

```
@Test
public void candidateStartersTest() {
    String processId = "abnormalApplyProcess:2:798e5ad0-b2fb-11eb-9eb6-f02f74ad9f2a";
    ProcessDefinition pd = repositoryService.createProcessDefinitionQuery()
            .processDefinitionId(processId)
            .singleResult();
    List<IdentityLinkEntity> set = ((ProcessDefinitionEntityImpl)pd).getIdentityLinks();
    Assert.assertEquals(2, set.size());
}
```

```
java.lang.NullPointerException
	at org.activiti.engine.impl.persistence.entity.ProcessDefinitionEntityImpl.getIdentityLinks(ProcessDefinitionEntityImpl.java:66)
	at com.xl.activiti.ActivitiTest.candidateStartersTest(ActivitiTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by roblues** [comment]
[org.activiti.engine.impl.persistence.entity.ProcessDefinitionEntityImpl#getIdentityLinks](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ProcessDefinitionEntityImpl.java#L65-L69)

```
public List<IdentityLinkEntity> getIdentityLinks() {
    if (!isIdentityLinksInitialized) {
      definitionIdentityLinkEntities = Context.getCommandContext().getIdentityLinkEntityManager().findIdentityLinksByProcessDefinitionId(id);
      isIdentityLinksInitialized = true;
    }

    return definitionIdentityLinkEntities;
}
```
in link invoking, it should check the null for `Context.getCommandContext()`

**Comment by roblues** [comment]
someone open the issue in 2019,
why do not they fix it?
https://github.com/Activiti/Activiti/issues/2856

**Comment by balsarori** [comment]
Calling implementation classes' methods can cause issues (NPE in this case because there is no active context). They are meant for internal use only and that's why they're hidden (i.e not part of the interface). There is a public Java API where you can retrieve such information from, in this case it's `RepositoryService.getIdentityLinksForProcessDefinition(processDefinitionId)`.

I hope that helps. Closing this issue.

**Comment by roblues** [comment]
Admiting that you guys writing bad code is so hard。
when returning some ProcessDefinitionEntityImpl object to client in spring project, it will use objectmapper to check the ProcessDefinetionEntityImpl's method like getXXX.  So unlucky, it throw NPE.

**Comment by balsarori** [comment]
@roblues Can you point to the code? Definitely, calling the `ProcessDefinitionEntityImpl` getXXX methods is incorrect.

**Comment by roblues** [comment]
```
 public List<IdentityLinkEntity> getIdentityLinks() {
    if (!isIdentityLinksInitialized) {
      definitionIdentityLinkEntities = Context.getCommandContext().getIdentityLinkEntityManager().findIdentityLinksByProcessDefinitionId(id);
      isIdentityLinksInitialized = true;
    }
    return definitionIdentityLinkEntities;
  }
```
the code above is bad, while Context.getCommandContext() or  getIdentityLinkEntityManager() is null , NPE will be throw out

my sugestion is 
```
public List<IdentityLinkEntity> getIdentityLinks() {
    if (!isIdentityLinksInitialized) {
      CommandContext context = Context.getCommandContext();
     if(context!=null){
            IdentityLinkEntityManager entityManager=context .getIdentityLinkEntityManager();
                       if(entityManager!=null){
                              definitionIdentityLinkEntities = =entityManager.findIdentityLinksByProcessDefinitionId(id);
                              isIdentityLinksInitialized = true;
                       }
     }
     return definitionIdentityLinkEntities;
  }
```

**Comment by roblues** [comment]
```
@GetMapping("/lists")
@ResponseBody
List<ProcessDefinition> listProcess() {
    RepositoryService repositoryService = processEngine.getRepositoryService();
    ProcessDefinitionQuery processDefinitionQuery = repositoryService.createProcessDefinitionQuery();
    return processDefinitionQuery.list();
}
```
the code above will throw NPE. 
Spring use ObjectMapper to transfer ProcessDefinition to JSON.
ObjectMapper  treat object'method like getXXX as field,   it will invoke getXXX, then NPE will be thrown out.

**Comment by balsarori** [comment]
@roblues you shouldn't return a `ProcessDefinition` object directly to the client instead it should be mapped to JSON Java representation class. Maybe that's not perfect but the engine classes were not implemented for such cases.
