### ISSUE TITLE
TransientVariableInstance cannot be cast to VariableInstanceEntity

### ISSUE THREAD

**Issue by scrapooo** [Activiti/Activiti#3715]
### Activity:6.0.0

**The following error occurred while completing the task**:  ` taskService.complete(taskId, null, model.getTransientVariables());`

```
java.lang.ClassCastException: org.activiti.engine.impl.persistence.entity.TransientVariableInstance cannot be cast to org.activiti.engine.impl.persistence.entity.VariableInstanceEntity
	at org.activiti.engine.impl.persistence.entity.ExecutionEntityManagerImpl.deleteDataForExecution(ExecutionEntityManagerImpl.java:569) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.persistence.entity.ExecutionEntityManagerImpl.deleteExecutionAndRelatedData(ExecutionEntityManagerImpl.java:422) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.persistence.entity.ExecutionEntityManagerImpl.deleteProcessInstanceExecutionEntity(ExecutionEntityManagerImpl.java:455) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.agenda.EndExecutionOperation.handleProcessInstanceExecution(EndExecutionOperation.java:81) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.agenda.EndExecutionOperation.handleRegularExecution(EndExecutionOperation.java:166) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.agenda.EndExecutionOperation.run(EndExecutionOperation.java:48) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-6.0.0.jar:6.0.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) ~[activiti-engine-6.0.0.jar:6.0.0]
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:191) ~[activiti-engine-6.0.0.jar:6.0.0]
```

**Comment by Groovvy** [comment]
I have the same problem? how do i fix it？

**Comment by dkalphacoder** [comment]
@scrapooo @Groovvy i think this could help. Check it out and let me know!
https://stackoverflow.com/a/73693344/11835331

**Comment by scrapooo** [comment]
@dkalphacoder I used the transient prop in the process variable to replace transient variable. I think another way is to add a same class ExecutionEntityManagerImpl to your project with it's source code, and then modify the error place。

sorry!  Recently, I have no time to try this solution
