### ISSUE TITLE
Doesn't support JDK8?

### ISSUE THREAD

**Issue by Showleen** [Activiti/Activiti#3790]
`java`
Caused by: java.lang.UnsupportedClassVersionError: org/activiti/spring/boot/ActivitiMethodSecurityAutoConfiguration$ActivitiMethodSecurityConfiguration has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284)
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324)
	... 28 common frames omitted

**Comment by Showleen** [comment]
I tried the m16 version。
But it can't work. Does it not support jdk1.8? Thank you

**Comment by HurryUpWb** [comment]
the same issues，https://github.com/Activiti/Activiti/issues/2428

**Comment by erdemedeiros** [comment]
@Showleen @HurryUpWb I confirm that JDK 8 is no longer supported.
