### ISSUE TITLE
taskService.complete Cannot delete or update a parent row

### ISSUE THREAD

**Issue by thl283406834** [Activiti/Activiti#3822]
**Activiti Version**
```
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter</artifactId>
            <version>7.1.0.M6</version>
        </dependency>
```

**BPMN 2.0**
```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn2:definitions xmlns:bpmn2="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="diagram_Process_1643166773888" targetNamespace="http://activiti.org/bpmn" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
  <bpmn2:process id="DEC" name="报关单" isExecutable="true">
    <bpmn2:extensionElements>
      <activiti:itradeForm xmlns:activiti="http://activiti.org/bpmn" value="{&#10;  &#34;column&#34;: {&#10;    &#34;layout&#34;: [&#10;      &#34;procDefName&#34;&#10;    ],&#10;    &#34;components&#34;: {&#10;      &#34;procDefName&#34;: {&#10;        &#34;label&#34;: &#34;bpmn.procDefName&#34;,&#10;        &#34;type&#34;: &#34;text&#34;,&#10;        &#34;model&#34;: &#34;procDefName&#34;&#10;      }&#10;    }&#10;  },&#10;  &#34;rules&#34;: {},&#10;  &#34;data&#34;: {&#10;    &#34;procDefName&#34;: &#34;&#34;&#10;  },&#10;  &#34;buttons&#34;: {&#10;    &#34;layout&#34;: [&#10;      &#34;search&#34;,&#10;      &#34;reset&#34;&#10;    ],&#10;    &#34;components&#34;: {&#10;      &#34;search&#34;: {&#10;        &#34;label&#34;: &#34;common.search&#34;,&#10;        &#34;value&#34;: &#34;Y&#34;&#10;      },&#10;      &#34;reset&#34;: {&#10;        &#34;type&#34;: &#34;-&#34;,&#10;        &#34;label&#34;: &#34;common.reset&#34;,&#10;        &#34;value&#34;: &#34;N&#34;&#10;      }&#10;    }&#10;  }&#10;}" />
      <activiti:itradeComponent xmlns:activiti="http://activiti.org/bpmn" value="DEC-COMPONENT" />
    </bpmn2:extensionElements>
    <bpmn2:startEvent id="Event_0lqa57p" name="开始">
      <bpmn2:outgoing>Flow_1oj4f8o</bpmn2:outgoing>
    </bpmn2:startEvent>
    <bpmn2:userTask id="Activity_09eskn2" name="审核人1" activiti:assignee="1381430594474393602">
      <bpmn2:extensionElements>
        <activiti:itradeForm value="{&#10;  &#34;column&#34;: {&#10;    &#34;layout&#34;: [&#10;      &#34;procDefName&#34;&#10;    ],&#10;    &#34;components&#34;: {&#10;      &#34;procDefName&#34;: {&#10;        &#34;label&#34;: &#34;bpmn.procDefName&#34;,&#10;        &#34;type&#34;: &#34;text&#34;,&#10;        &#34;model&#34;: &#34;procDefName&#34;&#10;      }&#10;    }&#10;  },&#10;  &#34;rules&#34;: {},&#10;  &#34;data&#34;: {&#10;    &#34;procDefName&#34;: &#34;&#34;&#10;  },&#10;  &#34;buttons&#34;: {&#10;    &#34;layout&#34;: [&#10;      &#34;search&#34;,&#10;      &#34;reset&#34;&#10;    ],&#10;    &#34;components&#34;: {&#10;      &#34;search&#34;: {&#10;        &#34;label&#34;: &#34;common.search&#34;,&#10;        &#34;value&#34;: &#34;Y&#34;&#10;      },&#10;      &#34;reset&#34;: {&#10;        &#34;type&#34;: &#34;-&#34;,&#10;        &#34;label&#34;: &#34;common.reset&#34;,&#10;        &#34;value&#34;: &#34;N&#34;&#10;      }&#10;    }&#10;  }&#10;}" />
        <activiti:itradeComponent value="DEC-COMPONENT" />
      </bpmn2:extensionElements>
    </bpmn2:userTask>
    <bpmn2:sequenceFlow id="Flow_1oj4f8o" sourceRef="Event_0lqa57p" targetRef="Activity_09eskn2" />
    <bpmn2:userTask id="Activity_1gghhlh" name="审核人2" activiti:assignee="1381430594474393602" />
    <bpmn2:sequenceFlow id="Flow_18ohs12" sourceRef="Activity_09eskn2" targetRef="Activity_1gghhlh" />
    <bpmn2:userTask id="Activity_0ippdg1" name="审核人3" activiti:assignee="1381430594474393602" />
    <bpmn2:sequenceFlow id="Flow_0fquqm8" sourceRef="Activity_1gghhlh" targetRef="Activity_0ippdg1" />
    <bpmn2:userTask id="Activity_0hkk278" name="审核人4" activiti:assignee="1381430594474393602" />
    <bpmn2:sequenceFlow id="Flow_1goimgq" sourceRef="Activity_0ippdg1" targetRef="Activity_0hkk278" />
    <bpmn2:endEvent id="Event_1b56cgl">
      <bpmn2:incoming>Flow_0sd4skw</bpmn2:incoming>
    </bpmn2:endEvent>
    <bpmn2:sequenceFlow id="Flow_0sd4skw" sourceRef="Activity_0hkk278" targetRef="Event_1b56cgl" />
  </bpmn2:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_DEC">
    <bpmndi:BPMNPlane id="BPMNPlane_DEC" bpmnElement="DEC">
      <bpmndi:BPMNEdge id="BPMNEdge_Flow_0sd4skw" bpmnElement="Flow_0sd4skw">
        <di:waypoint x="490" y="410" />
        <di:waypoint x="882" y="410" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="BPMNEdge_Flow_1goimgq" bpmnElement="Flow_1goimgq">
        <di:waypoint x="910" y="320" />
        <di:waypoint x="910" y="345" />
        <di:waypoint x="440" y="345" />
        <di:waypoint x="440" y="370" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="BPMNEdge_Flow_0fquqm8" bpmnElement="Flow_0fquqm8">
        <di:waypoint x="730" y="270" />
        <di:waypoint x="795" y="270" />
        <di:waypoint x="795" y="280" />
        <di:waypoint x="860" y="280" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="BPMNEdge_Flow_18ohs12" bpmnElement="Flow_18ohs12">
        <di:waypoint x="560" y="270" />
        <di:waypoint x="630" y="270" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="BPMNEdge_Flow_1oj4f8o" bpmnElement="Flow_1oj4f8o">
        <di:waypoint x="408" y="270" />
        <di:waypoint x="460" y="270" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="BPMNShape_Event_0lqa57p" bpmnElement="Event_0lqa57p">
        <dc:Bounds x="372" y="252" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_Activity_09eskn2" bpmnElement="Activity_09eskn2">
        <dc:Bounds x="460" y="230" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_Activity_1gghhlh" bpmnElement="Activity_1gghhlh">
        <dc:Bounds x="630" y="230" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_Activity_0ippdg1" bpmnElement="Activity_0ippdg1">
        <dc:Bounds x="860" y="240" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_Activity_0hkk278" bpmnElement="Activity_0hkk278">
        <dc:Bounds x="390" y="370" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="BPMNShape_Event_1b56cgl" bpmnElement="Event_1b56cgl">
        <dc:Bounds x="882" y="392" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn2:definitions>
```

**Trace Image**

![image](https://user-images.githubusercontent.com/57788607/153343761-ffd5a3d1-d742-49d6-bfd6-bc731e9b232d.png)

**JAVA Code**
```
    @Override
    public void doneTask(DoneTaskDTO doneTaskDTO) {
        Authentication.setAuthenticatedUserId(String.valueOf(getLoginUser()));

        Task task = taskService.createTaskQuery().taskId(doneTaskDTO.getTaskId()).singleResult();

        if (task == null) {
            throw new ServiceException(CommonConstants.PAGE_OVERDUE);
        }

        // 如果是代理人的任务
        if (DelegationState.PENDING.equals(task.getDelegationState())) {
            taskService.resolveTask(task.getId());
        }

        // 如果是候选人列表
        if (!StringUtils.hasText(task.getAssignee()) || !task.getAssignee().equals(String.valueOf(getLoginUserId()))) {
            taskService.claim(task.getId(), String.valueOf(getLoginUserId()));
        }

        BpmnModel bpmnModel = repositoryService.getBpmnModel(task.getProcessDefinitionId());
        Process process = bpmnModel.getMainProcess();
        Map<String, List<ExtensionElement>> processExtensionElements = process.getExtensionElements();
        List<ExtensionElement> processItradeFormList = processExtensionElements.get("itradeForm");

        FlowElement flowElement = process.getFlowElement(task.getTaskDefinitionKey());
        Map<String, List<ExtensionElement>> extensionElements = flowElement.getExtensionElements();
        List<ExtensionElement> itradeFormList = extensionElements.get("itradeForm");

        DoneTaskInfoDTO info = doneTaskDTO.getInfo();
        DoneTaskClickDTO click = info.getClick();

        if (itradeFormList != null && !itradeFormList.isEmpty()) {
            String value = itradeFormList.get(0).getAttributes().get("value").get(0).getValue();
            JSONObject form = JSON.parseObject(value);
            form.put("data", doneTaskDTO.getInfo().getFormData());
            form.put("buttons", null);
            taskService.addComment(task.getId(), task.getProcessInstanceId(), BpmnConstants.COMMENT_TYPE_FORM, form.toJSONString());
        } else if (processItradeFormList != null && !processItradeFormList.isEmpty()) {
            String value = processItradeFormList.get(0).getAttributes().get("value").get(0).getValue();
            JSONObject form = JSON.parseObject(value);
            form.put("data", doneTaskDTO.getInfo().getFormData());
            form.put("buttons", null);
            taskService.addComment(task.getId(), task.getProcessInstanceId(), BpmnConstants.COMMENT_TYPE_FORM, form.toJSONString());
        }

        taskService.addComment(task.getId(), task.getProcessInstanceId(), BpmnConstants.COMMENT_TYPE_CLICK, JSON.toJSONString(info.getClick()));

        Map<String, Object> transientVariables = new HashMap<>();
        transientVariables.put(BpmnConstants.COMMENT_TYPE_CLICK, click.getValue());

        taskService.complete(task.getId(), null, transientVariables);
    }
```
**ERROR MESSAGE on taskService.complete(task.getId(), null, transientVariables);**

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`itrade_bpmn`.`ACT_RU_VARIABLE`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`))
### The error may exist in org/activiti/db/mapping/entity/Execution.xml
### The error may involve org.activiti.engine.impl.persistence.entity.ExecutionEntityImpl.deleteExecution-Inline
### The error occurred while setting parameters
### SQL: delete from ACT_RU_EXECUTION where ID_ = ? and REV_ = ?
### Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`itrade_bpmn`.`ACT_RU_VARIABLE`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`))
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:196) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:209) ~[mybatis-3.5.7.jar:3.5.7]
	at org.activiti.engine.impl.db.DbSqlSession.flushDeleteEntities(DbSqlSession.java:906) ~[activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.db.DbSqlSession.flushDeletes(DbSqlSession.java:866) ~[activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:520) ~[activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:237) ~[activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:102) ~[activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:68) ~[activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-7.1.0.M6.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) [activiti-spring-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:35) [activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44) [activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) [activiti-engine-7.1.0.M6.jar:na]
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:198) [activiti-engine-7.1.0.M6.jar:na]
	at com.itrade.bpmn.service.impl.BpmnTodoServiceImpl.doneTask(BpmnTodoServiceImpl.java:197) [classes/:na]
	at com.itrade.bpmn.service.impl.BpmnTodoServiceImpl$$FastClassBySpringCGLIB$$673379e4.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at com.itrade.bpmn.service.impl.BpmnTodoServiceImpl$$EnhancerBySpringCGLIB$$717bbe32.doneTask(<generated>) [classes/:na]
	at com.itrade.bpmn.api.impl.BpmnTodoApiImpl.doneTask(BpmnTodoApiImpl.java:34) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at com.itrade.common.general.filter.ServiceRequestFilter.doFilterInternal(ServiceRequestFilter.java:35) [itrade-common-1.1.0-20220117.033610-10.jar:1.1.0-SNAPSHOT]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97) [spring-boot-actuator-2.3.12.RELEASE.jar:2.3.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`itrade_bpmn`.`ACT_RU_VARIABLE`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `ACT_RU_EXECUTION` (`ID_`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:na]
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59) ~[mybatis-3.5.7.jar:3.5.7]
	at com.sun.proxy.$Proxy108.execute(Unknown Source) ~[na:na]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.5.7.jar:3.5.7]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194) ~[mybatis-3.5.7.jar:3.5.7]
	... 78 common frames omitted
```

**All UserTask are the same, but the last UserTask which before [EndEvent] happend this error.**
**and Success without transientVariables (taskService.complete(task.getId()))**
**how to deal with it when i need transientVariables**

**Comment by OlderFeng** [comment]
I also had the same problem

**Comment by a350844866** [comment]
same problem, have you resloved this?

**Comment by NapChen** [comment]
you may reference to https://github.com/Activiti/Activiti/issues/4012 for detail
in my case, i handle this problem in process completed event listener, delete all variables when this listener triggered,it worked for me

```
@Slf4j
public class ActivitiProcessCompletedHandler extends ActivitiProcessDefaultHandler {
    public ActivitiProcessCompletedHandler() {
    }

    @Override
    public void handle(ProcessRuntimeEvent<ProcessInstance> runtimeEvent) {
        log.info("ActivitiProcessCompletedHandler triggered: " + runtimeEvent.getProcessInstanceId());
        String processInstanceId = runtimeEvent.getProcessInstanceId();
        new ActivitiHiProcessReasonUpdateCmd(processInstanceId, "完成").execute(Context.getCommandContext());
        // bugs:reference to https://github.com/Activiti/Activiti/issues/4012 or https://github.com/Activiti/Activiti/issues/3822
        // must clear all variables or throw exception:
        // java.sql.SQLIntegrityConstraintViolationException:
        // Cannot delete or update a parent row:
        // a foreign key constraint fails (XXX_SCHEMA_NAME.act_ru_variable, CONSTRAINT ACT_FK_VAR_EXE  FOREIGN KEY (EXECUTION_ID_) REFERENCES act_ru_execution (ID_))
        List<Execution> executions = runtimeService
                .createExecutionQuery()
                .processInstanceId(processInstanceId)
                .list();
        for (Execution execution : executions) {
            Map<String, Object> variables = runtimeService.getVariables(execution.getId());
            for (Map.Entry<String, Object> variable : variables.entrySet()) {
                log.info("delete variable: {}", variable.getKey());
                runtimeService.removeVariable(execution.getId(), variable.getKey());
            }
        }
    }
}
```

**Comment by GuoJing** [comment]
@NapChen hi, I had this issue too, but my solution is just to remove the TASK_ID value in the table `ru_variable`, and everything works. No need to delete all the variables.
