### ISSUE TITLE
taskService.complete() throws exception after Upgrade 5.21.0 > 7.3.0

### ISSUE THREAD

**Issue by flaviodonze** [Activiti/Activiti#3972]
After the update from 5.21.0 to 7.3.0 I get the following exception after calling:

`taskService.complete(taskId, variables);`

Is there some additional manual migration required? Seems like the execution parent is missing, but actually there should be no parent.

> ERROR: org.activiti.engine.impl.interceptor.CommandContext - Error while closing command context
> java.lang.NullPointerException: Cannot invoke "org.activiti.engine.delegate.DelegateExecution.isMultiInstanceRoot()" because the return value of "org.activiti.engine.delegate.DelegateExecution.getParent()" is null
> 	at org.activiti.engine.impl.bpmn.behavior.VariablesPropagator.propagate(VariablesPropagator.java:39)
> 	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.propagateVariablesToProcess(UserTaskActivityBehavior.java:282)
> 	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.trigger(UserTaskActivityBehavior.java:269)
> 	at org.activiti.engine.impl.agenda.TriggerExecutionOperation.run(TriggerExecutionOperation.java:53)
> 	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:77)
> 	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:61)
> 	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:46)
> 	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:52)
> 	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
> 	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:51)
> 	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
> 	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:49)
> 	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
> 	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:59)
> 	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:54)
> 	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:206)

**Comment by vnosach-clgx** [comment]
had same issue, anyone know how to solve it?
