### ISSUE TITLE
mutiinstance ArrayNode is not a Collection error

### ISSUE THREAD

**Issue by ming820214** [Activiti/Activiti#4159]
when I use activiti 7.1.0.M4 version，

"When i am setting the variables on process, it's being set as Array List which is of type collection. When i am trying to complete the task without passing any variable then it gets the variable from process and that time "userCollection" variable
value is ArrayNode and not ArrayList and ArrayNode is not type of Collection and because of that it fails."

the errors like below:

org.activiti.engine.ActivitiIllegalArgumentException: Variable memberList' is not a Collection
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveAndValidateCollection(MultiInstanceActivityBehavior.java:225) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveNrOfInstances(MultiInstanceActivityBehavior.java:184) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.bpmn.behavior.ParallelMultiInstanceBehavior.leave(ParallelMultiInstanceBehavior.java:107) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.bpmn.behavior.AbstractBpmnActivityBehavior.leave(AbstractBpmnActivityBehavior.java:55) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.trigger(UserTaskActivityBehavior.java:270) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.trigger(MultiInstanceActivityBehavior.java:157) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.agenda.TriggerExecutionOperation.run(TriggerExecutionOperation.java:38) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-7.1.0.M4.jar:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.10.RELEASE.jar:5.2.10.RELEASE]
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) ~[activiti-engine-7.1.0.M4.jar:na]
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:192) ~[activiti-engine-7.1.0.M4.jar:na]

and hitting an error in the engine in [MultiInstanceActivityBehavior.resolveAndValidateCollection](https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java)

How should I deal with it?

**Comment by zhaojda** [comment]
exm , I also encountered this problem, how did you solve it?
