### ISSUE TITLE
fix concurrent Sql Deadlock 

### ISSUE THREAD

**Issue by yangyu6** [Activiti/Activiti#4160]
≈activiti7 latest version
## Sql Deadlock problem during process concurrency

``` The error may involve org.activiti.engine.impl.persistence.entity.ExecutionEntityImpl.updateProcessInstanceLockTime-Inline
The error occurred while setting parameters
SQL: update ACT_RU_EXECUTION      set       LOCK_TIME_ = ?     where ID_ = ?       and (LOCK_TIME_ is null OR LOCK_TIME_ < ?)
Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.activiti.engine.impl.db.DbSqlSession.update(DbSqlSession.java:207)
	at org.activiti.engine.impl.persistence.entity.data.impl.MybatisExecutionDataManager.updateProcessInstanceLockTime(MybatisExecutionDataManager.java:326)
 ```

## reasons of problem

updateObjects The items in the map are unordered.

`org.activiti.engine.impl.db.DbSqlSession#determineUpdatedObjects` 

```
public void determineUpdatedObjects() {
    updatedObjects = new ArrayList<Entity>();
    Map<Class<?>, Map<String, CachedEntity>> cachedObjects = entityCache.getAllCachedEntities();
    for (Class<?> clazz : cachedObjects.keySet()) {

      Map<String, CachedEntity> classCache = cachedObjects.get(clazz);
      for (CachedEntity cachedObject : classCache.values()) {

        Entity cachedEntity = cachedObject.getEntity();
        
        if (!isEntityInserted(cachedEntity) && 
            (ExecutionEntity.class.isAssignableFrom(cachedEntity.getClass()) || !isEntityToBeDeleted(cachedEntity)) &&
            cachedObject.hasChanged() 
            ) {
          updatedObjects.add(cachedEntity);
        }
      }
    }
  }
```

`org.activiti.engine.impl.persistence.cache.EntityCacheImpl#cachedObjects`
```
public class EntityCacheImpl implements EntityCache {
  
  protected Map<Class<?>, Map<String, CachedEntity>> cachedObjects = new HashMap<Class<?>, Map<String,CachedEntity>>();
  
  @Override
  public CachedEntity put(Entity entity, boolean storeState) {
    Map<String, CachedEntity> classCache = cachedObjects.get(entity.getClass());
    if (classCache == null) {
      classCache = new HashMap<String, CachedEntity>();
      cachedObjects.put(entity.getClass(), classCache);
    }
    CachedEntity cachedObject = new CachedEntity(entity, storeState);
    classCache.put(entity.getId(), cachedObject);
    return cachedObject;
  }
```

**cachedObjects**.  
Inserting into the map is ordered, but the **hashmap** itself is unordered，leading to the disorder of **updateObjects**.
The sql is written out of order, causing deadlock

**Sql Deadlock problem during process concurrency**

### insert demo

Handle in entity dependency order .  EntityDependencyOrder.INSERT_ORDER

```
 protected void flushInserts() {
    
    if (insertedObjects.size() == 0) {
      return;
    }
  	
  	// Handle in entity dependency order
    for (Class<? extends Entity> entityClass : EntityDependencyOrder.INSERT_ORDER) {
      if (insertedObjects.containsKey(entityClass)) {
        flushInsertEntities(entityClass, insertedObjects.get(entityClass).values());
      	insertedObjects.remove(entityClass);
      }
    }
    
    // Next, in case of custom entities or we've screwed up and forgotten some entity
    if (insertedObjects.size() > 0) {
	    for (Class<? extends Entity> entityClass : insertedObjects.keySet()) {
      	flushInsertEntities(entityClass, insertedObjects.get(entityClass).values());
	    }
    }
    
    insertedObjects.clear();
  }
```

## fix

1.org.activiti.engine.impl.persistence.cache.EntityCacheImpl#cachedObjects

```
 public class FixEntityCacheImpl extends EntityCacheImpl {

    public FixEntityCacheImpl(){
        cachedObjects = new TreeMap<>(
                Comparator.comparingInt(o -> EntityDependencyOrder.INSERT_ORDER.indexOf(o))
        );
    }

    @Override
    public CachedEntity put(Entity entity, boolean storeState) {
        Map<String, CachedEntity> classCache = cachedObjects.computeIfAbsent(entity.getClass(), k -> new TreeMap<>());
        CachedEntity cachedObject = new CachedEntity(entity, storeState);
        classCache.put(entity.getId(), cachedObject);
        return cachedObject;
    }


}
```

2.AbstractProcessEngineConfigurator#beforeInit

```
@Override
    public void beforeInit(ProcessEngineConfigurationImpl configuration) {
configuration.setCustomSessionFactories(Lists.newArrayList(new GenericManagerFactory(EntityCache.class, FixEntityCacheImpl.class)));
       
}
```

**Comment by yangyu6** [comment]
update code 

org.activiti.engine.impl.db.DbSqlSession#flushUpdates

```
protected void flushUpdates() {
    for (Entity updatedObject : updatedObjects) {
      String updateStatement = dbSqlSessionFactory.getUpdateStatement(updatedObject);
      updateStatement = dbSqlSessionFactory.mapStatement(updateStatement);

      if (updateStatement == null) {
        throw new ActivitiException("no update statement for " + updatedObject.getClass() + " in the ibatis mapping files");
      }

      log.debug("updating: {}", updatedObject);
      int updatedRecords = sqlSession.update(updateStatement, updatedObject);
      if (updatedRecords == 0) {
        throw new ActivitiOptimisticLockingException(updatedObject + " was updated by another transaction concurrently");
      }

      // See https://activiti.atlassian.net/browse/ACT-1290
      if (updatedObject instanceof HasRevision) {
        ((HasRevision) updatedObject).setRevision(((HasRevision) updatedObject).getRevisionNext());
      }

    }
    updatedObjects.clear();
  }

```

**Comment by yangyu6** [comment]
Please accept. This is the first time I ask a question at github. Please correct me if there is something wrong
