### ISSUE TITLE
Do event subprocesses started by a message event work?

### ISSUE THREAD

**Issue by tf-tol** [Activiti/Activiti#4165]
According to the Activiti 6 documentation, event subprocesses can be triggered by a message start event even at the subprocess scope.
https://www.activiti.org/userguide/#bpmnEventSubprocess

> As already stated, an Event Sub-Process can also be added to an embedded subprocess. 

I have an event subprocess with a message start event inside a subprocess, and am trying to trigger the message start event, as follows:

```
      runtimeService.messageEventReceived(
        "EVENT_SUBPROC_START",
        subprocess.getId()
      );
```
(where `subprocess` is the subprocess scope immediately enclosing the event subprocess)

However, I get error `Execution with id ... does not have a subscription to a message event with name '<message name>'`:

```
2022-12-01T19:54:46.174Z - [sid=] - [rid=] - [Async-Task-1] ERROR org.activiti.engine.impl.interceptor.CommandContext - [method=] - [url=] - Error while closing command context
org.activiti.engine.ActivitiException: Execution with id 'c0237d32-71af-11ed-a5ad-bcd07409067d' does not have a subscription to a message event with name 'EVENT_SUBPROC_START'
  at org.activiti.engine.impl.cmd.MessageEventReceivedCmd.execute(MessageEventReceivedCmd.java:78) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.cmd.MessageEventReceivedCmd.execute(MessageEventReceivedCmd.java:34) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.cmd.NeedsActiveExecutionCmd.execute(NeedsActiveExecutionCmd.java:53) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:37) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:78) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-6.0.0.jar:6.0.0]
  at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.21.jar:5.3.21]
  at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) ~[activiti-engine-6.0.0.jar:6.0.0]
  at org.activiti.engine.impl.RuntimeServiceImpl.messageEventReceived(RuntimeServiceImpl.java:470) ~[activiti-engine-6.0.0.jar:6.0.0]
```

I'm pretty sure my BPM is correctly defined, as I have compared with event subprocess unit test XMLs in the Activiti codebase:

```
  <message id="EVENT_SUBPROC_START" name="EVENT_SUBPROC_START"></message>
  <process id="process" isExecutable="true">
    ...
      <subProcess id="subprocess" name="subprocess">
        <subProcess id="event-subprocess" name="event subprocess" triggeredByEvent="true">
          <startEvent id="EVENT_SUBPROC_START" name="EVENT_SUBPROC_START" activiti:isInterrupting="true">
            <messageEventDefinition messageRef="EVENT_SUBPROC_START"></messageEventDefinition>
          </startEvent>
          ... other elements ...
        </subProcess>
      </subProcess>
      ...
 </process>    
```

I am doing `runtimeService` queries and checking the database and noticed the following:
- No event for the event subprocess' message start event in the `ACT_RU_EVENT_SUBSCR` table (whereas intermediate catching message events appear there)
- No Execution for the event subprocess in the `ACT_RU_EXECUTION` table (whereas normal/non-event subprocesses appear there)

In trying to google an answer I ran into the following links:
https://github.com/Activiti/Activiti/issues/1638 (on timer start events in event subprocess)
https://github.com/Activiti/Activiti/issues/1639 (on signal start events in event subprocess)
which says that timer and signal start events in event subprocesses don't work ... **despite the documentation saying that it is supported?** Could anybody clarify whether event subprocesses -- in an embedded subprocess -- really works or not?

**Comment by ladislav-lencucha-adastra** [comment]
Same issue here. Did you manage to somehow solve this problem? To me, it looks like only boundaries messages work...
