### ISSUE TITLE
使用activiti过程中一个非常奇怪的问题

### ISSUE THREAD

**Issue by chengwenking** [Activiti/Activiti#4411]
我们一个项目结合了activit，刚开始使用的版本是6.0.0，无排他网关流程使用是正常的，没有出现问题。但是上线了之后，出现了排他网关和多分支的判断，然后就出现了运行一两天后，有的流程实例会在网关判断时失效，无法走到后续流程，导致实例直接结束；但是手动去拖动修改一下流程图，又能正常的创建实例和执行任务。后续改为使用7.1.0.M2版本，刚开始也没有问题，但是上线运行一段时间后又出现了改问题，并且报错的内容如下：
处理任务[2308301417316404]异常，异常信息为：java.lang.NullPointerException
	at orgine.powerprc.service.overt.process.instance.listener.MultiInstanceCommitUserListener.notify(MultiInstanceCommitUserListener.java:108)
	at org.activiti.engine.impl.delegate.invocation.ExecutionListenerInvocation.invoke(ExecutionListenerInvocation.java:34)
	at org.activiti.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:35)
	at org.activiti.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.notify(ClassDelegate.java:109)
	at org.activiti.engine.impl.bpmn.listener.ListenerNotificationHelper.executeExecutionListeners(ListenerNotificationHelper.java:77)
	at org.activiti.engine.impl.agenda.AbstractOperation.executeExecutionListeners(AbstractOperation.java:81)
	at org.activiti.engine.impl.agenda.AbstractOperation.executeExecutionListeners(AbstractOperation.java:71)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeMultiInstanceSynchronous(ContinueProcessOperation.java:167)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:99)
	at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:66)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:196)
	at orgine.powerprc.service.overt.process.task.helper.ProcessConfigHelper.refreshProcessTask(ProcessConfigHelper.java:404)
	at orgine.powerprc.service.overt.process.task.service.impl.ProcessTaskServiceImpl.completeTask(ProcessTaskServiceImpl.java:304)
	at orgine.powerprc.service.overt.process.task.controller.ProcessTaskController.completeTask(ProcessTaskController.java:135)
	at sun.reflect.GeneratedMethodAccessor1031.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at orgine.powermop.service.start.manager.core.handler.AbstractHandler.invoke(AbstractHandler.java:42)
	at orgine.powermop.service.start.manager.core.handler.ExecuteCallHandler.handler(ExecuteCallHandler.java:53)
	at orgine.powermop.service.start.manager.core.chain.ConsumerHandlerChain.doHandler(ConsumerHandlerChain.java:39)
	at orgine.powermop.service.start.manager.core.handler.RequestConvertHandler.handler(RequestConvertHandler.java:126)
	at orgine.powermop.service.start.manager.core.chain.ConsumerHandlerChain.doHandler(ConsumerHandlerChain.java:39)
	at orgine.powermop.service.start.manager.core.handler.PluginBeforeHandler.handler(PluginBeforeHandler.java:59)
	at orgine.powermop.service.start.manager.core.chain.ConsumerHandlerChain.doHandler(ConsumerHandlerChain.java:39)
	at orgine.powermop.service.start.manager.core.handler.ParamResolveHandler.handler(ParamResolveHandler.java:73)
	at orgine.powermop.service.start.manager.core.chain.ConsumerHandlerChain.doHandler(ConsumerHandlerChain.java:39)
	at orgine.powermop.service.start.manager.core.DefaultGatewayService.doPost(DefaultGatewayService.java:91)
	at orgine.powermop.service.start.manager.core.DefaultGatewayService.doPost(DefaultGatewayService.java:40)
	at orgine.powermop.service.start.manager.web.controller.EntranceController.gateway(EntranceController.java:64)
	at sun.reflect.GeneratedMethodAccessor616.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ooooo-youwillsee** [comment]
提前保留上下文相关信息，或者查询使用 CommandConfig  contextReusePossible = false

**Comment by ginxoag** [comment]
请问这个问题解决了吗？我们项目在使用activiti5.22的时候也碰到了一样的问题，查看日志正常情况是
`23-12-12 08:11:56.955 [http-nio-xxxx-exec-5] DEBUG o.a.engine.impl.bpmn.behavior.BpmnActivityBehavior Leaving activity 'b'
23-12-12 08:11:56.955 [http-nio-xxxx-exec-5] DEBUG com.shys.workflow.listener.GlobalEventListener envent type is ========>ACTIVITY_COMPLETED
23-12-12 08:11:56.955 [http-nio-xxxx-exec-5] DEBUG o.a.engine.impl.history.DefaultHistoryManager Current history level: FULL, level required: ACTIVITY
23-12-12 08:11:56.955 [http-nio-xxxx-exec-5] DEBUG com.shys.workflow.listener.GlobalEventListener envent type is ========>HISTORIC_ACTIVITY_INSTANCE_ENDED`
错误情况是
`23-12-12 16:01:38.292 [http-nio-xxxx-exec-5] DEBUG o.a.engine.impl.bpmn.behavior.BpmnActivityBehavior Leaving activity 'b'
23-12-12 16:01:38.292 [http-nio-xxxx-exec-5] DEBUG o.a.engine.impl.bpmn.behavior.BpmnActivityBehavior No outgoing sequence flow found for b. Ending execution.
23-12-12 16:01:38.292 [http-nio-xxxx-exec-5] DEBUG o.a.engine.impl.history.DefaultHistoryManager Current history level: FULL, level required: ACTIVITY
23-12-12 16:01:38.292 [http-nio-xxxx-exec-5] DEBUG com.shys.workflow.listener.GlobalEventListener envent type is ========>HISTORIC_ACTIVITY_INSTANCE_ENDED
23-12-12 16:01:38.292 [http-nio-xxxx-exec-5] DEBUG com.shys.workflow.listener.GlobalEventListener envent type is ========>ACTIVITY_COMPLETED
23-12-12 16:01:38.292 [http-nio-xxxx-exec-5] DEBUG com.shys.workflow.listener.GlobalEventListener envent type is ========>PROCESS_COMPLETED`
目前定位到activiti5的源码就是activiti判断结点没有出线直接结束了流程，而且也是模型重新发布了之后问题就没有了。
