### ISSUE TITLE
Getting ActivitiException objectMapper.readValue must not null error after upgrading from v7 to v8

### ISSUE THREAD

**Issue by vicehope** [Activiti/Activiti#4468]
After upgrading Activiti from v7 to v8 in my service, I am encountering exceptions every time the
org.activiti.engine.impl.RuntimeServicelmpl.startProcessInstanceByKey method is invoked.I would appreciate some assistance in gaining insight into the problem.

```
org.activiti.engine.ActivitiException: objectMapper.readValue ..:class.java
) must not be null at
org.activiti.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior java:119)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:230)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:168)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation,java:117)
at org.activiti.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:82)
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:77)
at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:61)
at org.activiti.engine.impl.interceptor.Commandinvoker.execute(CommandInvoker.java:46)
at org.activiti.engine.impl.interceptor. TransactionContextInterceptor.execute(TransactionContextinterceptor.java:52) at org.activiti.engine.impl.interceptor.CommandContextinterceptor.execute(CommandContextInterceptor.java:63) at org.activiti.spring. Spring Transactioninterceptor$1.dolnTransaction(Spring Transactioninterceptor java:51) at org.springframework.transactio support. TransactionTemplate.execute (TransactionTemplate.java:140) at org.activiti.spring.Spring TransactionInterceptor.execute (Spring TransactionInterceptor.java:49) at org.activiti.engine.impl.interceptor. Loginterceptor.execute (LogInterceptor.java:33) at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:59) at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorimpl.java:54) at org.activiti engine.impl. RuntimeServicelmp!.startProcessInstanceByKey(RuntimeServicelmpljava:91)
```

**Comment by vicehope** [comment]
To supplement and giving more context to the problem, this cause of the error is a result of null value in a property called inBoundVariables of the integrationContext which is passed in a input parameter of the Connector interface. 

The connector is triggered by function call to RuntimeService.startProcessInstanceByKey(processDefintionKey, variables), the non-empty variable is being passed in to the function as HashMap. Somehow, the value in the variables has lost in the transit and received a null value at the connector end.

**Comment by erdemedeiros** [comment]
Hi @vicehope, have you upgrade your project to Spring Boot 3.1.x and JDK 17 as well? Do you have the possibility to create a small reproducer for this?

**Comment by vicehope** [comment]
@erdemedeiros Hi thanks for your reply. Yes, I have upgraded to Spring Boot 3.1.2 and Java 17 using activiti version 8.0.0
I created a simple reproducer based from the activiti example, link is here: https://github.com/vicehope/activiti-null-issue/blob/main/activiti-api-basic-full-example-bean/src/main/java/org/activiti/examples/DemoApplication.java

If you execute the application, you should see the log output of the content string as an inbound variable are null. Below is the errors that I got. Thanks for the help.

```
2023-11-17T10:46:14.505+08:00  INFO 8824 --- [           main] org.activiti.examples.DemoApplication    : Started DemoApplication in 7.278 seconds (process running for 7.699)
2023-11-17T10:46:14.508+08:00  INFO 8824 --- [           main] org.activiti.examples.SecurityUtil       : > Logged in as: system
2023-11-17T10:46:14.533+08:00  INFO 8824 --- [           main] org.activiti.examples.DemoApplication    : > Available Process definitions: 2
2023-11-17T10:46:14.537+08:00  INFO 8824 --- [           main] org.activiti.examples.DemoApplication    : 	 > Process definition: ProcessDefinition{id='categorizeHumanProcess:1:78fed531-84f3-11ee-806b-acde48001122', name='categorizeHumanProcess', key='categorizeHumanProcess', description='null', formKey='null', version=1}
2023-11-17T10:46:14.537+08:00  INFO 8824 --- [           main] org.activiti.examples.DemoApplication    : 	 > Process definition: ProcessDefinition{id='simpleProcess:1:78ff7172-84f3-11ee-806b-acde48001122', name='simpleProcess', key='simpleProcess', description='null', formKey='null', version=1}
2023-11-17T10:46:15.507+08:00  INFO 8824 --- [   scheduling-1] org.activiti.examples.SecurityUtil       : > Logged in as: system
2023-11-17T10:46:15.508+08:00  INFO 8824 --- [   scheduling-1] org.activiti.examples.DemoApplication    : > Starting process to process content: {content=Simple String} at 17-11-23 10:46:15
2023-11-17T10:46:15.651+08:00  INFO 8824 --- [   scheduling-1] org.activiti.examples.DemoApplication    : null
2023-11-17T10:46:15.651+08:00  INFO 8824 --- [   scheduling-1] org.activiti.examples.DemoApplication    : Content: null
```

**Comment by codesaaz** [comment]
@vicehope  did you find any answer to this problem as I am also getting the same error on the same activiti provided example.
