### ISSUE TITLE
Encountering "Transaction synchronization is not active" error when a timer job is executed

### ISSUE THREAD

**Issue by vicehope** [Activiti/Activiti#4512]
Activiti version: 8.0.0
Spring Boot: 3

```
java.lang.IllegalStateException: Transaction synchronization is not active
	at org.springframework.transaction.support.TransactionSynchronizationManager.registerSynchronization(TransactionSynchronizationManager.java:277)
	at org.activiti.spring.SpringTransactionContext.addTransactionListener(SpringTransactionContext.java:79)
	at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.hintAsyncExecutor(DefaultJobManager.java:428)
	at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.triggerExecutorIfNeeded(DefaultJobManager.java:103)
	at org.activiti.engine.impl.asyncexecutor.DefaultJobManager.moveTimerJobToExecutableJob(DefaultJobManager.java:142)
	at org.activiti.engine.impl.asyncexecutor.AcquireTimerJobsRunnable$1.execute(AcquireTimerJobsRunnable.java:68)
	at org.activiti.engine.impl.asyncexecutor.AcquireTimerJobsRunnable$1.execute(AcquireTimerJobsRunnable.java:63)
	at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:41)
```

Could anyone advise me on the correct configuration in Spring Boot?

**Comment by isuri1** [comment]
@vicehope were you able to resolve this issue?

**Comment by breezefaith** [comment]
@vicehope were you able to resolve this issue?

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢
