### ISSUE TITLE
activiti6.0.0 module activiti5-engine: Could not set property 'lockOwner' of 'class org.activiti5.engine.impl.persistence.entity.TimerJobEntity'

### ISSUE THREAD

**Issue by marius56-discovery** [Activiti/Activiti#4619]
Class org.activiti5.engine.impl.persistence.entity.TimerJobEntity doesn't define below properties listed in 
modules\activiti5-engine\src\main\resources\org\activiti5\db\mapping\entity\TimerJob.xml

```
<result property="lockOwner" column="LOCK_OWNER_" jdbcType="VARCHAR" />
<result property="lockExpirationTime" column="LOCK_EXP_TIME_" jdbcType="TIMESTAMP" />
```

This results in below error:
```

2024-03-22 22:31:36 ERROR org.activiti.engine.impl.interceptor.CommandContext - masked exception in command context. for root cause, see below as it will be rethrown later.: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.reflection.ReflectionException: Could not set property 'lockOwner' of 'class org.activiti5.engine.impl.persistence.entity.TimerJobEntity' with value 'edd3be11-afa0-4c0b-a458-361107b109a6' Cause: org.apache.ibatis.reflection.ReflectionException: There is no setter for property named 'lockOwner' in 'class org.activiti5.engine.impl.persistence.entity.TimerJobEntity'
### The error may exist in org/activiti5/db/mapping/entity/TimerJob.xml
### The error may involve org.activiti5.engine.impl.persistence.entity.TimerJobEntity.selectTimerJobsByExecutionId
### The error occurred while handling results
### SQL: select *   from ACT_RU_TIMER_JOB J   where J.EXECUTION_ID_ = ?
### Cause: org.apache.ibatis.reflection.ReflectionException: Could not set property 'lockOwner' of 'class org.activiti5.engine.impl.persistence.entity.TimerJobEntity' with value 'edd3be11-afa0-4c0b-a458-361107b109a6' Cause: org.apache.ibatis.reflection.ReflectionException: There is no setter for property named 'lockOwner' in 'class org.activiti5.engine.impl.persistence.entity.TimerJobEntity'
	at deployment.frontline-transfers.war//org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at deployment.frontline-transfers.war//org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at deployment.frontline-transfers.war//org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at deployment.frontline-transfers.war//org.activiti5.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:397)
	at deployment.frontline-transfers.war//org.activiti5.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:388)
	at deployment.frontline-transfers.war//org.activiti5.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:383)
	at deployment.frontline-transfers.war//org.activiti5.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:360)
	at deployment.frontline-transfers.war//org.activiti5.engine.impl.persistence.entity.TimerJobEntityManager.findTimerJobsByExecutionId(TimerJobEntityManager.java:62)
```

**Comment by krimokrimo007** [comment]
Hello,
do you have any update on this issue ?
I'm facing it.
Regards,
