### ISSUE TITLE
Invalid authenticated principal  无效的验证主体

### ISSUE THREAD

**Issue by jack00000** [Activiti/Activiti#4733]
java.lang.SecurityException: Invalid authenticated principal
	at org.activiti.api.runtime.shared.security.AbstractSecurityManager.securityException(AbstractSecurityManager.java:61)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.activiti.api.runtime.shared.security.AbstractSecurityManager.getAuthenticatedUserId(AbstractSecurityManager.java:43)
	at org.activiti.runtime.api.event.impl.ToTaskCompletedConverter.from(ToTaskCompletedConverter.java:40)
	at org.activiti.runtime.api.event.internal.TaskCompletedListenerDelegate.onEvent(TaskCompletedListenerDelegate.java:42)
	at org.activiti.engine.delegate.event.impl.ActivitiEventSupport.dispatchEvent(ActivitiEventSupport.java:108)
	at org.activiti.engine.delegate.event.impl.ActivitiEventSupport.dispatchEvent(ActivitiEventSupport.java:101)
	at org.activiti.engine.delegate.event.impl.ActivitiEventDispatcherImpl.dispatchEvent(ActivitiEventDispatcherImpl.java:70)
	at org.activiti.engine.impl.cmd.AbstractCompleteTaskCmd.executeTaskComplete(AbstractCompleteTaskCmd.java:61)
	at org.activiti.engine.impl.cmd.CompleteTaskCmd.execute(CompleteTaskCmd.java:75)
	at org.activiti.engine.impl.cmd.CompleteTaskCmd.execute(CompleteTaskCmd.java:26)
	at org.activiti.engine.impl.cmd.NeedsActiveTaskCmd.execute(NeedsActiveTaskCmd.java:60)
	at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:41)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:82)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:61)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:46)
	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:52)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:51)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:49)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:59)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:54)
	at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:200)

**Comment by caowolf** [comment]
没有使用 spring-security 吗，这个要登录的，如果没有使用官方推荐的，就自己编个

![image](https://github.com/user-attachments/assets/ac7fa37e-057d-4811-b580-6e712dcfe3ff)

**Comment by QQ853695231** [comment]
我也是报这个错，不想用spring-security,这个随便编用户和对应的权限，对流程的流转有影响吗？ @caowolf
