### ISSUE TITLE
Activiti kickstart deploy on alfresco 5

### ISSUE THREAD

**Issue by HansDeBal** [Activiti/Activiti#491]
Hi,

I set up an alfresco dev-environment using alfresco SDK 2.0.0 and I am using it to locally run an alfresco 5 instance. When I use the eclipse activiti plugin and I try to deploy a kickstart-project using the CMIS export target to the local instance, i am getting the following error:

```
org.apache.chemistry.opencmis.commons.exceptions.CmisRuntimeException: null
    at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.convertStatusCode(AbstractAtomPubService.java:487)
    at org.apache.chemistry.opencmis.client.bindings.spi.atompub.AbstractAtomPubService.post(AbstractAtomPubService.java:629)
    at org.apache.chemistry.opencmis.client.bindings.spi.atompub.ObjectServiceImpl.createDocument(ObjectServiceImpl.java:119)
    at org.apache.chemistry.opencmis.client.runtime.SessionImpl.createDocument(SessionImpl.java:751)
    at org.apache.chemistry.opencmis.client.runtime.FolderImpl.createDocument(FolderImpl.java:95)
    at org.apache.chemistry.opencmis.client.runtime.FolderImpl.createDocument(FolderImpl.java:469)
    at org.activiti.designer.kickstart.eclipse.navigator.CmisUtil.uploadProcess(CmisUtil.java:214)
    at org.activiti.designer.kickstart.eclipse.ui.wizard.diagram.ExportKickstartProcessWizard.exportProcess(ExportKickstartProcessWizard.java:189)
    at org.activiti.designer.kickstart.eclipse.ui.wizard.diagram.ExportKickstartProcessWizard$1.run(ExportKickstartProcessWizard.java:88)
    at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by BenS89** [comment]
Also on Stackoverflow: http://stackoverflow.com/questions/35174368/activiti-kickstart-deploy-on-alfresco-5-with-cmis

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
