### ISSUE TITLE
Resources not found (images) when generating diagram in an OSGi environment and felixinstall

### ISSUE THREAD

**Issue by cheleb** [Activiti/Activiti#505]
In an OSGi wisdom [0](http://wisdom-framework.org/) extension [1](https://github.com/cheleb/wisdom-activiti) during process import, the diagram generation leads to a resource not found **when felix-fileinstall load/reload the process bundle**.

1)The changes in this pull request fixes this issue: https://github.com/Activiti/Activiti/pull/485
2) Applying a fragment host to export org.activiti.icons from bundle org.activiti.image also fixes this issue: https://github.com/cheleb/wisdom-activiti/blob/develop/wisdom-activiti-patch/pom.xml

`23:27:40.276 [FelixFrameworkWiring] INFO  o.a.e.i.b.d.BpmnDeployer - Processing resource OSGI-INF/activiti/SignUp.bpmn
23:27:41.735 [FelixFrameworkWiring] WARN  o.a.e.i.b.d.BpmnDeployer - Error while generating process diagram, image will not be stored in repository
java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(ImageIO.java:1348) ~[na:1.7.0_55]
    at org.activiti.image.impl.DefaultProcessDiagramCanvas.initialize(DefaultProcessDiagramCanvas.java:220) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramCanvas.<init>(DefaultProcessDiagramCanvas.java:171) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.initProcessDiagramCanvas(DefaultProcessDiagramGenerator.java:846) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.generateProcessDiagram(DefaultProcessDiagramGenerator.java:473) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.generateDiagram(DefaultProcessDiagramGenerator.java:403) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.generateDiagram(DefaultProcessDiagramGenerator.java:425) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.bpmn.deployer.BpmnDeployer.deploy(BpmnDeployer.java:130) ~[org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.persistence.deploy.DeploymentManager.deploy(DeploymentManager.java:50) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:103) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:37) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.RepositoryServiceImpl.deploy(RepositoryServiceImpl.java:78) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.repository.DeploymentBuilderImpl.deploy(DeploymentBuilderImpl.java:156) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.osgi.Extender.checkBundle(Extender.java:224) [org.activiti.osgi-5.17.0.jar:5.17.0]
    at org.activiti.osgi.Extender.bundleChanged(Extender.java:154) [org.activiti.osgi-5.17.0.jar:5.17.0]
    at org.activiti.osgi.Extender.addingBundle(Extender.java:107) [org.activiti.osgi-5.17.0.jar:5.17.0]
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:467) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:414) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443) [org.apache.felix.framework-4.4.1.jar:na]
    at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:869) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:790) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:515) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4429) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.StatefulResolver.fireResolvedEvents(StatefulResolver.java:1126) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.StatefulResolver.resolve(StatefulResolver.java:439) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3993) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix$RefreshHelper.restart(Felix.java:4911) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.refreshPackages(Felix.java:4148) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.FrameworkWiringImpl.run(FrameworkWiringImpl.java:178) [chameleon-core-1.10.3.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
23:27:41.735 [FelixFrameworkWiring] INFO  o.a.e.i.b.d.BpmnDeployer - Processing resource OSGI-INF/activiti/ValidateEntite.bpmn
23:27:41.786 [FelixFrameworkWiring] WARN  o.a.e.i.b.d.BpmnDeployer - Error while generating process diagram, image will not be stored in repository
java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(ImageIO.java:1348) ~[na:1.7.0_55]
    at org.activiti.image.impl.DefaultProcessDiagramCanvas.initialize(DefaultProcessDiagramCanvas.java:220) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramCanvas.<init>(DefaultProcessDiagramCanvas.java:171) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.initProcessDiagramCanvas(DefaultProcessDiagramGenerator.java:846) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.generateProcessDiagram(DefaultProcessDiagramGenerator.java:473) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.generateDiagram(DefaultProcessDiagramGenerator.java:403) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.image.impl.DefaultProcessDiagramGenerator.generateDiagram(DefaultProcessDiagramGenerator.java:425) ~[org.activiti.image.generator-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.bpmn.deployer.BpmnDeployer.deploy(BpmnDeployer.java:130) ~[org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.persistence.deploy.DeploymentManager.deploy(DeploymentManager.java:50) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:103) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:37) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.RepositoryServiceImpl.deploy(RepositoryServiceImpl.java:78) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.engine.impl.repository.DeploymentBuilderImpl.deploy(DeploymentBuilderImpl.java:156) [org.activiti.engine-5.17.0.jar:5.17.0]
    at org.activiti.osgi.Extender.checkBundle(Extender.java:224) [org.activiti.osgi-5.17.0.jar:5.17.0]
    at org.activiti.osgi.Extender.bundleChanged(Extender.java:154) [org.activiti.osgi-5.17.0.jar:5.17.0]
    at org.activiti.osgi.Extender.addingBundle(Extender.java:107) [org.activiti.osgi-5.17.0.jar:5.17.0]
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:467) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:414) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.apache.felix.framework-4.4.1.jar:na]
    at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:443) [org.apache.felix.framework-4.4.1.jar:na]
    at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:869) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:790) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:515) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4429) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.StatefulResolver.fireResolvedEvents(StatefulResolver.java:1126) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.StatefulResolver.resolve(StatefulResolver.java:439) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3993) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix$RefreshHelper.restart(Felix.java:4911) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.Felix.refreshPackages(Felix.java:4148) [chameleon-core-1.10.3.jar:na]
    at org.apache.felix.framework.FrameworkWiringImpl.run(FrameworkWiringImpl.java:178) [chameleon-core-1.10.3.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]`

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
