### ISSUE TITLE
NPE on engine.getTaskService().createTaskQuery() (conversation moved from developer forum)

### ISSUE THREAD

**Issue by markvt78** [Activiti/Activiti#715]
Original Post:

NPE on engine.getTaskService().createTaskQuery()
Unfollow this thread 
NPE on engine.getTaskService().createTaskQuery()

Hi,

We are experiencing a NPE on making this activity query call:

engine.getTaskService().createTaskQuery().taskId(taskId).includeProcessVariables().singleResult();

This only happens very occasionally and we have not found a way to reproduce the error. Nether occasion has been during any heavy load though both occasions have been at the same point in the BPMN where two parallel flows are executing a task each before entering an inclusive gateway. What we see is this error on the first task:
### Cause: java.lang.NullPointerException

org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException

at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23) ~[mybatis-3.2.5.jar:3.2.5]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:107) ~[mybatis-3.2.5.jar:3.2.5]
at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98) ~[mybatis-3.2.5.jar:3.2.5]
at org.activiti.engine.impl.db.DbSqlSession.selectListWithRawParameterWithoutFilter(DbSqlSession.java:426) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.persistence.entity.TaskEntityManager.findTasksAndVariablesByQueryCriteria(TaskEntityManager.java:139) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.TaskQueryImpl.executeList(TaskQueryImpl.java:930) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.AbstractQuery.executeSingleResult(AbstractQuery.java:158) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.AbstractQuery.execute(AbstractQuery.java:141) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-5.16.1.jar:5.16.1]
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.1.3.RELEASE.jar:4.1.3.RELEASE]
at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) ~[activiti-engine-5.16.1.jar:5.16.1]
at org.activiti.engine.impl.AbstractQuery.singleResult(AbstractQuery.java:104) ~[activiti-engine-5.16.1.jar:5.16.1]

and 1/10th of a second later the other task correctly makes this query call and continues on while the first leg is left in as stalled state and never reaches the gateway.

We have looked at past forum posts and note that it seems very similar to an old bug fixed in version 5.13 (while we are on a much later version 5.17) :

https://forums.activiti.org/content/npe-variables-get-processinstance-loaded-processinstancequery

That particular bug raised was on a createProcessInstanceQuery() while we are using a taskQuery. Is it possible the bug was fixed only for processInstance queries? (The old link to the fix is no longer available).

Can you shed any light on what this issue might be and why it could be happening so infrequently?

For now it seems that our only workaround is a crude one - wrapping this call in a try/catch, waiting and then retrying a specific number of times before failing

**Comment by markvt78** [comment]
HI erikwinlof,

Thanks for getting back to us. I can provide an anonymised version of the bpmn. Will that do for now? It may take us a bit longer to get a unit test to you.

Thanks

**Comment by erikwinlof** [comment]
Hi again! 
Please give the unit test a try with the anonymized version if possible.
Cheers, Erik

**Comment by markvt78** [comment]
Hi Erik,

Please find attached anonymized BPMN. I did run the unit test you linked and it runs fine. 

The point at which we see the issue is at the point in the process when the two parallel legs run their respective Task 10 tasks. Each of these tasks make the a call to the same Java class (wrapped in an @Transactional) and in this class we call the:

engine.getTaskService().createTaskQuery().taskId(taskId).includeProcessVariables().singleResult();

Which is where we see the NPE posted. As previously stated, we have done thousands of runs and only hit this issue twice. It should be noted also that in the previous task (Task 9) we are doing a 

engine.getRuntimeService().removeVariable(processId, varName);

just in case you think that is relevant.

**Comment by markvt78** [comment]
I don't have permission to add the file so the anonymised bpmn is in my forK:

https://github.com/markvt78/Activiti/blob/master/tooling/archetypes/activiti-archetype-unittest/src/main/resources/archetype-resources/src/test/resources/MYBPMN.bpmn

**Comment by markvt78** [comment]
Hi Erik,

Any update on this?

Thanks,

Mark

**Comment by erikwinlof** [comment]
Hi. 

No I haven't had the time yet :-( will get back as soon as I have. 

Cheers

**Comment by markvt78** [comment]
No problem thanks Erik

**Comment by markvt78** [comment]
Hi Erik,

Did you get a look at this yet?

Thanks,
Mark

**Comment by erikwinlof** [comment]
Hi Mark,

Sorry for taking so long, I just checked out the test and ran it. The process you have included is however so anonymized that I will not have any chance to reproduce the error that you describe i.e. Task9 & Task10 are here human tasks and I assume they are Service tasks in reality?

My advice would be to:

1. Set the pom.xml to the Activiti version you are using (you said 5.17 but the stack trace says 5.16.1) 

2. Make MyUnitTest.java run your actual (non anonymized process) lots of times until it the errors is thrown. (Note! Now MyUnitTest.java still references my-process.bpmn20.xml instead of MYBPMN.bpmn). 

3. Scale down your process to remove as much logic as possible while still making sure that the error is reproduced when running the test.

4. Anonymize the remaining bits if you wish but still making sure the error can be reproduced. Its ok if it happens occasionally, i.e. 1 out of 1000, as long as I can run the test and reproduce it.

Please give me a heads up when you have the test running and you can reproduce the error and I will be happy to try again!

Cheers, Erik

**Comment by markvt78** [comment]
Hi Erik,

Thanks for your reply. I will try this and get back to you.

Thanks,

Mark

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
