### ISSUE TITLE
org.activiti.engine.impl.persistence.entity.MessageEventSubscriptionEntity@640 was updated by another transaction concurrently

### ISSUE THREAD

**Issue by halfsoft** [Activiti/Activiti#741]
Here is a small and I hope good enough Unit test that demonstrates how deploying large amount of processes that rely on user tasks are failing regularly.
This is just one of the issues we are seeing but I hope a fix for it will maybe fix the other issues that we are getting as well.

In Core.java in validateResponse there is a sleep() to simulate delays that may be caused by connections to the DB or just doing work in the code. If the delay is not there or it is small enough there aren't any exceptions.

The file is a zip, just renamed to pdf.

[activiti-unit-test-template.zip.pdf](https://github.com/Activiti/Activiti/files/41543/activiti-unit-test-template.zip.pdf)

**Comment by halfsoft** [comment]
Also if we increase the number of instances to 10000 (instead of 1000) and we remove the Thread.sleep() we get a Deadlock exception:

    ERROR org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable  - Job 2710 failed
    org.apache.ibatis.exceptions.PersistenceException: 
    ### Error updating database.  Cause: org.h2.jdbc.JdbcSQLException: Deadlock detected. The current transaction was rolled back. Details: "
    Session #36 (user: SA) is waiting to lock PUBLIC.ACT_RU_JOB while locking PUBLIC.ACT_RU_EXECUTION (exclusive), PUBLIC.ACT_RU_EVENT_SUBSCR (exclusive), PUBLIC.ACT_RU_VARIABLE (exclusive).
    Session #31 (user: SA) is waiting to lock PUBLIC.ACT_RU_EXECUTION while locking PUBLIC.ACT_RU_JOB (exclusive)."; SQL statement:
    delete from ACT_RU_EXECUTION where ID_ = ? and REV_ = ? [40001-168]
    ### The error may involve org.activiti.engine.impl.persistence.entity.ExecutionEntity.deleteExecution-Inline
    ### The error occurred while setting parameters
    ### SQL: delete from ACT_RU_EXECUTION where ID_ = ? and REV_ = ?
    ### Cause: org.h2.jdbc.JdbcSQLException: Deadlock detected. The current transaction was rolled back. Details: "
    Session #36 (user: SA) is waiting to lock PUBLIC.ACT_RU_JOB while locking PUBLIC.ACT_RU_EXECUTION (exclusive), PUBLIC.ACT_RU_EVENT_SUBSCR (exclusive), PUBLIC.ACT_RU_VARIABLE (exclusive).
    Session #31 (user: SA) is waiting to lock PUBLIC.ACT_RU_EXECUTION while locking PUBLIC.ACT_RU_JOB (exclusive)."; SQL statement:
    delete from ACT_RU_EXECUTION where ID_ = ? and REV_ = ? [40001-168]
    	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
    	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150)
    	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:161)
    	at org.activiti.engine.impl.db.DbSqlSession$CheckedDeleteOperation.execute(DbSqlSession.java:293)
    	at org.activiti.engine.impl.db.DbSqlSession.flushRegularDeletes(DbSqlSession.java:922)
    	at org.activiti.engine.impl.db.DbSqlSession.flushDeletes(DbSqlSession.java:888)
    	at org.activiti.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:613)
    	at org.activiti.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:212)
    	at org.activiti.engine.impl.interceptor.CommandContext.close(CommandContext.java:138)
    	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:66)
    	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
    	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
    	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
    	at org.activiti.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:69)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.h2.jdbc.JdbcSQLException: Deadlock detected. The current transaction was rolled back. Details: "
    Session #36 (user: SA) is waiting to lock PUBLIC.ACT_RU_JOB while locking PUBLIC.ACT_RU_EXECUTION (exclusive), PUBLIC.ACT_RU_EVENT_SUBSCR (exclusive), PUBLIC.ACT_RU_VARIABLE (exclusive).
    Session #31 (user: SA) is waiting to lock PUBLIC.ACT_RU_EXECUTION while locking PUBLIC.ACT_RU_JOB (exclusive)."; SQL statement:
    delete from ACT_RU_EXECUTION where ID_ = ? and REV_ = ? [40001-168]
    	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
    	at org.h2.message.DbException.get(DbException.java:169)
    	at org.h2.message.DbException.get(DbException.java:146)
    	at org.h2.table.RegularTable.doLock(RegularTable.java:488)
    	at org.h2.table.RegularTable.lock(RegularTable.java:434)
    	at org.h2.command.dml.Delete.update(Delete.java:58)
    	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
    	at org.h2.command.Command.executeUpdate(Command.java:230)
    	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:194)
    	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41)
    	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66)
    	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45)
    	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
    	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
    	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
    	... 15 more

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
