### ISSUE TITLE
NullpointerException occured on referring Historic Variable(Serializable Type)

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#753]
Hi,

We found a bug, we report.
We are experiencing a NPE on referring Historic Variable(Serializable Type):

((HistoricVariableInstance) historicData).getValue();

# Occurrence condition
We are experiencing a NPE on referring HistoricVariableInstance(Serializable Type).
We are not experiencing a NPE on referring HistoricVariableInstance(String Type, etc.).

# Cause
Only Serializable Type, HistoricVariableInstance.class#getValue gets data from not Cache but RDB.
Therefore, HistoricVariableInstance.class#getValue try to get Context, but Context is null.

# Steps to Reproduce

0. We will build Postgres 9.4 environment.

1. We will build Activiti environment.
* Download https://github.com/Activiti/Activiti/releases/download/activiti-5.19.0/activiti-5.19.0.zip.
* Place "activiti-explorer.war" into in Tomcat's webapps directory, and then start the Tomcat.
* Place Postgres 9.4 JDBC Driver jar into %Tomcat_Root%/lib directory.
* Describe the connection setting in %Tomcat_Root%/webapps/activiti-explorer/WEB-INF/classes/db.properties.

2. We will install The project of the attached file.
https://drive.google.com/open?id=0ByO-BAU8ivtKcF80UUFUX0YtVU0

3. We will describe db.properties in %Project_Root%/src/main/resources/db.properties.

4. Execute jp.yoshimoto.historic_variable_npe.NullpointerExceptionReproduction.class, and then Check NullpointerException.

* Exception in thread "main" java.lang.NullPointerException
	at org.activiti.engine.impl.persistence.entity.ByteArrayRef.ensureInitialized(ByteArrayRef.java:96)
	at org.activiti.engine.impl.persistence.entity.ByteArrayRef.getBytes(ByteArrayRef.java:46)
	at org.activiti.engine.impl.persistence.entity.HistoricVariableInstanceEntity.getBytes(HistoricVariableInstanceEntity.java:138)
	at org.activiti.engine.impl.variable.ByteArrayType.getValue(ByteArrayType.java:32)
	at org.activiti.engine.impl.variable.SerializableType.getValue(SerializableType.java:49)
	at org.activiti.engine.impl.persistence.entity.HistoricVariableInstanceEntity.getValue(HistoricVariableInstanceEntity.java:129)
	at jp.yoshimoto.historic_variable_npe.NullpointerExceptionReproduction.main(NullpointerExceptionReproduction.java:53)

**Comment by whitecat** [comment]
Is there an issue in the JIRA that addresses this bug?

**Comment by daisuke-yoshimoto** [comment]
@whitecat 

The issue in the JIRA is the following url.
https://activiti.atlassian.net/browse/ACT-4185

But, the issue in the JIRA doesn't have enough information.
What kind of information do you need?
