### ISSUE TITLE
ActivitiException: unknown variable type name alfrescoScriptNode

### ISSUE THREAD

**Issue by 4F2E4A2E** [Activiti/Activiti#784]
Hello There!

We are currently having a hard time fetching runtime variables from an workflow, not matter what we do and which workflow we try.
![bildschirmfoto 2016-01-23 um 12 31 56](https://cloud.githubusercontent.com/assets/64590/12529977/a3852df6-c1cd-11e5-8174-90c05ea771ce.png)

We uploaded the Workflow via A-Explorer and started the Workflow via Alfresco. In Alfresco the Workflow seams to work just fine and it does pretty much everything we need, but our goal is to store some information inside variables inside the workflow, so we can fetch &/ set them via rest-api during it's process.

Our Setup:
Alfresco Community v5.0.0 (d r99759-b2) schema 8022
Activiti-Explorer and Activiti-Rest 5.16.4 (with correct db cfg and driver, deployed on the same tomcat as alfresco)
PostgreSQLDB (alfresco install db seetings)

CustomA.bp
[CustomA.zip](https://github.com/Activiti/Activiti/files/101837/CustomA.zip)

[alfrescoScriptNode_exception-stack-trace.txt](https://github.com/Activiti/Activiti/files/101834/alfrescoScriptNode_exception-stack-trace.txt)

Stackoverflow old, but similar issue: http://stackoverflow.com/questions/16218554/activitiexception-unknown-variable-type-name-alfrescoscriptnode

We would appreciated your help, thank you!

**Comment by jbarrez** [comment]
This exception means the engine does not know a custom Variable type. 
You need to add variable type classes to the engine, see https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L1463

**Comment by 4F2E4A2E** [comment]
Thank you alot for you message, i think to understand it better now. I could find those Variable Types in the Alfresco 5d Tag[1] alog with the config [2], but i still don't understand why or where i do have to set those settings. In Alfresco? In Activiti? Why to set it again if those settings are already in the alfresco jar?

Please help us to understand this, thank you!

1: https://github.com/Alfresco/community-edition/blob/afde3f58f91567b6f7eaa0bbac5e5adc38087fe0/projects/repository/source/java/org/alfresco/repo/workflow/activiti/variable/ScriptNodeVariableType.java
2: https://github.com/Alfresco/community-edition/blob/V5.0.d/root/projects/repository/config/alfresco/activiti-context.xml

**Comment by jbarrez** [comment]
Your process definitions/instances use a variable that the engine by default doesn't know, but is added by Alfresco. So in order for another engine to know about that custom variable type, you need to register that variable type with the engine.

**Comment by 4F2E4A2E** [comment]
So i have to pass those Types to Activiti along with the Workflow or deliver a lib which contains those types. Got it, thanks. Alfresco uses the activiti-context.xml for this configuration, but where should i configure those settings in Activiti 5.16.4?

**Comment by jbarrez** [comment]
That depends on how you are using it. See the link above on the process engine configuration. 
If you are using it in another way (like in Explorer, you'd need something else (xml or java config ... not sure anymore what 5.16.4 used)

**Comment by 4F2E4A2E** [comment]
Ok, thanks! We are using Activiti-Explorer and could not find any Spring-Cfg-File there for configuring those beans via CDI:
> ls activiti-5.16.4\wars\activiti-explorer\WEB-INF\classes
> activiti-login-context.xml
> activiti-ui-context.xml
> db.properties
> editor.html
> engine.properties
> log4j.properties
> org
> plugins.xml
> rebel.xml
> stencilset.json
> ui.properties
> ui.properties.alfresco

I will try my luck with some standard Spring-Cfg files.
BTW: @jbarrez your book is amazin, thank you for that too!

**Comment by jbarrez** [comment]
The configuration is done with JavaConfig, not XML: https://github.com/Activiti/Activiti/blob/activiti-5.16.4/modules/activiti-webapp-explorer2/src/main/java/org/activiti/explorer/conf/ActivitiEngineConfiguration.java

Btw, it's not my book, the author is @tijsrademakers

**Comment by 4F2E4A2E** [comment]
Oh, the forewords.
You are great anyway :+1:

**Comment by 4F2E4A2E** [comment]
Hey there, we again.
We created the Configuration in Java, packt into a jar via maven, deployt on WEB-INF/lib on activiti-explorer and activiti-rest, but still gets the same error:
unknown variable type name alfrescoScriptNode

Here our Java Class:
```
package at.test.activiti.cfg;

import java.sql.Driver;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.activiti.engine.FormService;
import org.activiti.engine.HistoryService;
import org.activiti.engine.IdentityService;
import org.activiti.engine.ManagementService;
import org.activiti.engine.ProcessEngine;
import org.activiti.engine.RepositoryService;
import org.activiti.engine.RuntimeService;
import org.activiti.engine.TaskService;
import org.activiti.engine.form.AbstractFormType;
import org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl;
import org.activiti.engine.impl.variable.DefaultVariableTypes;
import org.activiti.engine.impl.variable.VariableType;
import org.activiti.spring.ProcessEngineFactoryBean;
import org.activiti.spring.SpringProcessEngineConfiguration;
import org.alfresco.repo.workflow.activiti.variable.ScriptNodeListVariableType;
import org.alfresco.repo.workflow.activiti.variable.ScriptNodeVariableType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.SimpleDriverDataSource;
import org.springframework.transaction.PlatformTransactionManager;

@Configuration
public class CustomActivitiEngineConfiguration {


	private final Logger log = LoggerFactory.getLogger(CustomActivitiEngineConfiguration.class);

	@Autowired
	protected Environment environment;

	@Bean
	public DataSource dataSource() {
		SimpleDriverDataSource ds = new SimpleDriverDataSource();

		// Connection settings
		ds.setUrl(environment.getProperty("jdbc.url", "jdbc:postgresql://localhost:5432/alfresco"));
		ds.setUsername(environment.getProperty("jdbc.username", "alfresco"));
		ds.setPassword(environment.getProperty("jdbc.password", "test"));

		return ds;
	}

	@Bean(name = "transactionManager")
	public PlatformTransactionManager annotationDrivenTransactionManager() {
		DataSourceTransactionManager transactionManager = new DataSourceTransactionManager();
		transactionManager.setDataSource(dataSource());
		return transactionManager;
	}

	@Bean(name="processEngineFactoryBean")
	public ProcessEngineFactoryBean processEngineFactoryBean() {
		ProcessEngineFactoryBean factoryBean = new ProcessEngineFactoryBean();
		factoryBean.setProcessEngineConfiguration(processEngineConfiguration());
		return factoryBean;
	}

	@Bean(name="processEngine")
	public ProcessEngine processEngine() {
		// Safe to call the getObject() on the @Bean annotated processEngineFactoryBean(), will be
		// the fully initialized object instanced from the factory and will NOT be created more than once
		try {
			return processEngineFactoryBean().getObject();
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

	@Bean(name = "activitiProcessEngineConfiguration")
	public ProcessEngineConfigurationImpl activitiProcessEngineConfiguration() {
		SpringProcessEngineConfiguration processEngineConfiguration = new SpringProcessEngineConfiguration();
		System.out.println("------------------>");

		List<VariableType> formTypes = new ArrayList<VariableType>();
		//TODO add custom types
//		formTypes.add(new UserFormType());
//		formTypes.add(new ProcessDefinitionFormType());
//		formTypes.add(new MonthFormType());
		formTypes.add(new ScriptNodeVariableType());
		formTypes.add(new ScriptNodeListVariableType());
		processEngineConfiguration.setCustomPostVariableTypes(formTypes);

		return processEngineConfiguration;
	}

	@Bean(name = "processEngineConfiguration")
	public ProcessEngineConfigurationImpl processEngineConfiguration() {
		SpringProcessEngineConfiguration processEngineConfiguration = new SpringProcessEngineConfiguration();
		System.out.println("------------------>");

		List<VariableType> formTypes = new ArrayList<VariableType>();
		//TODO add custom types
//		formTypes.add(new UserFormType());
//		formTypes.add(new ProcessDefinitionFormType());
//		formTypes.add(new MonthFormType());
		formTypes.add(new ScriptNodeVariableType());
		formTypes.add(new ScriptNodeListVariableType());
		processEngineConfiguration.setCustomPostVariableTypes(formTypes);

		return processEngineConfiguration;
	}
	@Bean
	public RepositoryService repositoryService() {
		return processEngine().getRepositoryService();
	}

	@Bean
	public RuntimeService runtimeService() {
		return processEngine().getRuntimeService();
	}

	@Bean
	public TaskService taskService() {
		return processEngine().getTaskService();
	}

	@Bean
	public HistoryService historyService() {
		return processEngine().getHistoryService();
	}

	@Bean
	public FormService formService() {
		return processEngine().getFormService();
	}

	@Bean
	public IdentityService identityService() {
		return processEngine().getIdentityService();
	}

	@Bean
	public ManagementService managementService() {
		return processEngine().getManagementService();
	}
}
```

What is happening? Please guide us.

**Comment by 4F2E4A2E** [comment]
I did get it to try to load my config in the activiti-ui-context.xml
```
04:18:33,415 [localhost-startStop-1] INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory  - Overriding bean definition for bean 'processEngineConfiguration': replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=activitiEngineConfiguration; factoryMethodName=processEngineConfiguration; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]] with [Generic bean: class [at.softcom.activiti.cfg.SCActivitiEngineConfiguration]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in class path resource [activiti-ui-context.xml]]
```

What next?

**Comment by 4F2E4A2E** [comment]
We did manage to build the activiti-engine module with those types.
We added the nessecery dependency of alfresco-5.0.d to it, it compiles, builds but activiti-explorer wont start:
```
Jan 25, 2016 9:39:11 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Jan 25, 2016 9:39:12 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.activiti.explorer.servlet.WebConfigurer
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoDataConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected org.activiti.engine.IdentityService org.activiti.explorer.conf.DemoDataConfiguration.identityService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityService' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.IdentityService org.activiti.explorer.conf.ActivitiEngineConfiguration.identityService()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.ProcessEngine org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine()] threw exception; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:292)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.activiti.explorer.servlet.WebConfigurer.contextInitialized(WebConfigurer.java:40)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected org.activiti.engine.IdentityService org.activiti.explorer.conf.DemoDataConfiguration.identityService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityService' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.IdentityService org.activiti.explorer.conf.ActivitiEngineConfiguration.identityService()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.ProcessEngine org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine()] threw exception; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:508)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
	... 24 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityService' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.IdentityService org.activiti.explorer.conf.ActivitiEngineConfiguration.identityService()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.ProcessEngine org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine()] threw exception; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:597)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:989)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1017)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:480)
	... 26 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.IdentityService org.activiti.explorer.conf.ActivitiEngineConfiguration.identityService()] threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.ProcessEngine org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine()] threw exception; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:188)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:586)
	... 38 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngine' defined in class path resource [org/activiti/explorer/conf/ActivitiEngineConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.ProcessEngine org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine()] threw exception; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:597)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1094)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:989)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:324)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e.processEngine(<generated>)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration.identityService(ActivitiEngineConfiguration.java:134)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e.CGLIB$identityService$10(<generated>)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e$$FastClassBySpringCGLIB$$ef2b10c9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e.identityService(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:166)
	... 39 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.activiti.engine.ProcessEngine org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine()] threw exception; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:188)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:586)
	... 60 more
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine(ActivitiEngineConfiguration.java:84)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e.CGLIB$processEngine$4(<generated>)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e$$FastClassBySpringCGLIB$$ef2b10c9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration$$EnhancerBySpringCGLIB$$ddf7331e.processEngine(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:166)
	... 61 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1512)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:250)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor$1.intercept(ConfigurationClassEnhancer.java:381)
	at org.activiti.spring.ProcessEngineFactoryBean$$EnhancerBySpringCGLIB$$ecd67350.getObject(<generated>)
	at org.activiti.explorer.conf.ActivitiEngineConfiguration.processEngine(ActivitiEngineConfiguration.java:82)
	... 71 more
Caused by: java.lang.NullPointerException
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.initVariableTypes(ProcessEngineConfigurationImpl.java:1070)
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.init(ProcessEngineConfigurationImpl.java:286)
	at org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl.buildProcessEngine(ProcessEngineConfigurationImpl.java:274)
	at org.activiti.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:65)
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:60)
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 78 more

Jan 25, 2016 9:39:12 PM org.apache.catalina.core.StandardContext listenerStop
SEVERE: Exception sending context destroyed event to listener instance of class org.activiti.explorer.servlet.WebConfigurer
java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener registered?
	at org.springframework.web.context.support.WebApplicationContextUtils.getRequiredWebApplicationContext(WebApplicationContextUtils.java:84)
	at org.activiti.explorer.servlet.WebConfigurer.contextDestroyed(WebConfigurer.java:73)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5063)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5719)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by 4F2E4A2E** [comment]
We have it:
```
variableTypes.addType(new CustomObjectType("alfrescoScriptNode", ScriptNodeVariableType.class));
      variableTypes.addType(new CustomObjectType("alfrescoScriptNodeList", ScriptNodeListVariableType.class));
```

Thank you so much and we!

**Comment by jbarrez** [comment]
Thanks for posting back and figuring it out :-)
