### ISSUE TITLE
NPE using @MockServiceTask and throwing RuntimeException inside service task

### ISSUE THREAD

**Issue by mpevec** [Activiti/Activiti#789]
Using JUnit with @MockServiceTask when you throw a new RuntimeException inside of the mocked service task, you receive NPE:

`java.lang.NullPointerException: null
    at org.activiti.engine.impl.bpmn.helper.ErrorPropagation.findMatchingExceptionMapping(ErrorPropagation.java:306) ~[activiti-engine-6.0.0.Beta2.jar:6.0.0.Beta2]
    at org.activiti.engine.impl.bpmn.helper.ErrorPropagation.mapException(ErrorPropagation.java:269) ~[activiti-engine-6.0.0.Beta2.jar:6.0.0.Beta2]
    at org.activiti.engine.impl.bpmn.helper.ClassDelegate.execute(ClassDelegate.java:159) ~[activiti-engine-6.0.0.Beta2.jar:6.0.0.Beta2]`

The problem exists in the method:

`protected static String findMatchingExceptionMapping(Exception e, List<MapExceptionEntry> exceptionMap)`

in ErrorPropagation.java

where exceptionMap is not initialized (its null). In my opinion a null check should be applied in ErrorPropagation.java

The workaround is to extend ClassDelegate (and hence TestActivityBehaviorFactory ...)..

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
