### ISSUE TITLE
activiti 6 sql exception

### ISSUE THREAD

**Issue by masrawi** [Activiti/Activiti#800]
I am getting this exception after upgrading:

```
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: Ung?ltiger Spaltentyp: 1111
### The error may exist in org/activiti/db/mapping/entity/Execution.xml
### The error may involve org.activiti.engine.impl.persistence.entity.ExecutionEntityImpl.selectExecutionsByRootProcessInstanceId-Inline
### The error occurred while setting parameters
### SQL: select * from ACT_RU_EXECUTION     where ROOT_PROC_INST_ID_ = ?
### Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: Ung?ltiger Spaltentyp: 1111
    at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23) ~[mybatis-3.2.5.jar!/:3.2.5]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:107) ~[mybatis-3.2.5.jar!/:3.2.5]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98) ~[mybatis-3.2.5.jar!/:3.2.5]
    at org.activiti.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:434) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:425) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:420) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:401) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.persistence.entity.data.AbstractDataManager.getList(AbstractDataManager.java:124) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.persistence.entity.data.impl.MybatisExecutionDataManager.findExecutionsByRootProcessInstanceId(MybatisExecutionDataManager.java:126) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.persistence.entity.ExecutionEntityManagerImpl.findExecutionTree(ExecutionEntityManagerImpl.java:121) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.persistence.entity.ExecutionEntityManagerImpl.deleteChildExecutions(ExecutionEntityManagerImpl.java:377) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.persistence.entity.ExecutionEntityManagerImpl.deleteProcessInstanceExecutionEntity(ExecutionEntityManagerImpl.java:357) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.agenda.EndExecutionOperation.run(EndExecutionOperation.java:168) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:72) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:59) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:43) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
    at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:34) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
    at org.activiti.engine.impl.ManagementServiceImpl.executeJob(ManagementServiceImpl.java:77) ~[activiti-engine-6.0.0.Beta2.jar!/:6.0.0.Beta2]
```

**Comment by balsarori** [comment]
Thanks for reporting the issue. 

Can you provide us with extra information such as what database are you using, when does this exception happen, steps to reproduce this issue.

**Comment by masrawi** [comment]
I am using oracle. these exceptions seems to be just before the workflow end ( the last step before the end) . it used to work under version 5. I will try to reproduce it and submit a junit

**Comment by masrawi** [comment]
ROOT_PROC_INST_ID_ is null in the db which seems to be the main problem so I guess the code responsible to set it at some point is the cause (?)

I somehow can not reproduce it as a junit test. if I manually  issue:

```
update ACT_RU_EXECUTION set ROOT_PROC_INST_ID_=9594603 where PROC_INST_ID_=9594603;
```
and retry the process then it passes.

**Comment by jbarrez** [comment]
@masrawi : Any idea where this process is coming from? Could it be a v5 process instance? For a v5 process instance the ROOT_PROC_INST_ID_ can be null, but for a v6 not. Or rather, shouldn't.

Are you running with v5 compatibility? Or better, how did you do the v5->v6 migration?

**Comment by masrawi** [comment]
the process is initialized **after** upgrading. the upgrade is done only by upgrading the new activiti version in pom.xml

**Comment by jbarrez** [comment]
Hmmm, so then there must be a subtle bug that causes it somehow to become null  (which should never happen) ... Any particular way you are starting the process instance vs the unit test ... ? (looking for a needle in hackstack here)

**Comment by balsarori** [comment]
@masrawi It will be very helpful if you share a process definition that we can use to reproduce this issue

**Comment by masrawi** [comment]
correction: the process **is** an old one (v5) and was paused and then reactivated with v6

**Comment by yvoswillens** [comment]
@masrawi Are you sure you're running v6 in compatibility mode?
I've created a test project which first suspends a process instance with a v5 engine.
Then that process instance is activated using a v5 engine. 
When the "activiti5CompatibilityEnabled" config flag is not set it has the same behaviour described by you.
But with the compatibility mode on it works fine.

Could you check that? Or provide a process definition so that we can reproduce it.

**Comment by masrawi** [comment]
activiti5CompatibilityEnabled is not set in my case.

**Comment by tijsrademakers** [comment]
@masrawi when you upgrade to Activiti 6 with process instances / definitions etc of Activiti 5, the activiti5CompatibilityEnabled property needs to set to true. This is a required part of a migration to Activiti 6. We will document this in the user guide of course.

**Comment by Salaboy** [comment]
closing this due to inactivity, please re-open if this is still an issue.

**Comment by bobosb** [comment]
when ID_ is null, it also accurs，my activiti is 5.19

org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='id', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111
### The error may exist in org/activiti/db/mapping/entity/Model.xml
### The error may involve org.activiti.engine.impl.persistence.entity.ModelEntity.selectModel-Inline
### The error occurred while setting parameters
### SQL: select * from ACT_RE_MODEL where ID_ = ?
### Cause: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='id', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #1 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at org.activiti.engine.impl.db.DbSqlSession.selectOne(DbSqlSession.java:451)
	at org.activiti.engine.impl.persistence.entity.ModelEntityManager.findModelById(ModelEntityManager.java:132)
	at org.activiti.engine.impl.cmd.GetModelCmd.execute(GetModelCmd.java:36)
	at org.activiti.engine.impl.cmd.GetModelCmd.execute(GetModelCmd.java:26)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:37)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
	at org.activiti.engine.impl.RepositoryServiceImpl.getModel(RepositoryServiceImpl.java:236)
