### ISSUE TITLE
Activiti  [process definitions with the same key] when building and deploying via bamboo to open shift

### ISSUE THREAD

**Issue by koekemos** [Activiti/Activiti#896]
Hi Guys,

I am using activiti with springboot, and building a docker image.

This is the version of activiti that i am using 
`<activiti.version>6.0.0.Beta2</activiti.version>`

```
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter-actuator</artifactId>
            <version>${activiti.version}</version>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-camel</artifactId>
            <version>${activiti.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.camel</groupId>
                    <artifactId>camel-spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I get the following error when running a build plan and deployment plan from bamboo.

The build plan uses maven 3 to build a jar and pushes it to our nexus repository.
The deployment plan builds a docker image with the new jar an pushes the image to open shift.

```
org.activiti.engine.ActivitiException: The deployment contains process definitions with the same key (process id attribute), this is not allowed
	at org.activiti.engine.impl.bpmn.deployer.BpmnDeploymentHelper.verifyProcessDefinitionsDoNotShareKeys(BpmnDeploymentHelper.java:56)
	at org.activiti.engine.impl.bpmn.deployer.BpmnDeployer.deploy(BpmnDeployer.java:71)
	at org.activiti.engine.impl.persistence.deploy.DeploymentManager.deploy(DeploymentManager.java:53)
	at org.activiti.engine.impl.cmd.DeployCmd.executeDeploy(DeployCmd.java:110)
	at org.activiti.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:60)
	at org.activiti.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:40)
	at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:38)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:77)
	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:59)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:43)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:34)
	at org.activiti.engine.impl.RepositoryServiceImpl.deploy(RepositoryServiceImpl.java:84)
	at org.activiti.engine.impl.repository.DeploymentBuilderImpl.deploy(DeploymentBuilderImpl.java:171)
	at org.activiti.spring.autodeployment.DefaultAutoDeploymentStrategy.deployResources(DefaultAutoDeploymentStrategy.java:63)
	at org.activiti.spring.SpringProcessEngineConfiguration.autoDeployResources(SpringProcessEngineConfiguration.java:109)
	at org.activiti.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:67)
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:57)
	at org.activiti.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:32)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	... 62 common frames omitted
```

1. I have cleared the activiti tables on the dev environment and the issue persisted
1. I have change hibernate: ddl-auto:  from update to create-drop, but still the issue persisted
2. I have compiled the project locally and compared the jar size with the one that was build and pushed to nexus and there is no difference.
3. I created a docker image with the local jar and ran it with H2 and it started up successfully.
4. I created a docker image with the remote jar and ran it with the H2 and it failed with the exact same error. 

The error went away after running the build and deployment plan on bamboo a significant amount of times. What could be causing this ?

**Comment by koekemos** [comment]
The issue was that bamboo was not doing a clean build. It was duplicating one of the activiti diagrams under /processes. Once the force clean build was checked it started successfully on open shift.
