### ISSUE TITLE
Reduce dependency on Drools Engine

### ISSUE THREAD

**Issue by huksley** [Activiti/Activiti#984]
Currently (as of version 5.19.0.2) Activiti have strong dependency on Drools Engine.

If I declare `<businessRuleTask>` in BPMN file then during deploying I have exception because of creating instance of BusinessRuleTaskActivityBehavior:
```
java.lang.ClassNotFoundException: org.drools.runtime.rule.AgendaFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1284)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1118)
	at org.activiti.engine.impl.bpmn.parser.factory.DefaultActivityBehaviorFactory.createBusinessRuleTaskActivityBehavior(DefaultActivityBehaviorFactory.java:271)
	at org.activiti.engine.impl.bpmn.parser.handler.BusinessRuleParseHandler.executeParse(BusinessRuleParseHandler.java:37)
```

Do better support different rule engines (and avoid packaging Drools Engine for the sole purpose of satisfying classloader) there some delegation must be introduced so Drools Engine will be used later in execution phase or custom implementation, if it is required.

**Comment by tijsrademakers** [comment]
Activiti doesn't have a strong dependency on the Drools Engine. Only when you deploy a business rule task, you will get this ClassNotFoundException, because we instantiate the rule task logic at deploy time.

**Comment by huksley** [comment]
This exception is occurring when I create <businessTask activity:className=""/> type of business task.
It is expected in such situation to have no dependency on Drools.

**Comment by tijsrademakers** [comment]
The business rule task has a dependency on Drools in Activiti 5. Or are you defining a custom class?

**Comment by huksley** [comment]
Yes I am trying to use `<businessRule...` by defining custom class of BusinessRuleTaskActivityBehavior and implement it in different way. However I can`t create my instance because of missing Drools class.
Next message is full stacktrace in this scenario.

**Comment by huksley** [comment]
```
org.activiti.engine.ActivitiException: couldn't instantiate class ru.test.bpm.activiti.CustomBRTask
	at org.activiti.engine.impl.util.ReflectUtil.instantiate(ReflectUtil.java:137)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.defaultInstantiateDelegate(ClassDelegate.java:242)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.instantiateDelegate(ClassDelegate.java:232)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.getActivityBehaviorInstance(ClassDelegate.java:211)
	at org.activiti.engine.impl.bpmn.helper.ClassDelegate.execute(ClassDelegate.java:154)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:636)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:629)
...
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
	at org.activiti.engine.impl.RuntimeServiceImpl.startProcessInstance(RuntimeServiceImpl.java:409)
	at org.activiti.engine.impl.runtime.ProcessInstanceBuilderImpl.start(ProcessInstanceBuilderImpl.java:76)
Caused by: org.activiti.engine.ActivitiClassLoadingException: Could not load class: ru.test.bpm.activiti.CustomBRTask
	at org.activiti.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:87)
	at org.activiti.engine.impl.util.ReflectUtil.instantiate(ReflectUtil.java:134)
	... 387 more
Caused by: java.lang.NoClassDefFoundError: org/drools/runtime/rule/AgendaFilter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.activiti.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:291)
	at org.activiti.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:68)
	... 388 more
Caused by: java.lang.ClassNotFoundException: org.drools.runtime.rule.AgendaFilter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1284)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1118)
	... 392 more
```

**Comment by tijsrademakers** [comment]
Ok thanks, I'll have a look at it.

**Comment by huksley** [comment]
During deployment
```
java.lang.NoClassDefFoundError: org/drools/runtime/rule/AgendaFilter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.activiti.engine.impl.bpmn.parser.factory.DefaultActivityBehaviorFactory.createBusinessRuleTaskActivityBehavior(DefaultActivityBehaviorFactory.java:264)
	at org.activiti.engine.impl.bpmn.parser.handler.BusinessRuleParseHandler.executeParse(BusinessRuleParseHandler.java:37)
	at org.activiti.engine.impl.bpmn.parser.handler.BusinessRuleParseHandler.executeParse(BusinessRuleParseHandler.java:25)
	at org.activiti.engine.impl.bpmn.parser.handler.AbstractBpmnParseHandler.parse(AbstractBpmnParseHandler.java:81)
	at org.activiti.engine.impl.bpmn.parser.handler.AbstractFlowNodeBpmnParseHandler.parse(AbstractFlowNodeBpmnParseHandler.java:27)
	at org.activiti.engine.impl.bpmn.parser.handler.AbstractActivityBpmnParseHandler.parse(AbstractActivityBpmnParseHandler.java:36)
...
```

**Comment by huksley** [comment]
I have a workaround which is actually quite nice - I implement CustomBusinessRuleParseHandler and use ClassDelegate with my TaskBehavior based implementation inside.
The downside is using `.impl.` namespace APIs.

My wish would be having some sort of RuleDelegate (analagous to JavaDelegate) which, besides Execution argument will have additional parameters, i.e. ruleNames, input and output vars.

Thank you for your time and fantastic product!

**Comment by tijsrademakers** [comment]
Thanks, there's now a BusinessRuleTaskDelegate interface you can implement. This removes the Drools dependency need when using a custom business rule task that implements this new interface.
