### ISSUE TITLE
Update camel module to the latest camel version (2.17.x)

### ISSUE THREAD

**Issue by rolandobermudez** [Activiti/Activiti#990]
Current camel module version 5.21.0 throws runtime exception at initialization time

Caused by: java.lang.NoSuchMethodError: org.apache.camel.management.DefaultManagementMBeanAssembler: method <init>()V not found
	at org.apache.camel.spring.spi.SpringManagementMBeanAssembler.<init>(SpringManagementMBeanAssembler.java:44) ~[camel-spring-2.11.0.jar:2.11.0]
	at org.apache.camel.spring.SpringCamelContext.createManagementMBeanAssembler(SpringCamelContext.java:199) ~[camel-spring-2.11.0.jar:2.11.0]
	at org.apache.camel.impl.DefaultCamelContext.<init>(DefaultCamelContext.java:293) ~[camel-core-2.17.2.jar:2.17.2]
	at org.apache.camel.spring.SpringCamelContext.<init>(SpringCamelContext.java:67) ~[camel-spring-2.11.0.jar:2.11.0]
	at org.apache.camel.spring.boot.CamelAutoConfiguration.camelContext(CamelAutoConfiguration.java:50) ~[camel-spring-boot-2.17.2.jar:2.17.2]
	at org.apache.camel.spring.boot.CamelAutoConfiguration$$EnhancerBySpringCGLIB$$caf440b.CGLIB$camelContext$6(<generated>) ~[camel-spring-boot-2.17.2.jar:2.17.2]
	at org.apache.camel.spring.boot.CamelAutoConfiguration$$EnhancerBySpringCGLIB$$caf440b$$FastClassBySpringCGLIB$$c0263e9b.invoke(<generated>) ~[camel-spring-boot-2.17.2.jar:2.17.2]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	at org.apache.camel.spring.boot.CamelAutoConfiguration$$EnhancerBySpringCGLIB$$caf440b.camelContext(<generated>) ~[camel-spring-boot-2.17.2.jar:2.17.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
	... 30 common frames omitted

**Comment by tijsrademakers** [comment]
Done on Activiti Github master version
